
OPTIONS COMPRESS=YES;

LIBNAME Conso "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Sep21_All_Cnty_Frd_Tagged";

OPTIONS MPRINT MLOGIC SYMBOLGEN;

/* Analysis */

DATA rule_hit_CR;
SET 
Conso.rule_hit_last_3_months_cr;
where UPCASE(RULE_NAME_STRG) IN
(
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_CREDIT',
'HR_GLOBAL_BLACKLIST_ALL_TXNS',           
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_GLOBAL_BLACKLISTING_N1_1',
'HR_COUNTRY_BLACKLIST_MER_BD',       
'HR_GLOBAL_BLACKLISTINGN1_TW'
) and CLIENT_XID not in ("SC_CCMSHK_CR" "SC_PMTHK_CR");
RUN;

PROC SORT DATA=rule_hit_CR OUT=rule_hit_CR NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA last_3_months_CR;
SET 
Conso.last_3_months_data_cr;
where CRD_CLNT_ID not in ("SC_CCMSHK_CR" "SC_PMTHK_CR");
RUN;

PROC SORT DATA=last_3_months_CR OUT=last_3_months_CR NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SQL;
CREATE TABLE CHECK_CR AS
Select  R.RULE_NAME_STRG, T.* from rule_hit_CR R left join last_3_months_CR T on R.FI_TRANSACTION_ID = T.FI_TRANSACTION_ID where
UPPER(R.RULE_NAME_STRG) in (
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_CREDIT',
'HR_GLOBAL_BLACKLIST_ALL_TXNS',           
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_GLOBAL_BLACKLISTING_N1_1',
'HR_COUNTRY_BLACKLIST_MER_BD',       
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
QUIT;