
OPTIONS COMPRESS=YES;

LIBNAME Indi "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";

LIBNAME Conso "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Sep21";

OPTIONS MPRINT MLOGIC SYMBOLGEN;


/* Transaction Data */

PROC DELETE DATA = TXN_CNTY_NO_HHDR_CR; RUN;

%MACRO DISP(CNTY);

PROC SQL;
CREATE TABLE DISP AS SELECT * FROM
(
(SELECT * FROM Indi.FALT002_&CNTY._CR_JUN2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT002_&CNTY._CR_JUL2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT002_&CNTY._CR_AUG2021)
);
QUIT;

PROC APPEND DATA=DISP BASE=TXN_CNTY_NO_HHDR_CR FORCE;

%MEND;

%DISP(AE);
/*%DISP(HK);*/
%DISP(IN);
%DISP(MY);
%DISP(SG);


/* Rule Data */

PROC DELETE DATA = RULE_CNTY_NO_HKDR_CR; RUN;

%MACRO DISP(CNTY);

PROC SQL;
CREATE TABLE DISP AS SELECT * FROM
(
(SELECT * FROM Indi.FALT003_&CNTY._CR_JUN2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT003_&CNTY._CR_JUL2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT003_&CNTY._CR_AUG2021)
);
QUIT;

PROC APPEND DATA=DISP BASE=RULE_CNTY_NO_HKDR_CR FORCE;

%MEND;

%DISP(AE);
/*%DISP(HK);*/
%DISP(IN);
%DISP(MY);
%DISP(SG);


/* Analysis */

DATA rule_hit_CR;
SET 
Conso.rule_hit_last_3_months_cr
RULE_CNTY_NO_HKDR_CR;
where UPCASE(RULE_NAME_STRG) IN
(
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_CREDIT',
'HR_GLOBAL_BLACKLIST_ALL_TXNS',           
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_GLOBAL_BLACKLISTING_N1_1',
'HR_COUNTRY_BLACKLIST_MER_BD',       
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
RUN;


DATA last_3_months_CR;
SET 
TXN_CNTY_NO_HHDR_CR
Conso.last_3_months_data_cr;
RUN;


PROC SQL;
CREATE TABLE CHECK_CR AS
Select  R.RULE_NAME_STRG, T.* from rule_hit_CR R left join last_3_months_CR T on R.FI_TRANSACTION_ID = T.FI_TRANSACTION_ID where
UPPER(RULE_NAME_STRG) in (
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_CREDIT',
'HR_GLOBAL_BLACKLIST_ALL_TXNS',           
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_GLOBAL_BLACKLISTING_N1_1',
'HR_COUNTRY_BLACKLIST_MER_BD',       
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
QUIT;