
OPTIONS COMPRESS=YES;

LIBNAME Conso "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Sep21_All_Cnty_Frd_Tagged";

OPTIONS MPRINT MLOGIC SYMBOLGEN;

/* Analysis */

DATA rule_hit_DB;
SET 
Conso.rule_hit_last_3_months_db;
where UPCASE(RULE_NAME_STRG) IN
(
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT'
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_COUNTRY_BLACKLIST_MER_BD',
'HR_COUNTRY_BLACKLIST_MER_ID',
'HR_GLOBAL_BLACKLISTINGN1_TW'
) and
CLIENT_XID not in ("SC_HOGANHK_DB");
RUN;

PROC SORT DATA=rule_hit_DB OUT=rule_hit_DB NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA last_3_months_DB;
SET 
Conso.last_3_months_data_db;
where CRD_CLNT_ID not in ("SC_HOGANHK_DB");
RUN;

PROC SORT DATA=last_3_months_DB OUT=last_3_months_DB NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SQL;
Create table CHECK_DB AS
Select R.RULE_NAME_STRG, T.* from rule_hit_DB R left join last_3_months_DB T on R.FI_TRANSACTION_ID = T.FI_TRANSACTION_ID where
UPPER(R.RULE_NAME_STRG) in (
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT'
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_COUNTRY_BLACKLIST_MER_BD',
'HR_COUNTRY_BLACKLIST_MER_ID',
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
QUIT;