
OPTIONS COMPRESS=YES;

LIBNAME Indi "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Debit";

LIBNAME Conso "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Sep21";

OPTIONS MPRINT MLOGIC SYMBOLGEN;

/* Transaction Data */

PROC DELETE DATA = TXN_CNTY_NO_HHDR_DB; RUN;

%MACRO DISP(CNTY);

PROC SQL;
CREATE TABLE DISP AS SELECT * FROM
(
(SELECT * FROM Indi.FALT002_&CNTY._DB_JUN2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT002_&CNTY._DB_JUL2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT002_&CNTY._DB_AUG2021)
);
QUIT;

PROC APPEND DATA=DISP BASE=TXN_CNTY_NO_HHDR_DB FORCE;

%MEND;

%DISP(AE);
/*%DISP(HK);*/
%DISP(IN);
%DISP(MY);
%DISP(SG);


/* Rule Data */

PROC DELETE DATA = RULE_CNTY_NO_HKDR_DB; RUN;

%MACRO DISP(CNTY);

PROC SQL;
CREATE TABLE DISP AS SELECT * FROM
(
(SELECT * FROM Indi.FALT003_&CNTY._DB_JUN2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT003_&CNTY._DB_JUL2021) OUTER UNION CORR
(SELECT * FROM Indi.FALT003_&CNTY._DB_AUG2021)
);
QUIT;

PROC APPEND DATA=DISP BASE=RULE_CNTY_NO_HKDR_DB FORCE;

%MEND;

%DISP(AE);
/*%DISP(HK);*/
%DISP(IN);
%DISP(MY);
%DISP(SG);

/* Analysis */

DATA rule_hit_DB;
SET 
Conso.rule_hit_last_3_months_db
RULE_CNTY_NO_HKDR_DB;
where UPCASE(RULE_NAME_STRG) IN
(
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT'
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_COUNTRY_BLACKLIST_MER_BD',
'HR_COUNTRY_BLACKLIST_MER_ID',
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
RUN;

DATA last_3_months_DB;
SET 
TXN_CNTY_NO_HHDR_DB
Conso.last_3_months_data_db;
RUN;


PROC SQL;
Create table CHECK_DB AS
Select R.RULE_NAME_STRG, T.* from rule_hit_DB R left join last_3_months_DB T on R.FI_TRANSACTION_ID = T.FI_TRANSACTION_ID where
UPPER(R.RULE_NAME_STRG) in (
'HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT'
'HR_GLOBAL_BLACKLIST_MIDS_SUPRESS',
'HR_COUNTRY_BLACKLIST_MER_BD',
'HR_COUNTRY_BLACKLIST_MER_ID',
'HR_GLOBAL_BLACKLISTINGN1_TW'
);
QUIT;