 
PROC DELETE DATA = RULE_PERFORMENCE_CR; RUN;

****COMMENTS: Place the updated FRD15 dataset inside the below mentioned folder***********************;

LIBNAME EXIST "C:\Users\1640982\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Falcon 6.4 Monthly Data";

****COMMENTS: Place the Monthly Dataset in below folder***********************;

LIBNAME CREDIT "C:\Users\1640982\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Falcon 6.4 Monthly Data\CREDIT";


OPTIONS COMPRESS=YES;


 %LET TOD = %SYSFUNC(TODAY());
 %LET MNTH0 = %SYSFUNC(INTNX(MONTH,&TOD.,0),MONYY7.);
 %LET MNTH1 = %SYSFUNC(INTNX(MONTH,&TOD.,-1),MONYY7.);
 %LET MNTH2 = %SYSFUNC(INTNX(MONTH,&TOD.,-2),MONYY7.);
 %LET MNTH3 = %SYSFUNC(INTNX(MONTH,&TOD.,-3),MONYY7.);
 %LET MNTH_1 = %SYSFUNC(CATX(-,%SYSFUNC(SUBSTR(&MNTH1.,1,3)),%SYSFUNC(SUBSTR(&MNTH1.,6,2)) ));
 %LET MNTH_2 = %SYSFUNC(CATX(-,%SYSFUNC(SUBSTR(&MNTH2.,1,3)),%SYSFUNC(SUBSTR(&MNTH2.,6,2)) ));
 %LET MNTH_3 = %SYSFUNC(CATX(-,%SYSFUNC(SUBSTR(&MNTH3.,1,3)),%SYSFUNC(SUBSTR(&MNTH3.,6,2)) ));
 %LET MNTH11 = %SYSFUNC(CATX(,%SYSFUNC(SUBSTR(&MNTH1.,1,3)),%SYSFUNC(SUBSTR(&MNTH1.,6,2)) ));
 %LET MNTH33 = %SYSFUNC(CATX(,%SYSFUNC(SUBSTR(&MNTH3.,1,3)),%SYSFUNC(SUBSTR(&MNTH3.,6,2)) ));
 %LET MNTH00 = %SYSFUNC(CATX(,%SYSFUNC(SUBSTR(&MNTH0.,1,3)),%SYSFUNC(SUBSTR(&MNTH0.,6,2)) ));
 %PUT &MNTH1. &MNTH2. &MNTH3. &MNTH_1. &MNTH0. &MNTH_2. &MNTH_3. &MNTH11. &MNTH33. &MNTH00.;



/*CROSS CHECKING ARE ALL THE DISPUTE CASES PROPERLY TAGGED IN MONTHLY DATA*/

 
PROC IMPORT DATAFILE=
"\\INHADFIL101.IN.STANDARDCHARTERED.COM\WKGRPS7\RAC_IN_MIS\SARAVANA\MONTHLY REVIEWS\FALCON\&MNTH0.\DISPUTE_TRANSACTION_&MNTH1._GBL.XLSX"
OUT=FITXN DBMS=XLSX REPLACE;RUN;

OPTIONS MPRINT MLOGIC SYMBOLGEN;

PROC DELETE DATA = ALL_DISPUTE_CR; RUN;

%MACRO DISP(CNTY);

PROC SQL;
CREATE TABLE DISP AS SELECT * FROM
(
(SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH1. WHERE STRIP(FI_TRANSACTION_ID) IN (SELECT STRIP(FITXN) FROM FITXN)) OUTER UNION CORR
(SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH2. WHERE STRIP(FI_TRANSACTION_ID) IN (SELECT STRIP(FITXN) FROM FITXN)) OUTER UNION CORR
(SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH3. WHERE STRIP(FI_TRANSACTION_ID) IN (SELECT STRIP(FITXN) FROM FITXN)) 
);
QUIT;

PROC APPEND DATA=DISP BASE=ALL_DISPUTE_CR FORCE;

%MEND;


%DISP(AE);
%DISP(HK);
%DISP(IN);
%DISP(MY);
%DISP(SG);


PROC SORT DATA=ALL_DISPUTE_CR; BY FI_TRANSACTION_ID DESCENDING FRD_IND;  RUN;
PROC SORT DATA=ALL_DISPUTE_CR NODUPKEY; BY FI_TRANSACTION_ID;  RUN;

DATA DISP_NOT_TAGGED_AS_FRAUD_CR;
SET ALL_DISPUTE_CR;
WHERE FRD_IND EQ "";
RUN;


/*COMMENTS: CHANGE PATH*/

PROC EXPORT DATA=DISP_NOT_TAGGED_AS_FRAUD_CR OUTFILE="C:\USERS\1640982\OneDrive - Standard Chartered Bank\DESKTOP\JHILAM\Consolidated Last 3 Months Data\&MNTH00.\MAJOR_COUNTRIES_DATA\DISP_NOT_TAGGED_AS_FRAUD_CR.XLSX"
DBMS=XLSX REPLACE;RUN;

************* END OF CROSS CHECKING *******************;



/*%MACRO DISP(CNTY,MNTH);*/
/**/
/*data CREDIT.FALT002_&CNTY._CR_&MNTH.;*/
/*set CREDIT.FALT002_&CNTY._CR_&MNTH.;*/
/*IF FI_TRANSACTION_ID IN*/
/*('02606d946600887e'*/
/*'0260795c460194fc'*/
/*'0260795c4602524b'*/
/*'0260795c460255b7'*/
/*'0260795c460261a6'*/
/*'0260795c4602622e'*/
/*'0260795c460268e8'*/
/*'0260795c4603f9dc'*/
/*'02607d852101a98c'*/
/*'026089729000328f'*/
/*'02608ab02b02eff4'*/
/*'03606c13e700761d'*/
/*'036082d18b02eb39'*/
/*'1e606c12f9007df8'*/
/*'1e606d939400077a'*/
/*'1e606d939400093b'*/
/*'1e6077f80a011f3d'*/
/*'1e60795b9e062400'*/
/*'1e607eda85018857'*/
/*'1e607eda850188ba'*/
/*'1e607eda85018ad7'*/
/*'1e6082d08700151e'*/
/*'1e6082d087001520'*/
/*'1f6065c729066698'*/
/*'1f6065c7290679db'*/
/*'1f606c07fd001980'*/
/*'1f606c12f9007be6'*/
/*'1f606c12f9007c36'*/
/*'1f606d9395008bb4'*/
/*'1f606d9395008e98'*/
/*'1f6077f80a012f73'*/
/*'1f6077f80a012f80'*/
/*'206061bad9006090'*/
/*'206061d4a40001e6'*/
/*'206061d4a4000275'*/
/*'206061d4a4000772'*/
/*'206061d4a40008e2'*/
/*'20606c12f901adc6'*/
/*'20606d93950086aa'*/
/*'20606d93950086da'*/
/*'2060795b9d0245f2'*/
/*'2060795b9d024626'*/
/*'2060795b9d024787'*/
/*'2060795b9d024822'*/
/*'20607d84490112e3'*/
/*) THEN FRD_IND = "D";*/
/*RUN;*/
/**/
/*%MEND;*/
/**/
/*%DISP(VN, MAR2021);*/
/*%DISP(VN, APR2021);*/







/*RULE PERFORMANCE DATA*/




 **********Change the date as per requirement (which all dates need to append)*******************;


PROC DELETE DATA = RULE_PERFORMENCE_CR; RUN;



OPTIONS MPRINT MLOGIC SYMBOLGEN;

%MACRO DEC(CNTY);

DATA FALT003;
	SET CREDIT.FALT003_&CNTY._CR_&MNTH1.(WHERE=(STRIP(SUBSTR(CLIENT_XID,LENGTH(CLIENT_XID)-4))="&CNTY._CR" AND 
										UPCASE(SUBSTR(CREATED_DTTM,4,6)) IN ("&MNTH_1." "&MNTH_2." "&MNTH_3." ) ))
		CREDIT.FALT003_&CNTY._CR_&MNTH2.(WHERE=(STRIP(SUBSTR(CLIENT_XID,LENGTH(CLIENT_XID)-4))="&CNTY._CR" AND 
										UPCASE(SUBSTR(CREATED_DTTM,4,6)) IN ("&MNTH_1." "&MNTH_2." "&MNTH_3." ) ))
		CREDIT.FALT003_&CNTY._CR_&MNTH3.(WHERE=(STRIP(SUBSTR(CLIENT_XID,LENGTH(CLIENT_XID)-4))="&CNTY._CR" AND 
										UPCASE(SUBSTR(CREATED_DTTM,4,6)) IN ("&MNTH_1." "&MNTH_2." "&MNTH_3." ) ));
	COUNTRY = UPCASE(STRIP(SUBSTR(CLIENT_XID,LENGTH(CLIENT_XID)-4)));
RUN;

PROC SORT DATA=FALT003 OUT=RULE_&CNTY. NODUPKEY; BY FI_TRANSACTION_ID RULE_NAME_STRG ; RUN;

PROC SQL;
	CREATE TABLE FALT002 AS SELECT * FROM 

	((SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH1. WHERE 
	FI_TRANSACTION_ID IN (SELECT DISTINCT FI_TRANSACTION_ID FROM RULE_&CNTY.) AND 
	(STRIP(SUBSTR(CRD_CLNT_ID,LENGTH(CRD_CLNT_ID)-4))="&CNTY._CR" AND 
	TRN_AUTH_POST='A' AND UPCASE(SUBSTR(TRN_DT,4,6)) IN ("&MNTH_1." ) )) OUTER UNION CORR

	(SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH2. WHERE 
	FI_TRANSACTION_ID IN (SELECT DISTINCT FI_TRANSACTION_ID FROM RULE_&CNTY.) AND 
	(STRIP(SUBSTR(CRD_CLNT_ID,LENGTH(CRD_CLNT_ID)-4))="&CNTY._CR" AND 
	TRN_AUTH_POST='A' AND UPCASE(SUBSTR(TRN_DT,4,6)) IN ("&MNTH_2." ) )) OUTER UNION CORR

	(SELECT * FROM CREDIT.FALT002_&CNTY._CR_&MNTH3. WHERE 
	FI_TRANSACTION_ID IN (SELECT DISTINCT FI_TRANSACTION_ID FROM RULE_&CNTY.) AND 
	(STRIP(SUBSTR(CRD_CLNT_ID,LENGTH(CRD_CLNT_ID)-4))="&CNTY._CR" AND 
	TRN_AUTH_POST='A' AND UPCASE(SUBSTR(TRN_DT,4,6)) IN ("&MNTH_3." ) )) );
QUIT;

PROC SORT DATA=FALT002 OUT=TXN_&CNTY.; BY FI_TRANSACTION_ID DESCENDING FRD_IND;  RUN;
PROC SORT DATA=TXN_&CNTY. NODUPKEY; BY FI_TRANSACTION_ID;  RUN;

PROC SQL;
	CREATE TABLE TXN_DETAILS_&CNTY. AS SELECT * FROM RULE_&CNTY. AS A LEFT JOIN TXN_&CNTY. AS B ON 
	A.SCORE_CUSTOMER_ACCOUNT_XID=B.ACCT_NBR AND
	A.FI_TRANSACTION_ID=B.FI_TRANSACTION_ID;
QUIT;

PROC SORT DATA=EXIST.FRD15 OUT=FRD_&CNTY. NODUPKEY; 
	WHERE STRIP(SUBSTR(CLIENTIDFROMHEADER,LENGTH(CLIENTIDFROMHEADER)-4))="&CNTY._CR"; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SQL;
CREATE TABLE TXN_DETAILS_FRD_&CNTY. AS
		SELECT A.*,
		  SUBSTR(CREATED_DTTM,1,9) AS DATE,
		  UPCASE(SUBSTR(CREATED_DTTM,4,6)) AS MONTH,
		  A.TRN_AMT AS AMOUNT,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" THEN 1 
		  END AS FRAUD
FROM TXN_DETAILS_&CNTY. AS A LEFT JOIN FRD_&CNTY. AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE);
QUIT;

PROC APPEND DATA=TXN_DETAILS_FRD_&CNTY. BASE=RULE_PERFORMENCE_CR FORCE; RUN;

%MEND;

%DEC(AE);
%DEC(HK);
%DEC(IN);
%DEC(MY);
%DEC(SG);


PROC SORT DATA=RULE_PERFORMENCE_CR NODUPKEY; BY FI_TRANSACTION_ID RULE_NAME_STRG; RUN;

/*COMMENTS: CHANGE PATH*/

LIBNAME STORE "C:\Users\1640982\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\&MNTH00.\MAJOR_COUNTRIES_DATA"; 

DATA STORE.RULE_PERFORMANCE_CR_&MNTH0.;
	LENGTH MONTH $ 6. FRD_SCORE $ 10. ;
	SET RULE_PERFORMENCE_CR;
		WHERE UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST") AND 
			  UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST1") AND 
			  UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST2") AND ACCT_NBR NE "";

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;


	****SCORE BUCKET*******;

	 IF 0 LE FRD_SCOR LT 50 THEN FRD_SCORE='000-049';
     ELSE IF 50 LE FRD_SCOR LE 100 THEN FRD_SCORE='050-100';
     ELSE IF 101 LE FRD_SCOR LE 150 THEN FRD_SCORE='101-150';
     ELSE IF 151 LE FRD_SCOR LE 200 THEN FRD_SCORE='151-200';
     ELSE IF 201 LE FRD_SCOR LE 250 THEN FRD_SCORE='201-250';
     ELSE IF 251 LE FRD_SCOR LE 300 THEN FRD_SCORE='251-300';
     ELSE IF 301 LE FRD_SCOR LE 350 THEN FRD_SCORE='301-350';
     ELSE IF 351 LE FRD_SCOR LE 400 THEN FRD_SCORE='351-400';
     ELSE IF 401 LE FRD_SCOR LE 450 THEN FRD_SCORE='401-450';
     ELSE IF 451 LE FRD_SCOR LE 500 THEN FRD_SCORE='451-500';
     ELSE IF 501 LE FRD_SCOR LE 550 THEN FRD_SCORE='501-550';
     ELSE IF 551 LE FRD_SCOR LE 600 THEN FRD_SCORE='551-600';
     ELSE IF 601 LE FRD_SCOR LE 650 THEN FRD_SCORE='601-650';
     ELSE IF 651 LE FRD_SCOR LE 700 THEN FRD_SCORE='651-700';
     ELSE IF 701 LE FRD_SCOR LE 750 THEN FRD_SCORE='701-750';
     ELSE IF 751 LE FRD_SCOR LE 800 THEN FRD_SCORE='751-800';
     ELSE IF 801 LE FRD_SCOR LE 850 THEN FRD_SCORE='801-850';
     ELSE IF 851 LE FRD_SCOR LE 899 THEN FRD_SCORE='851-899';
     ELSE IF 900 LE FRD_SCOR LE 910 THEN FRD_SCORE='900-910';
	 ELSE IF 911 LE FRD_SCOR LE 920 THEN FRD_SCORE='911-920';
	 ELSE IF 921 LE FRD_SCOR LE 930 THEN FRD_SCORE='921-930';
	 ELSE IF 931 LE FRD_SCOR LE 940 THEN FRD_SCORE='931-940';
     ELSE IF 941 LE FRD_SCOR LE 950 THEN FRD_SCORE='941-950';
	 ELSE IF 951 LE FRD_SCOR LE 960 THEN FRD_SCORE='951-960';
	 ELSE IF 961 LE FRD_SCOR LE 970 THEN FRD_SCORE='961-970';
	 ELSE IF 971 LE FRD_SCOR LE 980 THEN FRD_SCORE='971-980';
     ELSE IF 981 LE FRD_SCOR LE 990 THEN FRD_SCORE='981-990';
	 ELSE IF 991 LE FRD_SCOR LE 1000 THEN FRD_SCORE='991-1000';

	MONTH = SUBSTR(TRN_DT,4,6);
RUN;




/*RULE DATA*/




%MACRO RULE(CNTY);

DATA &CNTY.;
SET CREDIT.FALT003_&CNTY._CR_&MNTH1.
	CREDIT.FALT003_&CNTY._CR_&MNTH2.
	CREDIT.FALT003_&CNTY._CR_&MNTH3.;
	WHERE UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST") AND 
			  UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST1") AND 
			  UPCASE(RULE_NAME_STRG) NOT LIKE ("%_TEST2");
RUN;

PROC SORT DATA=&CNTY. NODUPKEY; BY FI_TRANSACTION_ID RULE_NAME_STRG; RUN;

PROC APPEND DATA=&CNTY. BASE=STORE.RULE_HIT_LAST_3_MONTHS_CR FORCE; RUN;

%MEND;

%RULE(AE);
%RULE(HK);
%RULE(IN);
%RULE(MY);
%RULE(SG);




/*TXN DATA*/





PROC DELETE DATA=STORE.LAST_3_MONTHS_DATA_CR; RUN;

%MACRO TXN(CNTY);

DATA &CNTY.;
SET CREDIT.FALT002_&CNTY._CR_&MNTH1.
	CREDIT.FALT002_&CNTY._CR_&MNTH2.
	CREDIT.FALT002_&CNTY._CR_&MNTH3.;
	WHERE TRN_AUTH_POST = "A";
RUN;

PROC SORT DATA=&CNTY. ; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=&CNTY. NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC SORT DATA=EXIST.FRD15 OUT=FRD_&CNTY. NODUPKEY; 
	WHERE STRIP(SUBSTR(CLIENTIDFROMHEADER,LENGTH(CLIENTIDFROMHEADER)-4))="&CNTY._CR"; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SQL;
CREATE TABLE TXN_DETAILS_&CNTY. AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" THEN 1 
		  END AS FRAUD
FROM &CNTY. AS A LEFT JOIN FRD_&CNTY. AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE);
QUIT;

PROC APPEND DATA=TXN_DETAILS_&CNTY. BASE=STORE.LAST_3_MONTHS_DATA_CR FORCE; RUN;

%MEND;

%TXN(AE);
%TXN(HK);
%TXN(IN);
%TXN(MY);
%TXN(SG);


/*FRAUD DATA*/

DATA STORE.FRAUD_CR_&MNTH33._TO_&MNTH11.;
SET STORE.LAST_3_MONTHS_DATA_CR;
WHERE FRAUD=1;
RUN;


/*COMMENTS: CHANGE PATH*/

PROC EXPORT DATA=STORE.RULE_PERFORMANCE_CR_&MNTH0.
 OUTFILE="C:\USERS\1640982\OneDrive - Standard Chartered Bank\DESKTOP\JHILAM\Consolidated Last 3 Months Data\&MNTH00.\MAJOR_COUNTRIES_DATA\RULE_PERFORMANCE_CR_&MNTH0..XLSX"
DBMS=XLSX REPLACE;RUN;
PROC EXPORT DATA=STORE.FRAUD_CR_&MNTH33._TO_&MNTH11.
 OUTFILE="C:\USERS\1640982\OneDrive - Standard Chartered Bank\DESKTOP\JHILAM\Consolidated Last 3 Months Data\&MNTH00.\MAJOR_COUNTRIES_DATA\FRAUD_CR_&MNTH33._TO_&MNTH11..XLSX"
DBMS=XLSX REPLACE;RUN;


/*CHECKING ALL COUNTRIES DATA*/


PROC SQL;
CREATE TABLE CR_TXN AS
SELECT DISTINCT CRD_CLNT_ID,
COUNT(DISTINCT FI_TRANSACTION_ID) AS NUMBER_OF_TXNS,
SUM(FRAUD) AS NUMBER_OF_FRAUDS
FROM STORE.LAST_3_MONTHS_DATA_CR
GROUP BY CRD_CLNT_ID;
 

CREATE TABLE CR_RULE AS
SELECT DISTINCT CLIENT_XID,
COUNT(DISTINCT FI_TRANSACTION_ID) AS NUMBER_OF_HITS
FROM STORE.RULE_HIT_LAST_3_MONTHS_CR
GROUP BY CLIENT_XID;

 
CREATE TABLE CR_RULE_PERF AS
SELECT DISTINCT CLIENT_XID,
COUNT(DISTINCT FI_TRANSACTION_ID) AS NUMBER_OF_TXNS,
SUM(FRAUD) AS NUMBER_OF_FRAUDS
FROM STORE.RULE_PERFORMANCE_CR_&MNTH0.
GROUP BY CLIENT_XID;
QUIT;


