
LIBNAME DS1 "C:\Users\1640982\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\MAR22\MAJOR_COUNTRIES_DATA";

%LET TOD = %SYSFUNC(TODAY());
%LET MNTH0 = %SYSFUNC(INTNX(MONTH,&TOD.,0),MONYY7.);

DATA CR_DB_FRD_Tmp;
SET DS1.last_3_months_data_cr (DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
DS1.last_3_months_data_db (DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC);
if (SUBSTR(ACCT_NBR,1,1)="5" and SUBSTR(USR_IND_4,9,2) IN ("kG"  "kA"  "kJ"  "kC"  "kE"  "kL")) then
Challenge_Type = 2;
else if (SUBSTR(ACCT_NBR,1,1)="4" and SUBSTR(USR_IND_4,5,1) IN ("D"  "F")) then
Challenge_Type = 2;
else if (SUBSTR(USR_IND_4,1,2) = "Y2") then
Challenge_Type = 1;
else
Challenge_Type = 0;
RUN;

DATA CR_DB_FRAUD;
SET CR_DB_FRD_Tmp; 
KEEP ACCT_NBR TRN_DT TRN_TYP TRN_AUTH_POST DECI_CD DECI_CD_ORIG TRN_POS_ENT_CD TRN_POST_DT CRD_CLNT_ID 
SIC_CD MER_ID MER_NM mer_cty MER_CNTY_CD USR_IND_2 USR_IND_4 USR_DAT_2 MAST_ACCT_NBR CVV2_PRESENT 
CVV2_RESPONSE ACQUIRER_ID ACQUIRER_CNTRY TERMINAL_ID TERMINAL_TYPE TERMINAL_ENTRY_CAP ACQUIRER_MERCH_ID 
TRN_AMT FRD_SCOR AA_SCOR FI_TRANSACTION_ID TRANSACTION_ADVICE_XCD AUTHORIZATION_XID 
TRANSACTION_PIN_VERIFY_XCD CVV_VERIFY_XCD AUTH_DECISION_XCD FRD_IND Challenge_Type FRAUD; 
RUN;

DATA CR_DB_FRAUD_3DS1_3DS2;
SET CR_DB_FRAUD;
WHERE (Challenge_Type = 1 OR Challenge_Type = 2)  AND FRAUD=1;
RUN; 

PROC EXPORT DATA=CR_DB_FRAUD_3DS1_3DS2
 OUTFILE="C:\Users\1640982\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\MAR22\Major_3DS\CR_DB_FRD_3DS1_3DS2_Major_&MNTH0..XLSX"
DBMS=XLSX REPLACE;RUN;
