


				***************************************************************************

						         HR_Global_PLAYSTATION_CNP HK Credit IMPACT
								
				***************************************************************************;

/*PROC DELETE DATA=_ALL_;RUN;*/
OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";
LIBNAME CR1 "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21_Major\MAJOR_COUNTRIES_DATA";
LIBNAME EXIST "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Falcon 6.4 Monthly Data";

DATA FALT002;
     SET  
INC.falt002_cr_08dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC.falt002_cr_09dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC.falt002_cr_10dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC.falt002_cr_10dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC.falt002_cr_12dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC);

WHERE  TRN_AUTH_POST = "A" AND UPCASE(CRD_CLNT_ID) IN ("SC_CCMSHK_CR");
FORMAT TRAN_DATE DATE9.;
 TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
 ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
 AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
 MCC = INPUT(SIC_CD,BEST.);
          ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
/*         IF AUTH_DTTM GE "26FEB2021:22:15:00"DT;*/
         TIME = TIMEPART(AUTH_DTTM);

PROC SQL;
CREATE TABLE FACEBK AS
Select * from FALT002 WHERE 
MER_ID in 
(
'498750000011107'
'526567000011168'
'181918000067204'
'222180000067204'
) AND 
(
INDEX(UPCASE(MER_NM), "FACEBK") OR
INDEX(UPCASE(MER_NM), "FACEBOOK")
);
QUIT;


PROC SQL;
CREATE TABLE AIRBNB AS
Select * from FALT002 WHERE 
MER_ID in 
(
'260871000202167'
'059921000057726'
) AND 
(
INDEX(UPCASE(MER_NM), "AIRBNB")
);
QUIT;
