
PROC FORMAT;
PICTURE CUSTOM_DTTM
OTHER = '%Y-%0m-%0D-%0H.%0M.%0S' (DATATYPE=DATETIME);
RUN;

OPTIONS MPRINT MLOGIC SYMBOLGEN;

%MACRO APP(CNTY,MNTH);

%LET LBNM = %SYSFUNC(CATX(,&CNTY,%SUBSTR(&MNTH,1,3),%SUBSTR(&MNTH.,6,2)));

LIBNAME &LBNM. "\\INHADFIL101\wkgrps5\RAC_IN_MIS\Falcon 6.4 data download\&CNTY.";

DATA FALCON_64_&CNTY._&MNTH.;
	SET &LBNM..FALT002_&CNTY._CR_&MNTH.(FIRSTOBS=7000 OBS=8000);

	TRN_TIME = INPUT(COMPRESS(SUBSTR(TRN_DT, 11, 8),,"KD"), HHMMSS.);
	FORMAT TRAN_DATE YYMMDD10. TRN_TIME TIME8. TRN_DTTM CUSTOM_DTTM.;            
	TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.); 
	TRN_DTTM = DHMS(TRAN_DATE,0,0,TRN_TIME);
	PRIOR_CREDIT_LIMIT_AMT = INPUT(CR_LMT,BEST.);
	AMOUNT=INPUT(TRN_AMT,BEST.);
	AVAL=INPUT(AVAL_CR,BEST.);

	******ENCRYPTION*********;

		W1=SUBSTR(SUBSTR(ACCT_NBR,1,16),1,6);
		X1=SUBSTR(SUBSTR(ACCT_NBR,1,16),7);
		Y1=X1+3322114488;
		CLEN=LENGTH(COMPRESS(Y1));
		IF CLEN>10 THEN 
		Z1=SUBSTR(COMPRESS(Y1),CLEN-9);
		ELSE Z1=Y1;
		ENCRYPTED_ACCT_NBR = COMPRESS(W1||Z1);

	******DECRYPTION********* FOR TW, MY & ID WE ARE GETTING ENCRYPTED CARDS;

	     A1=SUBSTR(SUBSTR(ACCT_NBR,1,16),1,6);
	     B1=SUBSTR(SUBSTR(ACCT_NBR,1,16),1,5);
	     C1=SUBSTR(SUBSTR(ACCT_NBR,1,16),7);
	     D1=SUBSTR(SUBSTR(ACCT_NBR,1,16),6);
	     E1=SUBSTR(C1,1,1);
	     IF E1>2 THEN F1=0;ELSE F1=1;
	     IF F1=1 THEN G1=(COMPRESS(1||C1)-3322114488);ELSE G1=C1-3322114488;
	     DECRYPTED_ACCT_NBR=COMPRESS(A1||SUBSTR(G1,LENGTH(G1)-9));
	     IF LENGTH(DECRYPTED_ACCT_NBR)=15 THEN DECRYPTED_ACCT_NBR=STRIP(SUBSTR(DECRYPTED_ACCT_NBR,1,6))||"0"||STRIP(SUBSTR(DECRYPTED_ACCT_NBR,7));
	     ELSE IF LENGTH(DECRYPTED_ACCT_NBR)=14 THEN DECRYPTED_ACCT_NBR=STRIP(SUBSTR(DECRYPTED_ACCT_NBR,1,6))||"00"||STRIP(SUBSTR(DECRYPTED_ACCT_NBR,7));
		 ELSE IF LENGTH(DECRYPTED_ACCT_NBR)=13 THEN DECRYPTED_ACCT_NBR=STRIP(SUBSTR(DECRYPTED_ACCT_NBR,1,6))||"000"||STRIP(SUBSTR(DECRYPTED_ACCT_NBR,7));
		 ELSE IF LENGTH(DECRYPTED_ACCT_NBR)=12 THEN DECRYPTED_ACCT_NBR=STRIP(SUBSTR(DECRYPTED_ACCT_NBR,1,6))||"0000"||STRIP(SUBSTR(DECRYPTED_ACCT_NBR,7));

	**********************************;

	KEEP CRD_CLNT_ID TRN_POS_ENT_CD CUS_CARD_TYP TRN_TYP TERMINAL_TYPE TRN_AUTH_POST PRIOR_CREDIT_LIMIT_AMT
		 ACCT_NBR ENCRYPTED_ACCT_NBR DECRYPTED_ACCT_NBR TRN_TIME TRN_DTTM TRAN_DATE CRD_EXP_DT SIC_CD MER_ID MER_NM CRD_OPN_DT 
		 TERMINAL_ID  AMOUNT TRN_CURR_CD TERMINAL_ENTRY_CAP AVAL MER_ST MER_ZIP MER_CNTY_CD MER_CTY FI_TRANSACTION_ID ISS_DT DECI_CD_ORIG;
	RENAME CUS_CARD_TYP=CARD_CATEGORY_XCD ISS_DT=LAST_ISSUE_DT AMOUNT=TRN_AMT AVAL=AVAL_CR;
RUN;

PROC APPEND DATA=FALCON_64_&CNTY._&MNTH. BASE=FALCON_64_DEC FORCE; RUN;

%MEND;

*****BN******;

%APP(BN,DEC2016);