
LIBNAME CR "C:\Users\1510806\Desktop";


PROC IMPORT DATAFILE='C:\Users\1510806\Desktop\Credit.xls'
DBMS = XLS
OUT = LOOKUP_DATA_1
REPLACE;
RUN;

PROC SORT DATA=LOOKUP_DATA_1 NODUPKEY; by FI_TRANSACTION_ID;
RUN;


PROC SQL;
CREATE TABLE With_D AS 
SELECT DISTINCT
		RULE_NAME_STRG,
		CRD_CLNT_ID,
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(CASE WHEN FRAUD NE 1 THEN TRN_AMT END) AS GENUINE_TRN_AMT, 
		SUM(CASE WHEN FRAUD EQ 1 THEN TRN_AMT END) AS FRAUD_TRN_AMT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM LOOKUP_DATA_1
GROUP BY RULE_NAME_STRG, CRD_CLNT_ID;
RUN;


PROC SQL;
CREATE TABLE Without_D AS 
SELECT DISTINCT
		RULE_NAME_STRG,
		CRD_CLNT_ID,
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(CASE WHEN FRAUD NE 1 THEN TRN_AMT END) AS GENUINE_TRN_AMT, 
		SUM(CASE WHEN FRAUD EQ 1 THEN TRN_AMT END) AS FRAUD_TRN_AMT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM LOOKUP_DATA_1
WHERE TRN_POS_ENT_CD NE "D"
GROUP BY RULE_NAME_STRG, CRD_CLNT_ID;
RUN;