
OPTIONS COMPRESS=YES;

LIBNAME INC_CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";
LIBNAME INC_DB "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\DB";
LIBNAME EXIST "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Falcon 6.4 Monthly Data";
/*LIBNAME STORE "C:\Jhilam\Store";*/

PROC SORT DATA=EXIST.FRD15 OUT=FRD15 NODUPKEY; 
BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

DATA DEC2021;
SET 
INC_CR.falt002_cr_01dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_02dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_03dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_04dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_05dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_06dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_07dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_08dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_09dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_10dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_11dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_12dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_13dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_14dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_15dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_16dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_17dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_18dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_19dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_20dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_21dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_22dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_23dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_24dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_25dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_26dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_27dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_28dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_29dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_CR.falt002_cr_30dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_01dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_02dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_03dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_04dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_05dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_06dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_07dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_08dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_09dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_10dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_11dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_12dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_13dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_14dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_15dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_16dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_17dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_18dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_19dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_20dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_21dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_22dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_23dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_24dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_25dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_26dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_27dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_28dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_29dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC_DB.falt002_db_30dec(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC);
WHERE 
CRD_CLNT_ID in ("SC_SPARROWBD_DB" "SC_C400BD_CR" "SC_TANDEMTW_DB" "SC_CCMSTW_CR""SC_EURONETID_DB" "SC_EURONETBH_DB"
"SC_SPARROWBW_DB" "SC_SPARROWGH_DB" "SC_SPARROWJO_DB" "SC_SPARROWKE_DB" "SC_SPARROWLK_DB" "SC_SPARROWNG_DB"
"SC_SPARROWNP_DB" "SC_EURONETVN_DB" "SC_SPARROWZM_DB" "SC_EURONETBN_DB"  "SC_SPARROWBW_DB" "SC_SPARROWGM_DB"
"SC_EURONETQA_DB" "SC_SPARROWTZ_DB" "SC_SPARROWUG_DB" "SC_SPARROWZW_DB" "SC_SPARROWCI_DB" "SC_SPARROWCM_DB"
"SC_SPARROWSL_DB");
RUN;

PROC SORT DATA=DEC2021 OUT = DEC2021_1 ; BY FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=DEC2021_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

proc sql;
create table DEC2021_2
as select a.*,
             b.fraudflag,
             case 
                when strip(upcase(a.frd_ind)) in ("Y" "D") or b.fraudflag="1" then 1 
             end as FRAUD
from DEC2021_1 as a left join frd15 as b on 
a.acct_nbr = b.pan and
a.fi_transaction_id=b.fiTransactionIdReference;
quit;

PROC APPEND DATA=DEC2021_2 BASE=ALL_CPP_DATA_CR FORCE; RUN;

PROC SORT DATA=ALL_CPP_DATA_CR; BY CRD_CLNT_ID; RUN;

DATA FRAUDZ;
SET ALL_CPP_DATA_CR;
WHERE FRAUD = 1;
RUN;

PROC FREQ DATA = FRAUDZ;TITLE "Frequencies";
TABLE CRD_CLNT_ID/NOCOL NOROW NOPERCENT NOCUM; RUN; 
