
LIBNAME Data "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Jul21";

Data kk;
set 
Data.fraud_cr_apr21_to_jun21 (DROP = EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR  INCOME_AMT PAYMENT_DELINQUENT_CYC
)
Data.fraud_cr_apr21_to_jun211(DROP = EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR  INCOME_AMT PAYMENT_DELINQUENT_CYC
)	
Data.fraud_db_apr21_to_jun21(DROP = EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR  INCOME_AMT PAYMENT_DELINQUENT_CYC
)
Data.fraud_db_apr21_to_jun211(DROP  = EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR  INCOME_AMT PAYMENT_DELINQUENT_CYC
);
where
(
(SUBSTR(ACCT_NBR,1,1)="5" and SUBSTR(USR_DAT_1,9,2) IN ("kG"  "kA"  "kJ"  "kC"  "kE"  "kL"))
or
(SUBSTR(ACCT_NBR,1,1)="4" and SUBSTR(USR_IND_4,5,1) IN ("D" "F"))
);
run;