

**************************************************************************************

				HR_Country_CRYPTO_Merchants11

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";



DATA FALT003_1;
     SET INC.falt003_DB_23MAY;
WHERE DATE1 GE "23MAY2021"D AND UPCASE(RULE_NAME_STRG) = 'HR_COUNTRY_CRYPTO_MERCHANTS11' AND 
CLIENT_XID IN ("SC_EURONETIN_DB" "SC_EURONETVN_DB" "SC_SPARROWJO_DB");
IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) NOT IN ("HK" "TW" "BD") THEN TENANT = "Global"; 
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("HK") THEN TENANT = "HK";
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("TW") THEN TENANT = "TW";
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("BD") THEN TENANT = "BD";
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
     SET INC.falt002_DB_23MAY;
WHERE 
DATE1 GE "23MAY2021"D AND 
TRN_AUTH_POST = "A" AND
(AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG = "A") AND 
SIC_CD = "6051"	AND
CRD_CLNT_ID IN ("SC_EURONETIN_DB" "SC_EURONETVN_DB" "SC_SPARROWJO_DB") AND 
(
	INDEX(UPCASE(MER_NM),"MCO" ) OR 
 	INDEX(UPCASE(MER_NM),"MOONPAY" ) OR
	INDEX(UPCASE(MER_NM),"IEXPAY.NET" ) OR
	INDEX(UPCASE(MER_NM),"SWITCHERE.COM" ) OR
	INDEX(UPCASE(MER_NM),"BUY DIGITAL ASSET" ) OR
	INDEX(UPCASE(MER_NM),"WISENEX.COM" ) OR
	INDEX(UPCASE(MER_NM),"CONGEE.IO" ) OR
	INDEX(UPCASE(MER_NM),"MERCURYO" ) OR
	INDEX(UPCASE(MER_NM),"SIMPLEX" ) OR
	INDEX(UPCASE(MER_NM),"PAYBIS" ) OR
	INDEX(UPCASE(MER_NM),"N.EXCHANGE" ) OR
	INDEX(UPCASE(MER_NM),"WYRE" ) OR
	INDEX(UPCASE(MER_NM),"QUICKBIT.COM" )OR
	INDEX(UPCASE(MER_NM),"CRO" )OR
	INDEX(UPCASE(MER_NM),"CRYPTO.COM" )OR
	INDEX(UPCASE(MER_NM),"UNIMAL LTD" )OR
	INDEX(UPCASE(MER_NM),"MOON PAY")
);
IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) NOT IN ("HK" "TW" "BD") THEN TENANT = "Global"; 
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("HK") THEN TENANT = "HK";
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("TW") THEN TENANT = "TW";
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("BD") THEN TENANT = "BD";
RUN;


PROC SORT DATA=FALT002_1 OUT=HR_Country_CRYPTO_Merchants11 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_Country_CRYPTO_Merchants11;
TABLES TENANT*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES TENANT*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;


