
			*******************************************************************
					       HR_Country_3DS2_MC_RBA BD Credit

			*******************************************************************;

LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";

DATA  FALT002;
SET 
INC.falt002_cr_03nov
INC.falt002_cr_04nov;   

WHERE  
/*CRD_CLNT_ID NOT IN ("SC_CCMSIN_CR" "SC_CCMSMY_CR" "SC_CCMSSG_CR" */
/*"SC_C400AE_CR" "SC_CCMSHK_CR" "SC_PMTHK_CR" "SC_CCMSTW_CR" "SC_C400BD_CR") and */
CRD_CLNT_ID IN ("SC_C400BD_CR") and 
TRN_AUTH_POST = "A";
FORMAT TRAN_DATE DATE9.;
 TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
 ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
 AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
 MCC = INPUT(SIC_CD,BEST.);

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;


DATA SAS_DATA;
SET FALT002;
IF
(
 CRD_CLNT_ID IN ("SC_C400BD_CR") AND
 TRN_AUTH_POST  = "A" AND
(AUTH_DECISION_XCD  = "A" OR  DECI_CD_ORIG  = "A") AND
 TRN_TYP  IN ("C" "M" "P") AND
SUBSTR(ACCT_NBR,1,1)="5" AND
SUBSTR(USR_DAT_1,9,2) IN ("KJ" "KC" "KE" "KL" "KF" "KM")
)
THEN HR_Country_3DS2_MC_RBA = "Y";
RUN;

DATA TXN_DATA;
SET SAS_DATA;
WHERE HR_Country_3DS2_MC_RBA = "Y" and date1 GE "04NOV2021"D;
RUN;


DATA RULE_DATA;
SET 
INC.falt003_cr_03nov
INC.falt003_cr_04nov;
       WHERE UPCASE(RULE_NAME_STRG) IN ('HR_COUNTRY_3DS2_MC_RBA') and CLIENT_XID NOT IN ("SC_C400BD_CR") and
date1 GE "04NOV2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "HR_Country_3DS2_MC_RBA SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA=RULE_DATA; TITLE "HR_Country_3DS2_MC_RBA FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Country_3DS2_MC_RBA BD Credit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
 PROC FREQ DATA = TXN_DATA;TITLE "HR_Country_3DS2_MC_RBA SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Country_3DS2_MC_RBA FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Country_3DS2_MC_RBA BD Credit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Country_3DS2_MC_RBA BD Credit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;
