

				**************************************************************************************

								HR_CNP_Country_Non_Major Global Credit

				**************************************************************************************;

LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21_Non_Major";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";
LIBNAME CR1 "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21_Major\MAJOR_COUNTRIES_DATA";

DATA FALT002_1;
SET 
INC.falt002_cr_11NOV
INC.falt002_cr_12NOV;

     WHERE TRN_AUTH_POST = "A"  AND DATE1 GE "01SEP2021"D AND
 CRD_CLNT_ID IN ("SC_CCMSID_CR" "SC_C400VN_CR" "SC_C400GH_CR" "SC_C400KE_CR" "SC_C400BH_CR");
     FORMAT TRAN_DATE DATE9. TIME TIME8.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
         ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
/*         IF AUTH_DTTM GE "26FEB2021:22:15:00"DT;*/
         TIME = TIMEPART(AUTH_DTTM);

  	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;


    IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN SRVC_UDV_FX = 1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN SRVC_UDV_FX = 3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN SRVC_UDV_FX = 43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN SRVC_UDV_FX = 32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN SRVC_UDV_FX = 11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN SRVC_UDV_FX = 63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN SRVC_UDV_FX = 30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN SRVC_UDV_FX = 3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN SRVC_UDV_FX = 0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN SRVC_UDV_FX = 10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN SRVC_UDV_FX = 4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN SRVC_UDV_FX = 0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN SRVC_UDV_FX = 0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN SRVC_UDV_FX = 103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN SRVC_UDV_FX = 153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN SRVC_UDV_FX = 365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN SRVC_UDV_FX = 102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN SRVC_UDV_FX = 22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN SRVC_UDV_FX = 8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN SRVC_UDV_FX = 7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN SRVC_UDV_FX = 7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN SRVC_UDV_FX = 83.60;

/**/
/*    IF CRD_CLNT_ID IN ("SC_CCMSSG_CR") THEN SRVC_UDV_ISSUER_COUNTRY_CODE = "702";*/
/*	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN SRVC_UDV_ISSUER_COUNTRY_CODE = "458";*/
/*	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN SRVC_UDV_ISSUER_COUNTRY_CODE = "356";*/
/*	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN SRVC_UDV_ISSUER_COUNTRY_CODE = "784";*/


RUN;


DATA FALT002_1;
SET FALT002_1;
WHERE
(
 DATE1 GE "12NOV2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 TRN_TYP  IN ("C" "M" "P") AND
TRN_POS_ENT_CD  IN ("E" "K" "G") AND
(
( CRD_CLNT_ID  = "SC_CCMSID_CR" AND
(
(COMPRESS(MER_ID) = "15877016600") OR
(COMPRESS(MER_ID) = "000980200149998 " AND  FRD_SCOR  >= 500 )
)
)OR
(
 CRD_CLNT_ID  = "SC_C400VN_CR" AND
(
(COMPRESS(MER_ID) = "000004165502990" AND  USD  >= 250) OR
(COMPRESS(MER_ID) = "GN58481KL4JK93G" AND  USD  > 10)
)
) OR
(
 CRD_CLNT_ID  = "SC_C400GH_CR" AND
COMPRESS(MER_ID) = "395700048525" AND
 USD  >= 200
) OR
(
 CRD_CLNT_ID  = "SC_C400KE_CR" AND
COMPRESS(MER_ID) = "479631000200812" AND
 USD  >= 200
) OR
(  CRD_CLNT_ID  = "SC_C400BH_CR" AND COMPRESS(MER_ID) = "000000030000068" )
)
);
RUN;


PROC SORT DATA=FALT002_1 OUT=TXN_DATA NODUPKEY; BY FI_TRANSACTION_ID; RUN;


DATA FALT003_1;
SET  
INC.falt003_cr_12NOV;
WHERE DATE1 GE "12NOV2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_CNP_COUNTRY_NON_MAJOR';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY OUT = RULE_DATA ; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = TXN_DATA;TITLE "HR_CNP_Country_Non_Major  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA = RULE_DATA; TITLE "HR_CNP_Country_Non_Major  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

/* Writing Outout to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_CNP_Country_Non_Major Global Credit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
PROC FREQ DATA = TXN_DATA;TITLE "HR_CNP_Country_Non_Major  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_CNP_Country_Non_Major  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_CNP_Country_Non_Major Global Credit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_CNP_Country_Non_Major Global Credit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;



