

**************************************************************************************

				HR_Global_CRYPTO_Merchants6 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS6';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"FLOWBTC") OR
INDEX(UPCASE(MER_NM),"TRADESATOSHI") OR
INDEX(UPCASE(MER_NM),"CRYPTONIT") OR
INDEX(UPCASE(MER_NM),"GO4CRYPTOS") OR
INDEX(UPCASE(MER_NM),"NOVAEXCHANGE") OR
INDEX(UPCASE(MER_NM),"INDACOIN") OR
INDEX(UPCASE(MER_NM),"COINCOZ") OR
INDEX(UPCASE(MER_NM),"COINSWITCH") OR
INDEX(UPCASE(MER_NM),"BITTYLICIOUS") OR
INDEX(UPCASE(MER_NM),"BITCOINTRADE") OR
INDEX(UPCASE(MER_NM),"STOCKSEXCHANGE") OR
INDEX(UPCASE(MER_NM),"KUNA") OR
INDEX(UPCASE(MER_NM),"VBTC") OR
INDEX(UPCASE(MER_NM),"EZBTC") OR
INDEX(UPCASE(MER_NM),"BITPORT") OR
INDEX(UPCASE(MER_NM),"NXT MULTIGATEWAY") OR
INDEX(UPCASE(MER_NM),"BITOK") OR
INDEX(UPCASE(MER_NM),"CCEDK") OR
INDEX(UPCASE(MER_NM),"BANXIO") OR
INDEX(UPCASE(MER_NM),"CRYPTSY") OR
INDEX(UPCASE(MER_NM),"COMKORT") OR
INDEX(UPCASE(MER_NM),"CHANGETIP") OR
INDEX(UPCASE(MER_NM),"CLOUDHASHING") OR
INDEX(UPCASE(MER_NM),"COINCO") OR
INDEX(UPCASE(MER_NM),"COINBASE") OR
INDEX(UPCASE(MER_NM),"COINDESK") OR
INDEX(UPCASE(MER_NM),"COINIFY") OR
INDEX(UPCASE(MER_NM),"COINSPH") OR
INDEX(UPCASE(MER_NM),"SPECTROCOIN") OR
INDEX(UPCASE(MER_NM),"BUYSOMEBITCOINS") OR
INDEX(UPCASE(MER_NM),"BEBITCOINS.COM") OR
INDEX(UPCASE(MER_NM),"BTCEWEX") OR
INDEX(UPCASE(MER_NM),"CRYPTOTRADE") OR
INDEX(UPCASE(MER_NM),"BUYCOINNOW") OR
INDEX(UPCASE(MER_NM),"BTCBIT") OR
INDEX(UPCASE(MER_NM),"123BITCOIN.DK") OR
INDEX(UPCASE(MER_NM),"BELFRICS") OR
INDEX(UPCASE(MER_NM),"BIBOX") OR
INDEX(UPCASE(MER_NM),"BIGONE") OR
INDEX(UPCASE(MER_NM),"BITCOIN EXCHANGE") OR
INDEX(UPCASE(MER_NM),"BITCOIN NW") OR
INDEX(UPCASE(MER_NM),"BITCOIN.DE") OR
INDEX(UPCASE(MER_NM),"BITCOIN-OTC") OR
INDEX(UPCASE(MER_NM),"BITCOINS4CARDS.COM") OR
INDEX(UPCASE(MER_NM),"BITIBU") OR
INDEX(UPCASE(MER_NM),"BITLISH.COM") OR
INDEX(UPCASE(MER_NM),"BITNOVO.COM") OR
INDEX(UPCASE(MER_NM),"BITOEX") OR
INDEX(UPCASE(MER_NM),"BITPANDA.COM")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS6 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS6;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;