

**************************************************************************************

				HR_Global_CRYPTO_Merchants4 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS4';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"COINBROKER") OR
INDEX(UPCASE(MER_NM),"BITSPARK") OR
INDEX(UPCASE(MER_NM),"MASTERXCHANGE") OR
INDEX(UPCASE(MER_NM),"COIN-SWAP") OR
INDEX(UPCASE(MER_NM),"ALLCRYPT") OR
INDEX(UPCASE(MER_NM),"CRYPTOINE") OR
INDEX(UPCASE(MER_NM),"SWISSCEX") OR
INDEX(UPCASE(MER_NM),"DGEX") OR
INDEX(UPCASE(MER_NM),"MCXNOW") OR
INDEX(UPCASE(MER_NM),"CRYPTO-TRADE") OR
INDEX(UPCASE(MER_NM),"ICB") OR
INDEX(UPCASE(MER_NM),"COINNEXT") OR
INDEX(UPCASE(MER_NM),"JUSTCOIN") OR
INDEX(UPCASE(MER_NM),"MINTPAL") OR
INDEX(UPCASE(MER_NM),"LITETREE") OR
INDEX(UPCASE(MER_NM),"PRELUDE") OR
INDEX(UPCASE(MER_NM),"COINS-E") OR
INDEX(UPCASE(MER_NM),"COINMARKET") OR
INDEX(UPCASE(MER_NM),"NXTCHG") OR
INDEX(UPCASE(MER_NM),"UPBIT") OR
INDEX(UPCASE(MER_NM),"COINEX") OR
INDEX(UPCASE(MER_NM),"EMEBTC") OR
INDEX(UPCASE(MER_NM),"COINS.PH") OR
INDEX(UPCASE(MER_NM),"HUOBI") OR
INDEX(UPCASE(MER_NM),"UPHOLD") OR
INDEX(UPCASE(MER_NM),"WAVES PLATFORM") OR
INDEX(UPCASE(MER_NM),"AUSTIN GLOBAL EXCHANGE") OR
INDEX(UPCASE(MER_NM),"COINMKT") OR
INDEX(UPCASE(MER_NM),"PALTH") OR
INDEX(UPCASE(MER_NM),"CRYPTOAVE") OR
INDEX(UPCASE(MER_NM),"CRYPTO RUSH") OR
INDEX(UPCASE(MER_NM),"ALTSWAP") OR
INDEX(UPCASE(MER_NM),"37COINS") OR
INDEX(UPCASE(MER_NM),"AIRBITZ") OR
INDEX(UPCASE(MER_NM),"BIPS") OR
INDEX(UPCASE(MER_NM),"BITCOINCOM") OR
INDEX(UPCASE(MER_NM),"BITCOINSUISSE") OR
INDEX(UPCASE(MER_NM),"BITGO") OR
INDEX(UPCASE(MER_NM),"BITINSTANT") OR
INDEX(UPCASE(MER_NM),"BITPAY") OR
INDEX(UPCASE(MER_NM),"BITRESERVE") OR
INDEX(UPCASE(MER_NM),"BITWAGE") OR
INDEX(UPCASE(MER_NM),"BITWALA") OR
INDEX(UPCASE(MER_NM),"BITX") OR
INDEX(UPCASE(MER_NM),"BLOCKCHAININFO") OR
INDEX(UPCASE(MER_NM),"BLOCKSTREAM") OR
INDEX(UPCASE(MER_NM),"BTCE") OR
INDEX(UPCASE(MER_NM),"BTCJAM") OR
INDEX(UPCASE(MER_NM),"BTCS") OR
INDEX(UPCASE(MER_NM),"BTCSX") OR
INDEX(UPCASE(MER_NM),"BUTTERCOIN")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS4 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS4;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;