

**************************************************************************************

				HR_Global_CRYPTO_Merchants2 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS2';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"VIRCUREX") OR
INDEX(UPCASE(MER_NM),"BTCTRADE") OR
INDEX(UPCASE(MER_NM),"BIT2C THE BITCOIN EXCHANGE OF ISRAEL") OR
INDEX(UPCASE(MER_NM),"BITMARKET") OR
INDEX(UPCASE(MER_NM),"BRAZILIEX") OR
INDEX(UPCASE(MER_NM),"COINNEST") OR
INDEX(UPCASE(MER_NM),"BITCOIN EXCHANGE THAILAND") OR
INDEX(UPCASE(MER_NM),"BISQ") OR
INDEX(UPCASE(MER_NM),"BITOASIS") OR
INDEX(UPCASE(MER_NM),"BITMEX") OR
INDEX(UPCASE(MER_NM),"ORDERBOOK") OR
INDEX(UPCASE(MER_NM),"COINCHECK") OR
INDEX(UPCASE(MER_NM),"GDAX") OR
INDEX(UPCASE(MER_NM),"QUOINEX") OR
INDEX(UPCASE(MER_NM),"BTCMARKETS") OR
INDEX(UPCASE(MER_NM),"WEX") OR
INDEX(UPCASE(MER_NM),"CEXIO") OR
INDEX(UPCASE(MER_NM),"BITBAY") OR
INDEX(UPCASE(MER_NM),"DERIBIT") OR
INDEX(UPCASE(MER_NM),"OKCOIN-INTL") OR
INDEX(UPCASE(MER_NM),"ZAIF") OR
INDEX(UPCASE(MER_NM),"BXINTH") OR
INDEX(UPCASE(MER_NM),"ZEBPAY") OR
INDEX(UPCASE(MER_NM),"LUNO") OR
INDEX(UPCASE(MER_NM),"BITCOINCOID") OR
INDEX(UPCASE(MER_NM),"COINEXCHANGE") OR
INDEX(UPCASE(MER_NM),"MERCADOBITCOIN") OR
INDEX(UPCASE(MER_NM),"BTC38") OR
INDEX(UPCASE(MER_NM),"GATEIO") OR
INDEX(UPCASE(MER_NM),"FOXBIT") OR
INDEX(UPCASE(MER_NM),"BTCTURK") OR
INDEX(UPCASE(MER_NM),"XBTCE") OR
INDEX(UPCASE(MER_NM),"BITINKA") OR
INDEX(UPCASE(MER_NM),"BL3P") OR
INDEX(UPCASE(MER_NM),"COINSQUARE") OR
INDEX(UPCASE(MER_NM),"DSX") OR
INDEX(UPCASE(MER_NM),"BITONIC") OR
INDEX(UPCASE(MER_NM),"BITBANK") OR
INDEX(UPCASE(MER_NM),"MERCATOX") OR
INDEX(UPCASE(MER_NM),"INDEPENDENTRESERVE") OR
INDEX(UPCASE(MER_NM),"SHAPESHIFT") OR
INDEX(UPCASE(MER_NM),"MIXCOINS") OR
INDEX(UPCASE(MER_NM),"THEROCKTRADING") OR
INDEX(UPCASE(MER_NM),"LYKKE") OR
INDEX(UPCASE(MER_NM),"NEGOCIECOINS") OR
INDEX(UPCASE(MER_NM),"ANXPRO") OR
INDEX(UPCASE(MER_NM),"BITCOINTOYOU") OR
INDEX(UPCASE(MER_NM),"COINGATHER") OR
INDEX(UPCASE(MER_NM),"BITEXLA") OR
INDEX(UPCASE(MER_NM),"CRYPTODAO") OR
INDEX(UPCASE(MER_NM),"SURBTC") OR
INDEX(UPCASE(MER_NM),"BIT2C")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS2;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;