

**************************************************************************************

				HR_Global_CRYPTO_Merchants8 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS8';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"EINEX PURCHASE") OR
INDEX(UPCASE(MER_NM),"EINSTEIN EXCHANGE") OR
INDEX(UPCASE(MER_NM),"ETHFINEX") OR
INDEX(UPCASE(MER_NM),"EXTSTOCK") OR
INDEX(UPCASE(MER_NM),"EYALABS") OR
INDEX(UPCASE(MER_NM),"FISCO") OR
INDEX(UPCASE(MER_NM),"FORKDELTA") OR
INDEX(UPCASE(MER_NM),"FYB-SG") OR
INDEX(UPCASE(MER_NM),"GETBTC") OR
INDEX(UPCASE(MER_NM),"GMOCOIN") OR
INDEX(UPCASE(MER_NM),"GMOCOIN / COIN.Z") OR
INDEX(UPCASE(MER_NM),"GOPAX") OR
INDEX(UPCASE(MER_NM),"INDACOIN.COM") OR
INDEX(UPCASE(MER_NM),"INDEPENDENT RESERVE") OR
INDEX(UPCASE(MER_NM),"INDODAX") OR
INDEX(UPCASE(MER_NM),"INFINITYCOIN") OR
INDEX(UPCASE(MER_NM),"INSTANT BITCOIN") OR
INDEX(UPCASE(MER_NM),"INSTANT BITCOIN 9250109") OR
INDEX(UPCASE(MER_NM),"KOINEX") OR
INDEX(UPCASE(MER_NM),"KRYPTOS-X") OR
INDEX(UPCASE(MER_NM),"KYBER NETWORK") OR
INDEX(UPCASE(MER_NM),"LATOKEN") OR
INDEX(UPCASE(MER_NM),"LBANK") OR
INDEX(UPCASE(MER_NM),"LIANKE") OR
INDEX(UPCASE(MER_NM),"MAICOIN") OR
INDEX(UPCASE(MER_NM),"MONETIZZE*BITCOINTRADE") OR
INDEX(UPCASE(MER_NM),"NERAEX") OR
INDEX(UPCASE(MER_NM),"NORDIC BITCOIN") OR
INDEX(UPCASE(MER_NM),"NUMONEY") OR
INDEX(UPCASE(MER_NM),"ONECOIN") OR
INDEX(UPCASE(MER_NM),"ONECOIN / LIANKE / WANKEBI") OR
INDEX(UPCASE(MER_NM),"ORDERCRYPTO.COM") OR
INDEX(UPCASE(MER_NM),"PAKCOIN.IO") OR
INDEX(UPCASE(MER_NM),"PSP*COINSBANK.COM") OR
INDEX(UPCASE(MER_NM),"RIPPLE4Y") OR
INDEX(UPCASE(MER_NM),"ROBINHOOD") OR
INDEX(UPCASE(MER_NM),"SBI GROUP") OR
INDEX(UPCASE(MER_NM),"SHOPFORBTC.COM") OR
INDEX(UPCASE(MER_NM),"SIMPLEX*CUBITS") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_BITSTAMP") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_BITTYLICIOUS") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_BTCC") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_CUBITS") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_PAYBIS") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_XAPO") OR
INDEX(UPCASE(MER_NM),"SIMPLEX_XCOINS") OR
INDEX(UPCASE(MER_NM),"SIMPLEX-PAYBIS")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS8 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS8;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;