
					****************************************************
					    HR_Global_Magstripe_Nonmajor_Test Global Debit
					****************************************************;


OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Oct21_Major\MAJOR_COUNTRIES_DATA";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\DB";

DATA FALT002;
SET
INC.falt002_db_30OCT
INC.falt002_db_31OCT;

where
TRN_AUTH_POST  = "A";
FORMAT TRAN_DATE DATE9.;
TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));
MCC = INPUT(SIC_CD,BEST.);


IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
			ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/3.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;


RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;

/**/
/*%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);*/
/**/
/*DATA FALT002_2;*/
/*     SET FALT002_2;*/
/*     BY ACCT_NBR AUTH_DTTM;*/
/**/
/*     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;*/
/**/
/*     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;*/
/**/
/*     IF FIRST.ACCT_NBR THEN DO;*/
/*           TIME_RESET_&VAR_NAME. = 0;*/
/*           CUM_COUNT_&VAR_NAME. = 0;*/
/*           CUM_AMOUNT_&VAR_NAME. = 0;*/
/*     END;*/
/**/
/*     IF &CUMULATIVE_CONDITION. THEN DO;*/
/*           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;*/
/*                CUM_COUNT_&VAR_NAME. + 1;*/
/*                CUM_AMOUNT_&VAR_NAME. + USD;*/
/*           END;*/
/*           ELSE DO;*/
/*                TIME_RESET_&VAR_NAME. = AUTH_DTTM;*/
/*                CUM_COUNT_&VAR_NAME. = 1;*/
/*                CUM_AMOUNT_&VAR_NAME. = USD;*/
/*           END;*/
/*     END;*/
/**/
/**/
/*RUN;*/
/*%MEND; */
/**/
/*%UDV(CUM_INTERVAL        = 86400,                                          */
/*     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND */
/*								TRN_TYP IN ("C" "M" "P") AND */
/*	 						TRN_POS_ENT_CD IN ("E" "K" "G" "") AND*/
/*							TRN_AMT > 0),*/
/*     VAR_NAME            = CNP_DAILY);*/


PROC SQL;
CREATE TABLE FALT002_2 AS
SELECT * FROM FALT002_2
WHERE 
(
(
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 TRN_TYP  IN ("C" "M" "P") AND
TRN_POS_ENT_CD  IN ("U" "S" "F" "T") AND
 TRN_AMT  > 0
)
and
(

( CRD_CLNT_ID  = "SC_EURONETBH_DB" AND
 MER_CNTY_CD  NE "048" AND  FRD_SCOR  > 950
)

OR( CRD_CLNT_ID  = "SC_SPARROWBW_DB" AND
 MER_CNTY_CD  NE "072"
)

OR( CRD_CLNT_ID  = "SC_SPARROWGH_DB" AND
 MER_CNTY_CD  NE "288" AND  FRD_SCOR  > 700
)

OR( CRD_CLNT_ID  = "SC_SPARROWJO_DB" AND
 MER_CNTY_CD  NE "400"
)

OR( CRD_CLNT_ID  = "SC_SPARROWKE_DB" AND
 MER_CNTY_CD  NE "404" AND  FRD_SCOR  > 550
)

OR( CRD_CLNT_ID  = "SC_SPARROWLK_DB" AND
 MER_CNTY_CD  NE "144" AND  FRD_SCOR  > 50
)

OR( CRD_CLNT_ID  = "SC_SPARROWNG_DB" AND
 MER_CNTY_CD  NE "566" AND  FRD_SCOR  > 50
)

OR( CRD_CLNT_ID  = "SC_SPARROWNP_DB" AND
 MER_CNTY_CD  NE "524" AND  FRD_SCOR  > 100
)

OR( CRD_CLNT_ID  = "SC_EURONETVN_DB" AND
 MER_CNTY_CD  NE "704" AND  FRD_SCOR  > 250
)

OR( CRD_CLNT_ID  = "SC_SPARROWZM_DB" AND
 MER_CNTY_CD  NE "894" AND  FRD_SCOR  > 100
)

OR( CRD_CLNT_ID  = "SC_EURONETBN_DB" AND
 MER_CNTY_CD  NE "096" AND  FRD_SCOR  > 50
)

OR( CRD_CLNT_ID  = "SC_EURONETQA_DB" AND
 MER_CNTY_CD  NE "634"
)

OR( CRD_CLNT_ID  = "SC_SPARROWCM_DB" AND
 MER_CNTY_CD  NE "120"
)

OR( CRD_CLNT_ID  = "SC_SPARROWCI_DB" AND
 MER_CNTY_CD  NE "384" AND  FRD_SCOR  > 200
)

OR( CRD_CLNT_ID  = "SC_SPARROWGM_DB" AND
 MER_CNTY_CD  NE "270" AND  FRD_SCOR  > 150
)

OR( CRD_CLNT_ID  = "SC_SPARROWSL_DB" AND
 MER_CNTY_CD  NE "694" AND  FRD_SCOR  > 50
)

OR( CRD_CLNT_ID  = "SC_SPARROWTZ_DB" AND
 MER_CNTY_CD  NE "834" AND  FRD_SCOR  > 50
)

OR( CRD_CLNT_ID  = "SC_SPARROWUG_DB" AND
 MER_CNTY_CD  NE "800" AND  FRD_SCOR  > 400
)

OR( CRD_CLNT_ID  = "SC_SPARROWZW_DB" AND
 MER_CNTY_CD  NE "716" AND  FRD_SCOR  > 50
)
)
);
QUIT;

PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2 OUT=FALT003; BY ACCT_NBR AUTH_DTTM; RUN;


DATA TXN_DATA;
SET FALT003;
WHERE DATE1 GE "30OCT2021"D;
RUN;

DATA RULE_DATA;
SET
INC.FALT003_DB_30OCT
INC.FALT003_DB_31OCT;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_MAGSTRIPE_NONMAJOR_TEST') AND
/*CLIENT_XID IN ("SC_HOGANHK_DB") AND*/
DATE1 GE "30OCT2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "TXN_DATA SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA=RULE_DATA; TITLE "RULE_DATA FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;



/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Magstripe_Nonmajor_Test Global Debit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
 PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Magstripe_Nonmajor_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Magstripe_Nonmajor_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Magstripe_Nonmajor_Test Global Debit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Magstripe_Nonmajor_Test Global Debit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;