
						**********************************************************
								  HR_Global_Int_CNP_60MIN SG Debit
										
						**********************************************************;
 
/*PROC DELETE DATA=_ALL_;RUN;*/
OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21_Major\MAJOR_COUNTRIES_DATA";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\DB";

DATA FALT002;
SET
INC.falt002_db_15NOV(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC)
INC.falt002_db_16NOV(DROP =  EXTERNAL_1_SCR EXTERNAL_2_SCR EXTERNAL_3_SCR INCOME_AMT PAYMENT_DELINQUENT_CYC);


     WHERE TRN_AUTH_POST = "A"  AND DATE1 GE "01NOV2021"D AND
/* CRD_CLNT_ID IN ("SC_HOGANHK_DB");*/
	  CRD_CLNT_ID IN ("SC_EURONETSG_DB" "SC_EURONETMY_DB" "SC_EURONETIN_DB" "SC_EURONETAE_DB");
     FORMAT TRAN_DATE DATE9. TIME TIME8.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
         ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
/*         IF AUTH_DTTM GE "26FEB2021:22:15:00"DT;*/
         TIME = TIMEPART(AUTH_DTTM);

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/3.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;


		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN SRVC_UDV_FX =3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN SRVC_UDV_FX = 3.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN SRVC_UDV_FX = 13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN SRVC_UDV_FX = 65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN SRVC_UDV_FX = 30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN SRVC_UDV_FX = 0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN SRVC_UDV_FX = 10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN SRVC_UDV_FX = 4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN SRVC_UDV_FX = 0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN SRVC_UDV_FX = 103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN SRVC_UDV_FX = 153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN SRVC_UDV_FX = 365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN SRVC_UDV_FX = 102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN SRVC_UDV_FX = 22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN SRVC_UDV_FX = 8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN SRVC_UDV_FX = 1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN SRVC_UDV_FX = 10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN SRVC_UDV_FX = 45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN SRVC_UDV_FX = 65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN SRVC_UDV_FX = 3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN SRVC_UDV_FX = 2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN SRVC_UDV_FX = 3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN SRVC_UDV_FX = 361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN SRVC_UDV_FX = 7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN SRVC_UDV_FX = 83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN SRVC_UDV_FX = 562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN SRVC_UDV_FX = 570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN SRVC_UDV_FX = 8300;


RUN;

DATA FALT002;
SET FALT002; 
KEEP TRN_AUTH_POST DATE1 AUTH_DECISION_XCD USER_INDICATOR_7_XCD  TRN_TYP MER_CNTY_CD 
MER_NM USR_IND_4 TRN_POS_ENT_CD ACCT_NBR FI_TRANSACTION_ID TRN_AMT TRN_AMT_LOCAL USD 
CRD_CLNT_ID TRAN_DATE AUTH_DTTM TRN_DT MCC ATMONUS TIME TRANSACTION_CATEGORY_XCD SIC_CD AA_SCOR DECI_CD_ORIG
FRD_SCOR MER_ID USER_INDICATOR_7_XCD SRVC_UDV_FX SRVC_UDV_ISSUER_COUNTRY_CODE ACQUIRER_ID	;
RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_1 OUT=FALT002_2 ; BY ATMONUS AUTH_DTTM; RUN;

/**/
/*DATA FALT002_2;*/
/*     SET FALT002_2;*/
/*     BY ATMONUS AUTH_DTTM;*/
/**/
/*     FORMAT ATMONUS_FIRST_TXN_DATE DATETIME19. ATMONUS_FIRST_APPROVAL_DATE DATETIME19.;*/
/*	 RETAIN ATMONUS_FIRST_TXN_DATE ATMONUS_FIRST_APPROVAL_DATE;*/
/**/
/*     IF FIRST.ATMONUS THEN DO;*/
/*           ATMONUS_FIRST_TXN_DATE = 0;*/
/*		   ATMONUS_FIRST_APPROVAL_DATE = 0;*/
/*     END;*/
/**/
/*     IF TRN_AUTH_POST = "A" and MER_ID NE "" THEN DO;*/
/*           IF ATMONUS_FIRST_TXN_DATE = 0 THEN DO;*/
/*                ATMONUS_FIRST_TXN_DATE = AUTH_DTTM;*/
/*           END;*/
/*           IF ATMONUS_FIRST_APPROVAL_DATE = 0 AND TRN_TYP IN ("C" "M" "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG = "A") */
/*		   AND USD GT 0 THEN DO;*/
/*                ATMONUS_FIRST_APPROVAL_DATE = AUTH_DTTM;*/
/*           END;*/
/*     END;*/
/**/
/**/
/*RUN;*/
/**/
/**/
/*%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);*/
/**/
/*DATA FALT002_2;*/
/*     SET FALT002_2;*/
/*     BY ATMONUS AUTH_DTTM;*/
/**/
/*     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;*/
/**/
/*     RETAIN CUM_COUNT_&VAR_NAME. CUM_COUNT_MAX_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME. CUM_AMOUNT_MAX_&VAR_NAME.*/
/*			&VAR_NAME._AA_SCORE &VAR_NAME._BASE_SCORE */
/*			CUM_COUNT_APPR_&VAR_NAME. CUM_AMOUNT_APPR_&VAR_NAME. &VAR_NAME._PREV;*/
/**/
/*     IF FIRST.ATMONUS THEN DO;*/
/*           TIME_RESET_&VAR_NAME. = 0;*/
/*           CUM_COUNT_&VAR_NAME. = 0;*/
/*           CUM_AMOUNT_&VAR_NAME. = 0;*/
/*		   CUM_COUNT_APPR_&VAR_NAME. = 0;*/
/*		   CUM_AMOUNT_APPR_&VAR_NAME. = 0;*/
/*		   &VAR_NAME._BASE_SCORE=0;*/
/*		   &VAR_NAME._AA_SCORE=0;*/
/*		   CUM_COUNT_MAX_&VAR_NAME.=0;*/
/*		   CUM_AMOUNT_MAX_&VAR_NAME.=0;*/
/*		   ATMONUS_FIRST_TXN_DATE=AUTH_DTTM;*/
/*     END;*/
/**/
/*     IF &CUMULATIVE_CONDITION. THEN DO;*/
/*           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;*/
/*                CUM_COUNT_&VAR_NAME. + 1;*/
/*                CUM_AMOUNT_&VAR_NAME. + USD;*/
/*				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND*/
/*					USD GT 0) THEN DO;*/
/*					CUM_COUNT_APPR_&VAR_NAME. + 1 ;*/
/*					CUM_AMOUNT_APPR_&VAR_NAME. + USD;*/
/*				END;*/
/*				&VAR_NAME._BASE_SCORE=MAX(&VAR_NAME._BASE_SCORE,FRD_SCOR);*/
/*				&VAR_NAME._AA_SCORE=MAX(&VAR_NAME._AA_SCORE,AA_SCOR);*/
/*           END;*/
/*           ELSE DO;*/
/*		   		CUM_COUNT_MAX_&VAR_NAME. = max(CUM_COUNT_MAX_&VAR_NAME., CUM_COUNT_APPR_&VAR_NAME.);*/
/*				CUM_AMOUNT_MAX_&VAR_NAME. = max(CUM_AMOUNT_MAX_&VAR_NAME., CUM_AMOUNT_APPR_&VAR_NAME.);*/
/*				ATMONUS_DAILY_DAYS + 1;*/
/*				CUM_COUNT_&VAR_NAME. = 1;*/
/*           		CUM_AMOUNT_&VAR_NAME. = USD;*/
/*                CUM_COUNT_APPR_&VAR_NAME. = 0;*/
/*		   		CUM_AMOUNT_APPR_&VAR_NAME. = 0;*/
/*				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND*/
/*					USD GT 0) THEN DO;*/
/*					CUM_COUNT_APPR_&VAR_NAME. = 1 ;*/
/*					CUM_AMOUNT_APPR_&VAR_NAME. = USD;*/
/*				END;*/
/*				&VAR_NAME._PREV = TIME_RESET_&VAR_NAME.;*/
/*				TIME_RESET_&VAR_NAME. = AUTH_DTTM;*/
/*				&VAR_NAME._BASE_SCORE = FRD_SCOR;*/
/*				&VAR_NAME._AA_SCORE = AA_SCOR;*/
/*           END;*/
/*     END;*/
/**/
/*RUN;*/
/*%MEND; */
/**/
/*%UDV(CUM_INTERVAL        = 86400,                                          */
/*     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" and MER_ID NE "") ,*/
/*     VAR_NAME            = ATMONUS_DAILY);*/

/*PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Hotlist\hotlist_Data.xls"*/
/*OUT=LOOKUP_DATA DBMS=XLS REPLACE;RUN;*/
/**/
/**/
/*PROC SQL;*/
/*CREATE TABLE FALT002_LKP AS*/
/*SELECT * FROM FALT002_2 WHERE ACCT_NBR IN (SELECT HOTLIST_VALUE_NAME FROM LOOKUP_DATA where TENANT_CD = 'FI_BASE_TENANT');*/
/*RUN;*/


PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;


%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);
DATA FALT002_2;
SET FALT002_2;
     BY ACCT_NBR AUTH_DTTM;

    FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LT (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = USD;
           END;
     END;
RUN;
%MEND;

%UDV
(
CUM_INTERVAL = 3600,                                          
CUMULATIVE_CONDITION = %STR
(
     TRN_AUTH_POST = "A" AND 
     AUTH_DECISION_XCD = "A" AND 
     TRN_TYP IN ("C" "M" "P") AND 
     TRN_POS_ENT_CD IN ("E" "K" "G" "") AND
/*	 SIC_CD IN ("6011" "0000") AND*/
	 TRN_AMT > 0
),
VAR_NAME = CNP_HOURLY
);

DATA TEMP_TXN_DATA;
    SET FALT002_2;
	WHERE DATE1 GE "16NOV2021"D;
IF 

(
(
 TRN_AUTH_POST  = "A" AND
 TRN_TYP  IN ("C" "M" "P") AND
 AUTH_DECISION_XCD  = "A" AND
/*LOOKUPLIST("GENUINE",PAN) = 0 AND*/
/*LOOKUPLIST("VIP LIST",PAN) = 0 AND*/
 TRN_POS_ENT_CD  IN ("E" "K" "G" "") AND
SUBSTR(USR_IND_4,1,2) NE "Y2" AND
 TRN_AMT  > 0
)and
(
( CRD_CLNT_ID  = "SC_EURONETSG_DB" AND
 MER_CNTY_CD  NE "702" AND
CUM_COUNT_CNP_HOURLY > 7
)

OR
(
 CRD_CLNT_ID  = "SC_EURONETMY_DB" AND
 MER_CNTY_CD  NE "458" AND
(
(CUM_COUNT_CNP_HOURLY > 3 AND CUM_AMOUNT_CNP_HOURLY > 1500) OR
CUM_COUNT_CNP_HOURLY > 25
)
)

OR ( CRD_CLNT_ID  = "SC_EURONETIN_DB" AND
 MER_CNTY_CD  NE "356" AND
(
(CUM_COUNT_CNP_HOURLY > 4 AND CUM_AMOUNT_CNP_HOURLY > 200) OR
CUM_COUNT_CNP_HOURLY > 25
)
)

OR ( CRD_CLNT_ID  = "SC_EURONETAE_DB" AND
 MER_CNTY_CD  NE "784" AND
(
(CUM_COUNT_CNP_HOURLY > 5 AND CUM_AMOUNT_CNP_HOURLY > 500) OR
CUM_COUNT_CNP_HOURLY > 25
)
)
)
)

THEN FLAG="Y";
RUN;

DATA TXN_DATA;
SET TEMP_TXN_DATA;
WHERE FLAG = "Y" and date1 GE "16NOV2021"D;
RUN;


DATA RULE_DATA;
SET 
INC.falt003_db_16nov;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_INT_CNP_60MIN') and CLIENT_XID IN ("SC_EURONETSG_DB" "SC_EURONETMY_DB" "SC_EURONETIN_DB" "SC_EURONETAE_DB")
and date1 GE "16NOV2021"D;
RUN;

PROC SORT DATA = RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Int_CNP_60MIN  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Int_CNP_60MIN  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

/* Writing Outout to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Int_CNP_60MIN SG Debit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Int_CNP_60MIN  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Int_CNP_60MIN  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Int_CNP_60MIN SG Debit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_Global_Int_CNP_60MIN SG Debit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;







/********************** cross check 6 STEPS ***********************/

/* 1 - Getting txns in SAS not in Falcon */
/* MER_ID is Name in VIP list Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT ACCT_NBR, FI_TRANSACTION_ID, MER_ID, CRD_CLNT_ID FROM TXN_DATA where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
RULE_DATA);
QUIT;


/* 1 - Getting txns in Falcon not in SAS */
/* MER_ID is Name in VIP list Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT SCORE_CUSTOMER_ACCOUNT_XID, FI_TRANSACTION_ID, CLIENT_XID FROM RULE_DATA where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
TXN_DATA);
QUIT;


DATA TXN_CHECK;
SET 
FALT002;
WHERE FI_TRANSACTION_ID IN 
(
'20617aa2a5000661'
'20617aa2a5000666'
);
RUN;


/* 2 - High priority rule check */

DATA OTHER_RULE;
SET 
INC.falt003_db_03nov
INC.falt003_db_04nov;
WHERE FI_TRANSACTION_ID IN 
(
'0261925208010342'
'1e6192515302d9f6'
'216192518202bbcf'
'1f6192515402b058'
'1f6192515400fba4'
'1f6192515400ff28'
'0161925209010909'
'0261925208010ece'
'03619252320135b6'
'036192523202fe7c'
'216192518202ec69'
'216192518202ed90'
'1e6192515301bb13'
) and
UPCASE(RULE_NAME_STRG) not IN ('HR_GLOBAL_INT_CNP_60MIN');
RUN;


/* 3 - Genuine list check */

DATA CASACTN;
SET INC.casactn_db_15nov
INC.casactn_db_16nov;
WHERE ACCT_NBR IN 
(
"4585460009686552"
"4585460011485225"
"4585460018184896"
"4847980001856485"
"5243551020076863"
"5243551020076863"
"5243551020076863"
"5243551021005309"
"5243551022182206"
"5243551022253171"
"5243551022253171"
"5243551022253171"
"5523527021618698"
) and date1 ge "15NOV2021"d;
RUN;

/* 4 - If not solved in previous steps chec those ACCT_NBRs here*/
/* MER_ID or Name extraction for ACCT_NBS in SAS not in Falcon*/

PROC SQL;
CREATE TABLE VIP AS 
SELECT distinct(MER_ID), FI_TRANSACTION_ID FROM Txn_Data where ACCT_NBR in
(
'5523438412256975'
);
RUN;

/* 5 - Check if the ACCT_NBR is present in VIP list (Case manager)*/

DATA VIP_LIST;
SET LOOKUP_DATA;
WHERE
NAME IN(
'484767000200403'
'EP86CJLWQYAQGJM'
);
RUN;


DATA UDV_Mismatch;
SET TEMP_TXN_DATA;
WHERE FI_TRANSACTION_ID IN 
(
'0361925232013613'
'0361925232013619'
'03619252320136b3'
'2161925182013091'
'2161925182013120'
'2161925182013126'
);
RUN;

PROC EXPORT DATA= UDV_Mismatch
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\MR_Country_CNP_Google_Facebook_Test BD Credi.xlsx"
dbms=xlsx replace;
sheet="UDV_Mismatch";
run;

/********************** cross check 6 STEPS ***********************/