

**************************************************************************************

				HR_Global_CRYPTO_Merchants7 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS7';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"BITPESA") OR
INDEX(UPCASE(MER_NM),"BITPOINT") OR
INDEX(UPCASE(MER_NM),"BITQUICK") OR
INDEX(UPCASE(MER_NM),"BITRUSH") OR
INDEX(UPCASE(MER_NM),"BITS BLOCKCHAIN") OR
INDEX(UPCASE(MER_NM),"BITSECUREBUY.COM") OR
INDEX(UPCASE(MER_NM),"BITSTAMP.NET") OR
INDEX(UPCASE(MER_NM),"BIT-Z") OR
INDEX(UPCASE(MER_NM),"BTC-PLACE.COM") OR
INDEX(UPCASE(MER_NM),"BUYABITCOIN") OR
INDEX(UPCASE(MER_NM),"BUYBITSHOP.COM") OR
INDEX(UPCASE(MER_NM),"BUYCOIN") OR
INDEX(UPCASE(MER_NM),"BUYEGLCOM") OR
INDEX(UPCASE(MER_NM),"BUYMOREBIT.COM") OR
INDEX(UPCASE(MER_NM),"BUYUCOIN") OR
INDEX(UPCASE(MER_NM),"BUYWKB.COM") OR
INDEX(UPCASE(MER_NM),"BX THAILAND") OR
INDEX(UPCASE(MER_NM),"CAURI*ADVCASH.COM") OR
INDEX(UPCASE(MER_NM),"CAURI*PAYEER.COM") OR
INDEX(UPCASE(MER_NM),"CFS*CFSBITCOINROMANIA") OR
INDEX(UPCASE(MER_NM),"CHANGELLY") OR
INDEX(UPCASE(MER_NM),"COBINHOOD") OR
INDEX(UPCASE(MER_NM),"COIN.Z") OR
INDEX(UPCASE(MER_NM),"COINBASE UK") OR
INDEX(UPCASE(MER_NM),"COINBENE") OR
INDEX(UPCASE(MER_NM),"COINBUYNOW.COM") OR
INDEX(UPCASE(MER_NM),"COINCORNERSHOP.COM") OR
INDEX(UPCASE(MER_NM),"COINEGG") OR
INDEX(UPCASE(MER_NM),"COINFALCON") OR
INDEX(UPCASE(MER_NM),"COINHAKO") OR
INDEX(UPCASE(MER_NM),"COINHOUSE SAS") OR
INDEX(UPCASE(MER_NM),"COINJAR PTY LTD") OR
INDEX(UPCASE(MER_NM),"COINMAMA.COM") OR
INDEX(UPCASE(MER_NM),"COINPIA") OR
INDEX(UPCASE(MER_NM),"COINRAIL") OR
INDEX(UPCASE(MER_NM),"COINROOM") OR
INDEX(UPCASE(MER_NM),"COINS.MY") OR
INDEX(UPCASE(MER_NM),"COINSMARKETS") OR
INDEX(UPCASE(MER_NM),"CREX24") OR
INDEX(UPCASE(MER_NM),"CRXZONE") OR
INDEX(UPCASE(MER_NM),"CRYPTOBRIDGE") OR
INDEX(UPCASE(MER_NM),"CRYPTOCONNECT.CA") OR
INDEX(UPCASE(MER_NM),"CRYPTOPALAZZO.COM") OR
INDEX(UPCASE(MER_NM),"CRYPTOPAY.COM") OR
INDEX(UPCASE(MER_NM),"CRYPTOPAYWWW.CRYPTOPAY") OR
INDEX(UPCASE(MER_NM),"CRYTOPIA") OR
INDEX(UPCASE(MER_NM),"DMM BITCOIN")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS7 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS7;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;