
****************************************************
HR_Global_Blacklist_MIDS_Supress DR CREDIT
****************************************************;

LIBNAME DC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

DATA FALT002;
SET

DC.FALT002_CR_16JUL;

where
CRD_CLNT_ID IN ("SC_PMTHK_CR");
FORMAT TRAN_DATE DATE9.;
TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));
MCC = INPUT(SIC_CD,BEST.);


	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT_LOCAL/7.8;

RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;

PROC IMPORT DATAFILE='C:\Users\1510806\Desktop\Jhilam\Hotlist\LIMIT_BASED_WHITELIST_HK.XLS'
DBMS = XLS
OUT = LOOKUP_DATA
REPLACE;
RUN;


PROC SQL;
CREATE TABLE FALT002_2 AS
SELECT * FROM FALT002_2
WHERE 
/* Base tenant hotlist */
(
(
CRD_CLNT_ID IN ("SC_PMTHK_CR")
 TRN_AUTH_POST  = "A" AND
( AUTH_DECISION_XCD  = "A" OR (AUTH_DECISION_XCD = "" AND  DECI_CD_ORIG  = "A")) AND
 TRN_TYP  IN ("C" "M" "P") AND
TRN_POS_ENT_CD  IN ("E" "K" "G") AND
GETLOOKUPLISTVALUE("BLACKLISTED_MERCHANTS", COMPRESS(MER_ID), HOTLISTVALUE) = 1 AND
/*LOOKUPLIST("GENUINE",PAN) = 0 AND*/
HOTLISTVALUE <> '' AND
IS_NUMERIC(HOTLISTVALUE) = 1
)
AND
(CVV2RESPONSE = "M")
);

QUIT;

PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2 OUT=FALT003; BY ACCT_NBR AUTH_DTTM; RUN;


DATA TXN_DATA;
SET FALT003;
WHERE DATE1 GE "16JUL2021"D;
RUN;

DATA RULE_DATA;
SET
DC.FALT003_CR_16JUL;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_BLACKLIST_MIDS_SUPRESS') AND
CLIENT_XID IN ("SC_PMTHK_CR") AND
DATE1 GE "16JUL2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "TXN_DATA SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA=RULE_DATA; TITLE "RULE_DATA FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;


/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Blacklist_MIDS_Supress DR CREDIT.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Blacklist_MIDS_Supress SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Blacklist_MIDS_Supress FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Blacklist_MIDS_Supress DR CREDIT.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Blacklist_MIDS_Supress DR CREDIT.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;

