
**********************************************************
		HR_Global_Google_Specific AE IN SG MY Credit
				
**********************************************************;
 
/*PROC DELETE DATA=_ALL_;RUN;*/
OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

DATA FALT002;
SET  
CR.falt002_SG_cr_JUL2021
CR.falt002_SG_cr_MAY2021
CR.falt002_SG_cr_JUN2021
CR.falt002_MY_cr_JUL2021
CR.falt002_MY_cr_MAY2021
CR.falt002_MY_cr_JUN2021
CR.falt002_IN_cr_JUL2021
CR.falt002_IN_cr_MAY2021
CR.falt002_IN_cr_JUN2021
CR.falt002_AE_cr_JUL2021
CR.falt002_AE_cr_MAY2021
CR.falt002_AE_cr_JUN2021
INC.falt002_cr_01AUG
INC.falt002_cr_02AUG
INC.falt002_cr_03AUG
INC.falt002_cr_04AUG
INC.falt002_cr_05AUG
INC.falt002_cr_06AUG
INC.falt002_cr_07AUG
INC.falt002_cr_08AUG
INC.falt002_cr_09AUG
INC.falt002_cr_10AUG
INC.falt002_cr_11AUG
INC.falt002_cr_12AUG
INC.falt002_cr_13AUG
INC.falt002_cr_14AUG
INC.falt002_cr_15AUG
INC.falt002_cr_16AUG
INC.falt002_cr_17AUG
INC.falt002_cr_18AUG
INC.falt002_cr_19AUG
INC.falt002_cr_20AUG
INC.falt002_cr_21AUG
INC.falt002_cr_22AUG
INC.falt002_cr_23AUG
INC.falt002_cr_24AUG
INC.falt002_cr_25AUG
INC.falt002_cr_26AUG
INC.falt002_cr_27AUG;

     WHERE TRN_AUTH_POST = "A"  AND DATE1 GE "01MAY2021"D AND
 CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSMY_CR" "SC_CCMSIN_CR" "SC_C400AE_CR");
     FORMAT TRAN_DATE DATE9. TIME TIME8.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
         ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
/*         IF AUTH_DTTM GE "26FEB2021:22:15:00"DT;*/
         TIME = TIMEPART(AUTH_DTTM);

  	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

RUN;

DATA FALT002;
SET FALT002; 
KEEP TRN_AUTH_POST DATE1 AUTH_DECISION_XCD USER_INDICATOR_7_XCD  TRN_TYP MER_CNTY_CD 
MER_NM USR_IND_4 TRN_POS_ENT_CD ACCT_NBR FI_TRANSACTION_ID TRN_AMT TRN_AMT_LOCAL USD 
CRD_CLNT_ID TRAN_DATE AUTH_DTTM TRN_DT MCC ATMONUS TIME TRANSACTION_CATEGORY_XCD SIC_CD AA_SCOR DECI_CD_ORIG
FRD_SCOR MER_ID;
RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_1 OUT=FALT002_2 ; BY ATMONUS AUTH_DTTM; RUN;


DATA FALT002_2;
     SET FALT002_2;
     BY ATMONUS AUTH_DTTM;

     FORMAT ATMONUS_FIRST_TXN_DATE DATETIME19. ATMONUS_FIRST_APPROVAL_DATE DATETIME19.;
	 RETAIN ATMONUS_FIRST_TXN_DATE ATMONUS_FIRST_APPROVAL_DATE;

     IF FIRST.ATMONUS THEN DO;
           ATMONUS_FIRST_TXN_DATE = 0;
		   ATMONUS_FIRST_APPROVAL_DATE = 0;
     END;

     IF TRN_AUTH_POST = "A" and MER_ID NE "" THEN DO;
           IF ATMONUS_FIRST_TXN_DATE = 0 THEN DO;
                ATMONUS_FIRST_TXN_DATE = AUTH_DTTM;
           END;
           IF ATMONUS_FIRST_APPROVAL_DATE = 0 AND TRN_TYP IN ("C" "M" "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG = "A") 
		   AND USD GT 0 THEN DO;
                ATMONUS_FIRST_APPROVAL_DATE = AUTH_DTTM;
           END;
     END;


RUN;


%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ATMONUS AUTH_DTTM;

     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. CUM_COUNT_MAX_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME. CUM_AMOUNT_MAX_&VAR_NAME.
			&VAR_NAME._AA_SCORE &VAR_NAME._BASE_SCORE 
			CUM_COUNT_APPR_&VAR_NAME. CUM_AMOUNT_APPR_&VAR_NAME. &VAR_NAME._PREV;

     IF FIRST.ATMONUS THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
		   CUM_COUNT_APPR_&VAR_NAME. = 0;
		   CUM_AMOUNT_APPR_&VAR_NAME. = 0;
		   &VAR_NAME._BASE_SCORE=0;
		   &VAR_NAME._AA_SCORE=0;
		   CUM_COUNT_MAX_&VAR_NAME.=0;
		   CUM_AMOUNT_MAX_&VAR_NAME.=0;
		   ATMONUS_FIRST_TXN_DATE=AUTH_DTTM;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND
					USD GT 0) THEN DO;
					CUM_COUNT_APPR_&VAR_NAME. + 1 ;
					CUM_AMOUNT_APPR_&VAR_NAME. + USD;
				END;
				&VAR_NAME._BASE_SCORE=MAX(&VAR_NAME._BASE_SCORE,FRD_SCOR);
				&VAR_NAME._AA_SCORE=MAX(&VAR_NAME._AA_SCORE,AA_SCOR);
           END;
           ELSE DO;
		   		CUM_COUNT_MAX_&VAR_NAME. = max(CUM_COUNT_MAX_&VAR_NAME., CUM_COUNT_APPR_&VAR_NAME.);
				CUM_AMOUNT_MAX_&VAR_NAME. = max(CUM_AMOUNT_MAX_&VAR_NAME., CUM_AMOUNT_APPR_&VAR_NAME.);
				ATMONUS_DAILY_DAYS + 1;
				CUM_COUNT_&VAR_NAME. = 1;
           		CUM_AMOUNT_&VAR_NAME. = USD;
                CUM_COUNT_APPR_&VAR_NAME. = 0;
		   		CUM_AMOUNT_APPR_&VAR_NAME. = 0;
				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND
					USD GT 0) THEN DO;
					CUM_COUNT_APPR_&VAR_NAME. = 1 ;
					CUM_AMOUNT_APPR_&VAR_NAME. = USD;
				END;
				&VAR_NAME._PREV = TIME_RESET_&VAR_NAME.;
				TIME_RESET_&VAR_NAME. = AUTH_DTTM;
				&VAR_NAME._BASE_SCORE = FRD_SCOR;
				&VAR_NAME._AA_SCORE = AA_SCOR;
           END;
     END;

RUN;
%MEND; 

%UDV(CUM_INTERVAL        = 86400,                                          
     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" and MER_ID NE "") ,
     VAR_NAME            = ATMONUS_DAILY);


PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;


%MACRO UDV_GOOGLE(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);
DATA FALT002_2;
SET FALT002_2;
     BY ACCT_NBR AUTH_DTTM;

    FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LT (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = USD;
           END;
     END;
RUN;
%MEND;

%UDV_GOOGLE
(
CUM_INTERVAL = 86400,                                          
CUMULATIVE_CONDITION = %STR
(
     TRN_AUTH_POST = "A" AND 
     AUTH_DECISION_XCD = "A" AND 
     TRN_TYP IN ("C" "M" "P") AND 
     TRN_POS_ENT_CD IN ("E" "K" "G" "") AND 
	 INDEX(UPCASE(MER_NM), "GOOGLE") AND 
     TRN_AMT > 0
),
VAR_NAME = GOOGLE_DAILY
);


%UDV_GOOGLE
(
CUM_INTERVAL = 3600,                                          
CUMULATIVE_CONDITION = %STR
(
     TRN_AUTH_POST = "A" AND 
     AUTH_DECISION_XCD = "A" AND 
     TRN_TYP IN ("C" "M" "P") AND 
     TRN_POS_ENT_CD IN ("E" "K" "G" "") AND
     TRN_AMT > 0
),
VAR_NAME = GOOGLE_HOURLY
);


DATA TEMP_TXN_DATA;
    SET FALT002_2;
	WHERE DATE1 GE "27AUG2021"D;
IF 
(
 CRD_CLNT_ID  IN ("SC_CCMSSG_CR" "SC_CCMSMY_CR" "SC_CCMSIN_CR" "SC_C400AE_CR") AND
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 TRN_TYP  IN ("C" "M" "P") AND
TRN_POS_ENT_CD  IN ("E" "K" "G") AND
SUBSTR(USR_IND_4,1,2) NE "Y2" AND
INDEX(UPCASE(MER_NM), "GOOGLE") AND
 TRN_AMT  > 0 AND
(
(INDEX(UPCASE(MER_NM), "ADS") AND SUBSTR(USER_INDICATOR_7_XCD,1,3) not in ("702", "458", "356", "784") AND CUM_AMOUNT_GOOGLE_DAILY > 200) OR
(INDEX(UPCASE(MER_NM), "*GAMANIA") AND CUM_COUNT_GOOGLE_HOURLY > 1) OR
(INDEX(UPCASE(MER_NM), "*CHROME") AND CUM_AMOUNT_GOOGLE_DAILY > 200) OR
(INDEX(UPCASE(MER_NM), "NCSOFT")) OR
(INDEX(UPCASE(MER_NM), "NGUYEN")) OR
(INDEX(UPCASE(MER_NM), "ROBLOX") AND CUM_COUNT_GOOGLE_DAILY > 10) OR
(INDEX(UPCASE(MER_NM), "PROXIMA") AND CUM_COUNT_GOOGLE_DAILY > 10) OR
(INDEX(UPCASE(MER_NM), "NUVERSE") AND  CUM_AMOUNT_APPR_ATMONUS_DAILY > 200)
) AND
NOT(
 AUTH_DTTM - ATMONUS_FIRST_APPROVAL_DATE > 1 AND
 CUM_AMOUNT_APPR_ATMONUS_DAILY  <= 2 *  CUM_AMOUNT_MAX_ATMONUS_DAILY  AND
 CUM_COUNT_APPR_ATMONUS_DAILY  <= 2 *  CUM_COUNT_MAX_ATMONUS_DAILY 
)
)
THEN FLAG="Y";
RUN;

DATA TXN_DATA;
SET TEMP_TXN_DATA;
WHERE FLAG = "Y" and date1 GE "27AUG2021"D;
RUN;


DATA RULE_DATA;
SET 
INC.falt003_cr_27AUG;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_GOOGLE_SPECIFIC') and CLIENT_XID IN  ("SC_CCMSSG_CR" "SC_CCMSMY_CR" "SC_CCMSIN_CR" "SC_C400AE_CR")
and date1 GE "27AUG2021"D;
RUN;

PROC SORT DATA = RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Google_Specific  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Google_Specific  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

/* Writing Outout to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Google_Specific AE IN SG MY Credit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Google_Specific  SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Google_Specific  FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Google_Specific AE IN SG MY Credit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Google_Specific AE IN SG MY Credit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;







/*CROSS CHECK* - 5 STEPS */


PROC EXPORT DATA= CASACTN
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_MID_Merchantname Global Credit.xlsx"
dbms=xlsx replace;
sheet="CASACTN";
run;

PROC EXPORT DATA= OTHER_RULE
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_MID_Merchantname Global Credit.xlsx"
dbms=xlsx replace;
sheet="OTHER_RULE";
run;


/********************** cross check 6 STEPS ***********************/

/* 1 - Getting txns in SAS not in Falcon */
/* MER_ID is Name in VIP list Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT ACCT_NBR, FI_TRANSACTION_ID, MER_ID, CRD_CLNT_ID FROM TXN_DATA where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
RULE_DATA);
QUIT;


/* 1 - Getting txns in Falcon not in SAS */
/* MER_ID is Name in VIP list Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT SCORE_CUSTOMER_ACCOUNT_XID, FI_TRANSACTION_ID, CLIENT_XID FROM RULE_DATA where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
TXN_DATA);
QUIT;


DATA TXN_CHECK;
SET 
FALT002;
WHERE FI_TRANSACTION_ID IN 
(
'0060cca6d402f4ee',
'1e60cca61502dc17',
'2060cca6140444cf'
);
RUN;


/* 2 - High priority rule check */

DATA OTHER_RULE;
SET 
INC.falt003_cr_26aug
INC.falt003_cr_27aug;
WHERE FI_TRANSACTION_ID IN 
(
'0361279a8100d026'
'0361279a8100d03a'
) and
UPCASE(RULE_NAME_STRG) not IN ('HR_GLOBAL_GOOGLE_SPECIFIC');
RUN;


/* 3 - Genuine list check */

DATA CASACTN;
SET
INC.casactn_cr_26aug
INC.casactn_cr_27aug;
WHERE ACCT_NBR IN 
(
"5498341641562562"
"5498341641562562"
) and date1 ge "26AUG2021"d;
RUN;

/* 4 - If not solved in previous steps chec those ACCT_NBRs here*/
/* MER_ID or Name extraction for ACCT_NBS in SAS not in Falcon*/

PROC SQL;
CREATE TABLE VIP AS 
SELECT distinct(MER_ID), FI_TRANSACTION_ID FROM Txn_Data where ACCT_NBR in
(
'5523438412256975'
);
RUN;

/* 5 - Check if the ACCT_NBR is present in VIP list (Case manager)*/

DATA VIP_LIST;
SET LOOKUP_DATA;
WHERE
NAME IN(
'484767000200403'
'EP86CJLWQYAQGJM'
);
RUN;


DATA UDV_Mismatch;
SET TEMP_TXN_DATA;
WHERE FI_TRANSACTION_ID IN 
(
'0060df0d5a00840e'
'0060df0d5a038513'
'0060df0d5a03854d'
);
RUN;

PROC EXPORT DATA= UDV_Mismatch
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\MR_Country_CNP_Google_Facebook_Test BD Credi.xlsx"
dbms=xlsx replace;
sheet="UDV_Mismatch";
run;

/********************** cross check 6 STEPS ***********************/