

**************************************************************************************

				HR_Global_CRYPTO_Merchants5 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS5';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"FYBSG") OR
INDEX(UPCASE(MER_NM),"DIGITALASSET") OR
INDEX(UPCASE(MER_NM),"GENERALBYTES") OR
INDEX(UPCASE(MER_NM),"GHASHIO") OR
INDEX(UPCASE(MER_NM),"LIBERTYX") OR
INDEX(UPCASE(MER_NM),"MAGNR") OR
INDEX(UPCASE(MER_NM),"MTGOX") OR
INDEX(UPCASE(MER_NM),"PANTERACAPITAL") OR
INDEX(UPCASE(MER_NM),"SATOSHICITADEL") OR
INDEX(UPCASE(MER_NM),"SATOSHIDICE") OR
INDEX(UPCASE(MER_NM),"SEARCHTRADE") OR
INDEX(UPCASE(MER_NM),"TIDBIT") OR
INDEX(UPCASE(MER_NM),"WIREX") OR
INDEX(UPCASE(MER_NM),"XAPO") OR
INDEX(UPCASE(MER_NM),"COINMAMA") OR
INDEX(UPCASE(MER_NM),"LOCALBITCOIN") OR
INDEX(UPCASE(MER_NM),"COINPLUG") OR
INDEX(UPCASE(MER_NM),"CRYPTOGO") OR
INDEX(UPCASE(MER_NM),"COINCORNER") OR
INDEX(UPCASE(MER_NM),"ETHEXINDIA") OR
INDEX(UPCASE(MER_NM),"REMITANO") OR
INDEX(UPCASE(MER_NM),"BITPANDA") OR
INDEX(UPCASE(MER_NM),"COINHOUSE") OR
INDEX(UPCASE(MER_NM),"247 EXCHANGE") OR
INDEX(UPCASE(MER_NM),"BITCOIN.COM") OR
INDEX(UPCASE(MER_NM),"COINGATE") OR
INDEX(UPCASE(MER_NM),"BREAD") OR
INDEX(UPCASE(MER_NM),"BITIT.IO")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS5 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS5;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;