

*************************************************************
				HR_Global_Merchant_MID Debit

**************************************************************;

PROC IMPORT DATAFILE="C:\Users\1510806\Desktop\Jhilam\Daily Data\Hotlist\BLACKLISTED_MID_WITH_NAME_DEBIT.xlsx" DBMS=XLSX
OUT=BLACKLISTED_MID_WITH_NAME_DB REPLACE;RUN;

OPTIONS VALIDVARNAME = ANY;

DATA BLACKLISTED_MID_WITH_NAME_db_1;
SET BLACKLISTED_MID_WITH_NAME_DB;
NAME_1=SCAN(NAME,-2,":");
     FORMAT TRAN_DATE1 DATE9.;
     TRAN_DATE1 = MDY(SUBSTR('LAST UPDATED'N,1,2) , SUBSTR('LAST UPDATED'N,4,2) , SUBSTR('LAST UPDATED'N,7,4));
     ATTRIB LAST_UPDATED FORMAT=DATETIME19.;
     LAST_UPDATED=DHMS(TRAN_DATE1,SUBSTR('LAST UPDATED'N,12,2),SUBSTR('LAST UPDATED'N,15,2),SUBSTR('LAST UPDATED'N,18,2)); 
RUN;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";

DATA  FALT002;
     SET INC.FALT002_db_16JUN 
		 INC.FALT002_db_17JUN;   
     WHERE (	TRN_AUTH_POST = "A" and 
	(AUTH_DECISION_XCD = "A" or ((AUTH_DECISION_XCD)="" and DECI_CD_ORIG = "A")) and 
	TRN_TYP IN ("C"  "M"  "P"  "A") and TRN_POS_ENT_CD IN ("E"  "K"  "G" ""));
/*and SUBSTR(USR_IND_4,1,2) NE "Y2" ) ;*/
	IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) NOT IN ("HK" "TW" "BD" "ID") THEN TENANT = "Global"; 
	ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("HK") THEN TENANT = "HK";
	ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("TW") THEN TENANT = "TW";
	ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("BD") THEN TENANT = "BD";
	ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("ID") THEN TENANT = "ID";
	 FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;


PROC SQL;
CREATE TABLE FALT002_2 AS SELECT A.*,B.NAME ,B.VALUE FROM
(SELECT * FROM FALT002 WHERE COMPRESS(MER_ID) IN 
(SELECT DISTINCT NAME_1 FROM BLACKLISTED_MID_WITH_NAME_db_1)) A
LEFT JOIN 
BLACKLISTED_MID_WITH_NAME_db_1 B 
ON COMPRESS(A.MER_ID) = B.NAME_1
WHERE A.AUTH_DTTM GE B.LAST_UPDATED;
QUIT;


DATA HR_Global_Merchant_MID_SAS;
SET FALT002_2;
IF INDEX(MER_NM,STRIP(VALUE)) > 0 THEN FLAG = "Y";
RUN;

DATA TXN_DATA;
SET HR_Global_Merchant_MID_SAS;
WHERE FLAG = "Y" and date1 GE "17JUN2021"D;
RUN;

DATA RULE_DATA;
 SET INC.falt003_db_16JUN	
	 INC.falt003_db_17JUN;
	WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_MERCHANT_MID') and date1 GE "17JUN2021"D;
	IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) NOT IN ("HK" "TW" "BD" "ID") THEN TENANT = "Global"; 
	ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("HK") THEN TENANT = "HK";
	ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("TW") THEN TENANT = "TW";
	ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("BD") THEN TENANT = "BD";
	ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("ID") THEN TENANT = "ID";
RUN;

PROC SORT DATA = RULE_DATA NODUPKEY ;BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA; TITLE "HR_Global_Merchant_MID SAS"; 
TABLE TENANT*DATE1/NOCOL NOROW NOPERCENT NOCUM;  RUN;

PROC FREQ DATA=RULE_DATA; TITLE "HR_Global_Merchant_MID FALCON HITS"; 
TABLE TENANT*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;


ods listing;
ods excel file='C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Merchant_MID Debit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
PROC FREQ DATA = TXN_DATA;TITLE "HR_Global_Merchant_MID SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_Global_Merchant_MID FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Merchant_MID Debit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\HR_Global_Merchant_MID Debit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;




/*MISMATCH CHECKING*/


DATA HR_GLOBAL_MERCHANT_DECLINE_RL;
SET INC.falt003_db_29jun	INC.falt003_db_30jun;
WHERE (UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_MERCHANT_DECLINE') AND CLIENT_XID IN ('SC_SPARROWBD_DB' 'SC_HOGANHK_DB'
'SC_EURONETID_DB' 'SC_TANDEMTW_DB')) OR
(UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_MERCHANT_DECLINE_1') AND CLIENT_XID NOT IN ('SC_SPARROWBD_DB' 'SC_HOGANHK_DB'
'SC_EURONETID_DB' 'SC_TANDEMTW_DB'));
RUN;

PROC SORT DATA = HR_GLOBAL_MERCHANT_DECLINE_RL NODUPKEY ;BY FI_TRANSACTION_ID; RUN;

PROC SQL;
CREATE TABLE CHK1 AS
SELECT A.*,B.RULE_NAME_STRG AS NEW_RULE_NAME_STRG FROM 
HR_Global_Merchant_MID_RL A LEFT JOIN HR_GLOBAL_MERCHANT_DECLINE_RL B
ON A.FI_TRANSACTION_ID = B.FI_TRANSACTION_ID;
QUIT;


PROC SQL;
CREATE TABLE CHK2 AS
SELECT A.*,B.RULE_NAME_STRG AS NEW_RULE_NAME_STRG FROM 
HR_GLOBAL_MERCHANT_DECLINE_RL A LEFT JOIN HR_Global_Merchant_MID_RL B
ON A.FI_TRANSACTION_ID = B.FI_TRANSACTION_ID;
QUIT;

