
****************************************************
HR_Global_Blacklist_MIDS_Supress HK CREDIT
****************************************************;

LIBNAME INC "C:\Users\1586087\Documents\Daily_datasets\Credit";

DATA FALT002;
SET INC.FALT002_CR_18JUL;
where CRD_CLNT_ID IN ("SC_CCMSHK_CR") and
 TRN_AUTH_POST  = "A" AND
( AUTH_DECISION_XCD  = "A" OR (AUTH_DECISION_XCD = "" AND  DECI_CD_ORIG  = "A")) AND
 TRN_TYP  IN ("C" "M" "P") AND TRN_POS_ENT_CD  IN ("E" "K" "G");
FORMAT TRAN_DATE DATE9.;
TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));

RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC IMPORT DATAFILE='C:\Users\1586087\Desktop\BLACKLISTED_MERCHANTS_HK.XLS'
DBMS = XLS
OUT = BLACKLISTED_MERCHANTS_HK
REPLACE;
RUN;


PROC SQL;
CREATE TABLE MIDS_HOTLIST_CREDIT_Test AS
SELECT A.*, B.NAME, B.VALUE FROM 
(SELECT * FROM FALT002 
WHERE COMPRESS(MER_ID) IN (SELECT DISTINCT NAME FROM BLACKLISTED_MERCHANTS_HK)) AS A
LEFT JOIN 
BLACKLISTED_MERCHANTS_HK AS B ON
COMPRESS(A.MER_ID) = COMPRESS(B.NAME)
WHERE B.NAME NE "" AND COMPRESS(B.VALUE,,"D")="" ;
QUIT;


PROC SORT DATA=MIDS_HOTLIST_CREDIT_Test NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA Blacklisting_ID_Test_RL;
SET INC.FALT003_CR_18JUL;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_BLACKLIST_MIDS_SUPRESS') AND CLIENT_XID IN ("SC_CCMSHK_CR") AND DATE1 GE "18JUL2021"D;
RUN;

 PROC SORT DATA = Blacklisting_ID_Test_RL NODUPKEY ;BY FI_TRANSACTION_ID; RUN;


 PROC FREQ DATA=MIDS_HOTLIST_CREDIT_Test; TITLE "HR_Global_Blacklist_MIDS_Supress_Test SAS"; 
 TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

 PROC FREQ DATA=Blacklisting_ID_Test_RL; TITLE "HR_Global_Blacklist_MIDS_Supress_Test FALCON HITS"; 
 TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

