
**************************************************************************************

				HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\db";

PROC DELETE DATA = BLACKLISTED_MERCHANTS; RUN;

%MACRO HOTLIST(HT);

PROC IMPORT DATAFILE="C:\Users\1510806\Downloads\BLACKLIST&HT..XLS"
OUT=&HT. DBMS=XLS REPLACE;RUN;

PROC APPEND BASE=BLACKLISTED_MERCHANTS DATA=&HT. FORCE;RUN;

%MEND;

%HOTLIST(_MIDS_COUNTRYWISE_DEBIT);
%HOTLIST(_MIDS_BINATTACK_DEBIT);

/*DATA BLACKLISTED_MERCHANTS_DEBIT;*/
/*SET BLACKLISTED_MERCHANTS;*/
/*WHERE FROM NOT IN ("01/04/2019");*/
/*RUN;*/

DATA FALT002;
SET INC.FALT002_DB_23MAY;
WHERE 
(TRN_AUTH_POST = "A" and (AUTH_DECISION_XCD = "A" or ((AUTH_DECISION_XCD)= "" and 
DECI_CD_ORIG = "A")) and
/*and SUBSTR(USR_IND_4,1,2) NE "Y2" */
TRN_POS_ENT_CD NE "V") AND CRD_CLNT_ID NOT IN ("SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETMY_DB" "SC_SPARROWBD_DB" "SC_EURONETID_DB");
COUNTRY = SUBSTR(CRD_CLNT_ID,LENGTH(CRD_CLNT_ID) - 4, 2);
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SQL;
CREATE TABLE MIDS_HOTLIST_DEBIT_Test AS
SELECT A.*, B.Name, B.STATUS, B.VALUE FROM 
(SELECT * FROM FALT002_1 
WHERE COMPRESS(MER_ID) IN (SELECT DISTINCT NAME FROM BLACKLISTED_MERCHANTS)) AS A
LEFT JOIN 
BLACKLISTED_MERCHANTS AS B ON
COMPRESS(A.MER_ID) = COMPRESS(B.NAME)
WHERE B.STATUS NE "" AND INDEX(B.VALUE,STRIP(A.COUNTRY)) AND A.DATE1 GE "23MAY2021"D;
QUIT;

PROC SORT DATA=MIDS_HOTLIST_DEBIT_Test NODUPKEY; BY FI_TRANSACTION_ID; RUN;

     DATA Blacklisting_ID_Test_RL;
     SET INC.falt003_DB_23MAY;
     WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT') AND DATE1 GE "23MAY2021"D AND
	 CLIENT_XID NOT IN ("SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETMY_DB" "SC_SPARROWBD_DB" "SC_EURONETID_DB");
	 RULE_HIT = "Y";
     RUN;

     PROC SORT DATA = Blacklisting_ID_Test_RL NODUPKEY ;BY FI_TRANSACTION_ID; RUN;


     PROC FREQ DATA=MIDS_HOTLIST_DEBIT_Test; TITLE "HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT_Test SAS"; 
     TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

     PROC FREQ DATA=Blacklisting_ID_Test_RL; TITLE "HR_GLOBAL_BLACKLIST_MIDS_HOTLIST_DEBIT_Test FALCON HITS"; 
     TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;



/*CROSS CHECK*/

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT ACCT_NBR, FI_TRANSACTION_ID, Name FROM MIDS_HOTLIST_DEBIT_Test where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
Blacklisting_ID_Test_RL);
QUIT;

/* to check the Name in Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT distinct(Name) FROM MIDS_HOTLIST_DEBIT_Test where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
Blacklisting_ID_Test_RL);
QUIT;


DATA OTHER_RULE;
SET IND.falt003_DB_23MAY;
WHERE FI_TRANSACTION_ID IN 
(
'0160a7a2da04e072'
'0360a7a30202fcc0'
'0360a7a3020330bf'
'0360a7a3020334cc'
'0360a7a3020339c0'
'1f60a7a21e030c1c'
'2060a7a21e0322dd'
'2160a7a24b03234c'
'2160a7a24b0326fa'
'2160a7a24b032706'
'2160a7a24b032b60'
'2160a7a24b033dc1'
'2160a7a24b04ebab'
 /*high priority rule with return triggered*/
);
RUN;

DATA CASACTN;
SET IND.casactn_db_23may
IND.casactn_db_22may;
WHERE ACCT_NBR IN 
(
"4033970101243043"
"4783932798548912"
"4847980000857963"
"4998270400047119"
) and date1 ge "23may2021"d;
RUN;






/*	DATA RL;*/
/*     SET INC.falt003_DB_23MAY;*/
/*	RUN;*/
/**/
/*	 PROC SQL;*/
/*	 CREATE TABLE RULE_HIT AS */
/*	 SELECT DISTINCT * FROM RL WHERE FI_TRANSACTION_ID IN*/
/*	 (SELECT DISTINCT FI_TRANSACTION_ID FROM MIDS_HOTLIST_DEBIT_Test WHERE FI_TRANSACTION_ID NOT IN */
/*	 (SELECT DISTINCT FI_TRANSACTION_ID FROM Blacklisting_ID_Test_RL))*/
/*	 AND UPCASE(RULE_NAME_STRG) = "HR_GLOBAL_BLACKLIST_MIDS_SUPRESS";*/
/*	 QUIT;*/
/**/
/*	 	 PROC SQL;*/
/*	 CREATE TABLE TXN AS */
/*	 SELECT DISTINCT * FROM MIDS_HOTLIST_DEBIT_Test WHERE FI_TRANSACTION_ID NOT IN*/
/*	 (SELECT DISTINCT FI_TRANSACTION_ID FROM RULE_HIT) AND FI_TRANSACTION_ID NOT IN*/
/*	 (SELECT DISTINCT FI_TRANSACTION_ID FROM Blacklisting_ID_Test_RL) ;*/
/*	 QUIT;*/
/**/
/*	 */
/**/
/*	 DATA CASACTN;*/
/*	 SET INC.CASACTN_IN_DB_JAN2019*/
/*		 INC.CASACTN_SG_DB_JAN2019;*/
/*	 WHERE STRIP(ACCT_NBR) IN */
/*	('4585460006434907'*/
/*	'4987590000771716'*/
/*	'5523527020931886') AND DATE1 GE "25JAN2018"D;*/
/*	 RUN;*/