

**************************************************************************************

				HR_Global_CRYPTO_Merchants3 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS3';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"BTCXINDIA") OR
INDEX(UPCASE(MER_NM),"TUXEXCHANGE") OR
INDEX(UPCASE(MER_NM),"BITSSA") OR
INDEX(UPCASE(MER_NM),"URDUBIT") OR
INDEX(UPCASE(MER_NM),"BITLISH") OR
INDEX(UPCASE(MER_NM),"BITSANE") OR
INDEX(UPCASE(MER_NM),"KIWI-COIN") OR
INDEX(UPCASE(MER_NM),"QRYPTOS") OR
INDEX(UPCASE(MER_NM),"XBITASIA") OR
INDEX(UPCASE(MER_NM),"NZBCX") OR
INDEX(UPCASE(MER_NM),"PAXFUL") OR
INDEX(UPCASE(MER_NM),"SOUTHXCHANGE") OR
INDEX(UPCASE(MER_NM),"OPENLEDGER") OR
INDEX(UPCASE(MER_NM),"CHILEBIT") OR
INDEX(UPCASE(MER_NM),"MONKEYCOIN") OR
INDEX(UPCASE(MER_NM),"FYBSE") OR
INDEX(UPCASE(MER_NM),"ARENABITCOIN") OR
INDEX(UPCASE(MER_NM),"DC-EX") OR
INDEX(UPCASE(MER_NM),"COINGI") OR
INDEX(UPCASE(MER_NM),"HAVELOCKINVESTMENTS") OR
INDEX(UPCASE(MER_NM),"GUARANIBITCOIN") OR
INDEX(UPCASE(MER_NM),"SURBITCOIN") OR
INDEX(UPCASE(MER_NM),"ZYADO") OR
INDEX(UPCASE(MER_NM),"WALLTIME") OR
INDEX(UPCASE(MER_NM),"USECRYPTOS") OR
INDEX(UPCASE(MER_NM),"POSWALLET") OR
INDEX(UPCASE(MER_NM),"OKEX") OR
INDEX(UPCASE(MER_NM),"NLEXCH") OR
INDEX(UPCASE(MER_NM),"MEGACRYPTON") OR
INDEX(UPCASE(MER_NM),"LZF") OR
INDEX(UPCASE(MER_NM),"LITEBIT") OR
INDEX(UPCASE(MER_NM),"GOCIO") OR
INDEX(UPCASE(MER_NM),"DWVX") OR
INDEX(UPCASE(MER_NM),"COIN LOFT") OR
INDEX(UPCASE(MER_NM),"CRYPTXC") OR
INDEX(UPCASE(MER_NM),"CRYPTOPAY") OR
INDEX(UPCASE(MER_NM),"CRIPTOCAMBIO") OR
INDEX(UPCASE(MER_NM),"COINPIT") OR
INDEX(UPCASE(MER_NM),"BTCBOX") OR
INDEX(UPCASE(MER_NM),"BRIGHTONPEAK") OR
INDEX(UPCASE(MER_NM),"BITNOW") OR
INDEX(UPCASE(MER_NM),"BITBOL") OR
INDEX(UPCASE(MER_NM),"247EXCHANGE") OR
INDEX(UPCASE(MER_NM),"ETHERDELTA") OR
INDEX(UPCASE(MER_NM),"ELECTROCOIN") OR
INDEX(UPCASE(MER_NM),"CHBTC") OR
INDEX(UPCASE(MER_NM),"BTER") OR
INDEX(UPCASE(MER_NM),"VIABTC") OR
INDEX(UPCASE(MER_NM),"YUNBI") OR
INDEX(UPCASE(MER_NM),"COINSPOT") OR
INDEX(UPCASE(MER_NM),"NXT MONETARY SYSTEM")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS3 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS3;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;