
*************************************************************

			HR_Global_Debit_Blacklist_MID Global Debit

**************************************************************;

LIBNAME IND "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";

PROC IMPORT DATAFILE="C:\Users\1510806\Downloads\BLACKLISTED_MERCHANTS_DEBIT_1.XLS"
OUT=BLACKLISTED_MERCHANTS_DEBIT1 DBMS=XLS REPLACE;
RUN;
PROC IMPORT DATAFILE="C:\Users\1510806\Downloads\BLACKLISTED_MERCHANTS_DEBIT_2.XLS"
OUT=BLACKLISTED_MERCHANTS_DEBIT2 DBMS=XLS REPLACE;
RUN;

DATA BLACKLISTED_MERCHANTS_DEBIT;
SET BLACKLISTED_MERCHANTS_DEBIT1 BLACKLISTED_MERCHANTS_DEBIT2;
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = MDY(SUBSTR(Last_Updated,1,2),SUBSTR(Last_Updated,4,2),SUBSTR(Last_Updated,7,4));
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(Last_Updated,12,2),SUBSTR(Last_Updated,15,2),SUBSTR(Last_Updated,18,2)); 
RUN; 

DATA FALT002;
     SET IND.falt002_DB_23MAY ;
     WHERE (CRD_CLNT_ID NOT IN ("SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_SPARROWBD_DB") AND TRN_AUTH_POST = "A" AND  
     (AUTH_DECISION_XCD = "A" OR (AUTH_DECISION_XCD = "" AND DECI_CD_ORIG = "A")) AND TRN_TYP IN ("C"  "M"  "P"  "A")) AND 
     TRN_POS_ENT_CD NE "V";
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
	 IF CRD_CLNT_ID NE "SC_EURONETMY_DB" THEN COUNTRY = "RAC_INDIA";
	 ELSE COUNTRY = "RAC_SG";
RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SQL;
CREATE TABLE Debit_Blacklist_MID_Test AS
SELECT A.NAME, A.FROM, A.AUTH_DTTM AS AUTH_DTTM1, A.*, B.* FROM BLACKLISTED_MERCHANTS_DEBIT AS A
LEFT JOIN 
FALT002_1 AS B
/*ON STRIP(A.COUNTRY) = STRIP(B.COUNTRY) AND*/
/*STRIP(A.NAME) = STRIP(B.MER_ID)*/
/*WHERE A.AUTH_DTTM LE B.AUTH_DTTM;*/
ON STRIP(A.NAME) = STRIP(B.MER_ID);
QUIT;

PROC SORT DATA=Debit_Blacklist_MID_Test NODUPKEY; BY FI_TRANSACTION_ID; RUN;

     DATA Blacklisting_ID_Test_RL;
     SET IND.falt003_DB_23MAY ;
     WHERE UPCASE(RULE_NAME_STRG) IN ('HR_GLOBAL_DEBIT_BLACKLIST_MID') AND 
	 (CLIENT_XID NOT IN ("SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_SPARROWBD_DB")) AND
	 DATE1 GE "23MAY2021"D;
     RUN;

     PROC SORT DATA = Blacklisting_ID_Test_RL NODUPKEY ;BY FI_TRANSACTION_ID; RUN;


     PROC FREQ DATA=Debit_Blacklist_MID_Test; TITLE "HR_Global_Debit_Blacklist_MID_Test SAS"; 
     TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

     PROC FREQ DATA=Blacklisting_ID_Test_RL; TITLE "HR_Global_Debit_Blacklist_MID_Test FALCON HITS"; 
     TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;



/*CROSS CHECK*/


/* Check the "Name" column in the output with the name column in VIP genuine - if it matches then VIP/Geuine list issue*/

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT ACCT_NBR, FI_TRANSACTION_ID, * FROM Debit_Blacklist_MID_Test where FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
Blacklisting_ID_Test_RL);
QUIT;

DATA OTHER_RULE;
SET IND.falt003_DB_23MAY;
WHERE FI_TRANSACTION_ID IN 
(
'0060a7a2da030ada'
'1f60a7a21e048b4b' /*high priority rule with return triggered*/
);
RUN;

DATA CASACTN;
SET IND.casactn_db_23may
IND.casactn_db_22may;
WHERE ACCT_NBR IN ("5243573000176612" "4455980205066397") and date1 ge "23may2021"d;
RUN;

PROC SQL;
CREATE TABLE NOT_TRIGGERED AS 
SELECT * FROM Debit_Blacklist_MID_Test AS A
LEFT JOIN Blacklisting_ID_Test_RL AS B
ON A.FI_TRANSACTION_ID = B.FI_TRANSACTION_ID;
QUIT;

PROC SQL;
CREATE TABLE TRIGGERED AS 
SELECT * FROM Blacklisting_ID_Test_RL AS A
LEFT JOIN Debit_Blacklist_MID_Test AS B
ON A.FI_TRANSACTION_ID = B.FI_TRANSACTION_ID;
QUIT;

DATA CASACTN;
SET IND.casactn_db_23may
IND.casactn_db_22may;
WHERE ACCT_NBR IN ("5243573000176612") and date1 ge "22may2021"d;
RUN;

data chk;
set iND.falt002_DB_30OCT;
where fi_transaction_id = "035db71246044680";
run;

data chk1;
set iND.falt003_DB_30OCT;
where fi_transaction_id = "035db71246044680";
run;