

**************************************************************************************

				HR_Global_CRYPTO_Merchants9

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

DATA FALT003_1;
     SET INC.falt003_cr_23MAY
INC.falt003_cr_24MAY;
WHERE DATE1 GE "23MAY2021"D AND UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS9' AND
SUBSTR(STRIP(CLIENT_XID),4,3) NOT IN ("PMT");
IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) NOT IN ("HK" "TW" "BD") THEN TENANT = "Global"; 
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("HK") THEN TENANT = "HK";
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("TW") THEN TENANT = "TW";
ELSE IF SUBSTR(STRIP(CLIENT_XID),LENGTH(STRIP(CLIENT_XID))-4, 2) IN ("BD") THEN TENANT = "BD";
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
     SET INC.falt002_cr_23MAY
INC.falt002_cr_24MAY;
WHERE 
DATE1 GE "23MAY2021"D AND 
TRN_AUTH_POST = "A" AND
(AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG = "A") AND
SIC_CD = "6051"	AND
(
	INDEX(UPCASE(MER_NM),"SPECTROCOIN.COM" ) OR
	INDEX(UPCASE(MER_NM),"STOCKS.EXCHANGE" ) OR
	INDEX(UPCASE(MER_NM),"TIDEBIT" ) OR
	INDEX(UPCASE(MER_NM),"TRADEOGRE" ) OR
	INDEX(UPCASE(MER_NM),"UNOCOIN" ) OR
	INDEX(UPCASE(MER_NM),"UPHOLD.COM" ) OR
	INDEX(UPCASE(MER_NM),"VAULTORO " ) OR
	INDEX(UPCASE(MER_NM),"WALLOF COINS" ) OR
	INDEX(UPCASE(MER_NM),"WANKEBI" ) OR
	INDEX(UPCASE(MER_NM),"WORLD EXCHANGE SERVIES (WEX)" ) OR
	INDEX(UPCASE(MER_NM),"WWW.BITIT.IO" ) OR
	INDEX(UPCASE(MER_NM),"XCOINS" ) OR
	INDEX(UPCASE(MER_NM),"YAPIZON" ) OR
	INDEX(UPCASE(MER_NM),"YOBIT.NET" ) OR
	INDEX(UPCASE(MER_NM),"YOUBIT" ) OR 
	INDEX(UPCASE(MER_NM),"IVMC" ) OR 
	INDEX(UPCASE(MER_NM),"BITCOINS NORWAY" ) OR 
	INDEX(UPCASE(MER_NM),"BITKONAN" ) OR 
	INDEX(UPCASE(MER_NM),"ICE3X" ) OR 
 	INDEX(UPCASE(MER_NM),"ASKCOIN" ) OR
	INDEX(UPCASE(MER_NM),"PAYBIS-SIMPLEX" ) OR
	INDEX(UPCASE(MER_NM),"PSP*KOINAL" ) OR
	INDEX(UPCASE(MER_NM),"MCO" ) OR 
 	INDEX(UPCASE(MER_NM),"MOONPAY" ) OR
	INDEX(UPCASE(MER_NM),"IEXPAY.NET" ) OR
	INDEX(UPCASE(MER_NM),"SWITCHERE.COM" ) OR
	INDEX(UPCASE(MER_NM),"BUY DIGITAL ASSET" ) OR
	INDEX(UPCASE(MER_NM),"WISENEX.COM" ) OR
	INDEX(UPCASE(MER_NM),"CONGEE.IO" ) OR
	INDEX(UPCASE(MER_NM),"MERCURYO" ) OR
	INDEX(UPCASE(MER_NM),"SIMPLEX" ) OR
	INDEX(UPCASE(MER_NM),"PAYBIS" ) OR
	INDEX(UPCASE(MER_NM),"N.EXCHANGE" ) OR
	INDEX(UPCASE(MER_NM),"WYRE" ) OR
	INDEX(UPCASE(MER_NM),"QUICKBIT.COM" )OR
	INDEX(UPCASE(MER_NM),"CRO" )OR
	INDEX(UPCASE(MER_NM),"CRYPTO.COM" ) OR
	INDEX(UPCASE(MER_NM),"UNIMAL LTD" )OR
	INDEX(UPCASE(MER_NM),"MOON PAY" )
) AND 
SUBSTR(STRIP(CRD_CLNT_ID),4,3) NOT IN ("PMT");

IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) NOT IN ("HK" "TW" "BD") THEN TENANT = "Global"; 
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("HK") THEN TENANT = "HK";
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("TW") THEN TENANT = "TW";
ELSE IF SUBSTR(STRIP(CRD_CLNT_ID),LENGTH(STRIP(CRD_CLNT_ID))-4, 2) IN ("BD") THEN TENANT = "BD";
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS9 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS9;
TABLES TENANT*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES TENANT*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;


/*PROC SQL;*/
/*CREATE TABLE CHK AS */
/*SELECT * FROM INC.falt003_cr_09MAY WHERE FI_TRANSACTION_ID IN*/
/*(SELECT DISTINCT FI_TRANSACTION_ID FROM HR_GLOBAL_CRYPTO_MERCHANTS9 WHERE UPCASE(DECI_CD) EQ "DECLINE" AND INDEX(CRD_CLNT_ID,"HK"));*/
/*QUIT;*/
/**/
/**/
/*DATA CHK_TXN;*/
/*SET INC.falt002_cr_09MAY;*/
/*WHERE FI_TRANSACTION_ID IN */
/*('006094fcd4066a07'*/
/*'006094fcd4066a5a');*/
/*RUN;*/