

**************************************************************************************

				HR_Global_CRYPTO_Merchants9 Global Credit

**************************************************************************************;

LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";



DATA FALT003_1;
SET  
/*INC.falt003_cr_02jun*/
/*INC.falt003_cr_01jun;*/
INC.falt003_cr_05jun
INC.falt003_cr_06jun;

WHERE DATE1 GE "06JUN2021"D AND CLIENT_XID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND 
UPCASE(RULE_NAME_STRG) = 'HR_GLOBAL_CRYPTO_MERCHANTS9';
RUN;

PROC SORT DATA=FALT003_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002_1;
SET 
/*INC.falt002_cr_02jun*/
/*INC.falt002_cr_01jun;*/
INC.falt002_cr_05jun
INC.falt002_cr_06jun;
WHERE 
(
 DATE1 GE "06JUN2021"D AND 
 TRN_AUTH_POST  = "A" AND
( AUTH_DECISION_XCD  = "A" OR  DECI_CD_ORIG  = "A") AND
 CRD_CLNT_ID  NE "SC_C400JE_CR" AND
 SIC_CD = "6051" AND
 CRD_CLNT_ID NOT IN ("SC_CCMSHK_CR" "SC_CCMSTW_CR" "SC_CCMSMY_CR" "SC_C400BD_CR") AND
(
INDEX(UPCASE(MER_NM),"SPECTROCOIN.COM") OR
INDEX(UPCASE(MER_NM),"STOCKS.EXCHANGE") OR
INDEX(UPCASE(MER_NM),"TIDEBIT") OR
INDEX(UPCASE(MER_NM),"TRADEOGRE") OR
INDEX(UPCASE(MER_NM),"UNOCOIN") OR
INDEX(UPCASE(MER_NM),"UPHOLD.COM") OR
INDEX(UPCASE(MER_NM),"VAULTORO ") OR
INDEX(UPCASE(MER_NM),"WALLOF COINS") OR
INDEX(UPCASE(MER_NM),"WANKEBI") OR
INDEX(UPCASE(MER_NM),"WORLD EXCHANGE SERVIES (WEX)") OR
INDEX(UPCASE(MER_NM),"WWW.BITIT.IO") OR
INDEX(UPCASE(MER_NM),"XCOINS") OR
INDEX(UPCASE(MER_NM),"YAPIZON") OR
INDEX(UPCASE(MER_NM),"YOBIT.NET") OR
INDEX(UPCASE(MER_NM),"YOUBIT") OR
INDEX(UPCASE(MER_NM),"IVMC") OR
INDEX(UPCASE(MER_NM),"BITCOINS NORWAY") OR
INDEX(UPCASE(MER_NM),"BITKONAN") OR
INDEX(UPCASE(MER_NM),"ICE3X") OR
INDEX(UPCASE(MER_NM),"ASKCOIN") OR
INDEX(UPCASE(MER_NM),"PAYBIS-SIMPLEX") OR
INDEX(UPCASE(MER_NM),"PSP*KOINAL") OR
INDEX(UPCASE(MER_NM),"MCO") OR
INDEX(UPCASE(MER_NM),"MOONPAY") OR
INDEX(UPCASE(MER_NM),"IEXPAY.NET") OR
INDEX(UPCASE(MER_NM),"SWITCHERE.COM") OR
INDEX(UPCASE(MER_NM),"BUY DIGITAL ASSET") OR
INDEX(UPCASE(MER_NM),"WISENEX.COM") OR
INDEX(UPCASE(MER_NM),"CONGEE.IO") OR
INDEX(UPCASE(MER_NM),"MERCURYO") OR
INDEX(UPCASE(MER_NM),"SIMPLEX") OR
INDEX(UPCASE(MER_NM),"PAYBIS") OR
INDEX(UPCASE(MER_NM),"N.EXCHANGE") OR
INDEX(UPCASE(MER_NM),"WYRE") OR
INDEX(UPCASE(MER_NM),"QUICKBIT.COM") OR
INDEX(UPCASE(MER_NM),"CRO") OR
INDEX(UPCASE(MER_NM),"CRYPTO.COM") OR
INDEX(UPCASE(MER_NM),"UNIMAL LTD") OR
INDEX(UPCASE(MER_NM),"MOON PAY")
)
);
RUN;

PROC SORT DATA=FALT002_1 OUT=HR_GLOBAL_CRYPTO_MERCHANTS9 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA= HR_GLOBAL_CRYPTO_MERCHANTS9;
TABLES CRD_CLNT_ID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;

PROC FREQ DATA= FALT003_1;
TABLES CLIENT_XID*DATE1/NOCOL NOCUM NOPERCENT NOROW;RUN;