
			*******************************************************************
					 HR_MID_Amount_NonMajor_Test Global Debit

			*******************************************************************;

LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Nov21_Major\MAJOR_COUNTRIES_DATA";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\DB";

DATA  FALT002;
SET 
INC.falt002_db_03dec
INC.falt002_db_04dec;   

WHERE  CRD_CLNT_ID NOT IN ("SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_SPARROWBD_DB" "SC_EURONETAE_DB"
"SC_EURONETIN_DB" "SC_EURONETSG_DB" "SC_EURONETMY_DB") and 
TRN_AUTH_POST = "A" and AUTH_DECISION_XCD = "A" and TRN_TYP IN  ("C" "M" "P");
FORMAT TRAN_DATE DATE9.;
 TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
 ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
 AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
 MCC = INPUT(SIC_CD,BEST.);

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/3.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;

RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_1 OUT=FALT002_2 ; BY ACCT_NBR AUTH_DTTM; RUN;


DATA HR_MID_Amount_NonMajor_TestSAS;
SET FALT002_2;
IF
(
(
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 TRN_TYP  IN ("C" "M" "P")
)
and
(
(
 CRD_CLNT_ID  = "SC_SPARROWKE_DB" AND
(
(COMPRESS(MER_ID) = "KA2DJIBSBZMSEA9" AND  USD  >= 40) OR
(COMPRESS(MER_ID) = "100000000007434" AND  USD  >= 10)
)
)

OR(  CRD_CLNT_ID  NOT IN ("SC_EURONETIN_DB" "SC_EURONETMY_DB" "SC_EURONETSG_DB" "SC_EURONETAE_DB") AND
(
(COMPRESS(MER_ID) = "145456887" AND  USD  >= 40) OR
(COMPRESS(MER_ID) = "24633695" AND  USD  >= 40) OR
(COMPRESS(MER_ID) = "4556359848" AND  USD  >= 20) OR
(COMPRESS(MER_ID) = "4556487655" AND  USD  >= 45) OR
(COMPRESS(MER_ID) = "24633695" AND  FRD_SCOR  > 300) OR
(COMPRESS(MER_ID) = "000174241204992" AND  USD  > 40)
)
)

OR(
 CRD_CLNT_ID  = "SC_EURONETBH_DB" AND
(
(COMPRESS(MER_ID) = "000445120538993" AND SIC_CD IN ("5399" "5691")) OR
(COMPRESS(MER_ID) = "475700000000001" AND  FRD_SCOR  > 800)
)
)

OR(
 CRD_CLNT_ID  = "SC_SPARROWGH_DB" AND
(
(COMPRESS(MER_ID) = "29851415" AND
SIC_CD IN ("5817" "7399") AND
 USD  >= 75) OR
(COMPRESS(MER_ID) = "010096327")
)
)

OR(
 CRD_CLNT_ID  = "SC_SPARROWZM_DB" AND
(
(COMPRESS(MER_ID) = "0027953" AND  USD  >= 50) OR
(COMPRESS(MER_ID) = "000445120538993" AND  FRD_SCOR  > 955) OR
(COMPRESS(MER_ID) = "3057FL9O000009O" AND  TRN_AMT  > 0)
)
)

OR
(
 CRD_CLNT_ID  = "SC_SPARROWBW_DB" AND
(
(COMPRESS(MER_ID) = "401655000398455" AND  FRD_SCOR  > 200)
)
)
)
)
THEN HR_MID_Amount_NonMajor_Test = "Y";
RUN;

DATA TXN_DATA;
SET HR_MID_Amount_NonMajor_TestSAS;
WHERE HR_MID_Amount_NonMajor_Test = "Y" and date1 GE "02DEC2021"D;
RUN;


DATA RULE_DATA;
SET 
INC.falt003_db_02dec
INC.falt003_db_03dec;
WHERE UPCASE(RULE_NAME_STRG) IN ('HR_MID_AMOUNT_NONMAJOR_TEST') and date1 GE "02DEC2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "HR_MID_Amount_NonMajor_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA=RULE_DATA; TITLE "HR_MID_Amount_NonMajor_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_MID_Amount_NonMajor_Test Global Debit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
 PROC FREQ DATA = TXN_DATA;TITLE "HR_MID_Amount_NonMajor_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "HR_MID_Amount_NonMajor_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_MID_Amount_NonMajor_Test Global Debit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\HR_MID_Amount_NonMajor_Test Global Debit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;
