
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Jul21";
LIBNAME DL "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";
/*LIBNAME EXIST "C:\Users\1586087\Documents\Monthly datasets";*/
LIBNAME EXIST "Z:\Falcon 6.4 data download\FRD15";
options compress=yes MPRINT MLOGIC SYMBOLGEN;

*********************************************************;

PROC DELETE DATA=FALT002_2; RUN;


/*%MACRO DEC(CNTY);*/

DATA FALT002;
     SET  INC.last_3_months_data_db
DL.falt002_db_21jul
DL.falt002_db_20jul;
/*INC.falt002_&cnty._DB_may2021*/
/*INC.falt002_&cnty._DB_JUN2021 INC.falt002_&cnty._DB_JUL2021;*/
     WHERE CRD_CLNT_ID = "SC_TANDEMTW_DB" AND TRN_AUTH_POST = "A" ;
	ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));
	 USD=TRN_AMT/30.116853;

     IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN DO;
     A1=SUBSTR(ACCT_NBR,1,6);
     B1=SUBSTR(ACCT_NBR,1,5);
     C1=SUBSTR(ACCT_NBR,7);
     D1=SUBSTR(ACCT_NBR,6);
     E1=SUBSTR(C1,1,1);
     IF E1>2 THEN F1=0;ELSE F1=1;
     IF F1=1 THEN G1=(COMPRESS(1||C1)-3322114488);ELSE G1=C1-3322114488;
     ORG_ACCT_NBR=COMPRESS(A1||SUBSTR(G1,LENGTH(G1)-9));
     IF LENGTH(ORG_ACCT_NBR)=15 THEN ORG_ACCT_NBR=STRIP(SUBSTR(ORG_ACCT_NBR,1,6))||"0"||STRIP(SUBSTR(ORG_ACCT_NBR,7));
     ELSE IF LENGTH(ORG_ACCT_NBR)=14 THEN ORG_ACCT_NBR=STRIP(SUBSTR(ORG_ACCT_NBR,1,6))||"00"||STRIP(SUBSTR(ORG_ACCT_NBR,7));
     ELSE IF LENGTH(ORG_ACCT_NBR)=13 THEN ORG_ACCT_NBR=STRIP(SUBSTR(ORG_ACCT_NBR,1,6))||"000"||STRIP(SUBSTR(ORG_ACCT_NBR,7));
     ELSE IF LENGTH(ORG_ACCT_NBR)=12 THEN ORG_ACCT_NBR=STRIP(SUBSTR(ORG_ACCT_NBR,1,6))||"0000"||STRIP(SUBSTR(ORG_ACCT_NBR,7));
     DROP A1 B1 C1 D1 E1 F1 G1;
     END;
     ELSE ORG_ACCT_NBR = ACCT_NBR;


IF 

ORG_ACCT_NBR in  
(
'4377226221769704'
'4377226223031988'
'4377226222899591'
'4377226221324567'
'4377226222864462'
'4377226223041698'
'4377226221667197'
);

/*		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'*/
/*								'421451'*/
/*								'469626'*/
/*								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;*/
/*	ELSE TRN_AMT_LOCAL = TRN_AMT;*/
/**/
/*		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;*/
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/4.221743;*/
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;*/
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/63.75;*/
/*		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; */
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; */
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; */
/*		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; */
/*		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; */
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; */
/*		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;*/
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;*/
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;*/
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;*/
/*		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;*/

RUN;

PROC SORT DATA=FALT002 OUT =  FALT002_2 ; BY ORG_ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=FALT002_2 NODUPKEY; BY ORG_ACCT_NBR FI_TRANSACTION_ID; RUN;


PROC SORT DATA=EXIST.FRD15 OUT=FRD_TW NODUPKEY; 
     WHERE STRIP(SUBSTR(CLIENTIDFROMHEADER,LENGTH(CLIENTIDFROMHEADER)-4))="TW_DB"; 
     BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SQL;
CREATE TABLE TXN_DETAILS AS
           SELECT A.*,
             B.FRAUDFLAG,
             CASE 
                WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" THEN 1 

				when A.ORG_ACCT_NBR in 
(
'4377226221769704'
'4377226223031988'
'4377226222899591'
'4377226221324567'
'4377226222864462'
'4377226223041698'
'4377226221667197')
 THEN 1

             END AS FRAUD
FROM FALT002_2 AS A LEFT JOIN FRD_TW AS B ON 
A.ACCT_NBR = B.PAN AND
A.FI_TRANSACTION_ID=B.FITRANSACTIONIDREFERENCE;
QUIT;

PROC APPEND DATA=TXN_DETAILS BASE=FALT002_2 FORCE; RUN;


/*PROC SORT DATA=EXIST.FRD15 OUT=FRD_&CNTY. NODUPKEY; */
/*     WHERE STRIP(SUBSTR(CLIENTIDFROMHEADER,LENGTH(CLIENTIDFROMHEADER)-4))="&CNTY._DB"; */
/*     BY PAN FITRANSACTIONIDREFERENCE; */
/*RUN;*/
/**/
/*PROC SQL;*/
/*CREATE TABLE TXN_DETAILS AS*/
/*           SELECT A.*,*/
/*             B.FRAUDFLAG,*/
/*             CASE */
/*                WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1"  THEN 1*/
/*             END AS FRAUD*/
/*FROM FALT002 AS A LEFT JOIN FRD_&CNTY. AS B ON */
/*A.ACCT_NBR = B.PAN AND*/
/*A.FI_TRANSACTION_ID=B.FITRANSACTIONIDREFERENCE*/
/*WHERE*/
/*ORG_ACCT_NBR in */
/*(*/
/*'4377226221769704'*/
/*'4377226223031988'*/
/*'4377226222899591'*/
/*'4377226221324567'*/
/*'4377226222864462'*/
/*'4377226223041698'*/
/*'4377226221667197'*/
/*);*/
/*QUIT;*/
/**/
/*PROC APPEND DATA=TXN_DETAILS BASE=FALT002_2 FORCE; RUN;*/
/*PROC DELETE DATA=FRD_&CNTY.; RUN;*/
/**/
/*%MEND;*/
/**/
/**/
/*%DEC(TW);*/

PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;
PROC SORT DATA=FALT002_2 ; BY ORG_ACCT_NBR AUTH_DTTM;RUN;


%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ORG_ACCT_NBR AUTH_DTTM;

     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ORG_ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + (TRN_AMT);
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = (TRN_AMT);
           END;
     END;


RUN;
%MEND; 

%UDV(CUM_INTERVAL        = 1800,                                          
     CUMULATIVE_CONDITION= %STR(CRD_CLNT_ID = "SC_TANDEMTW_DB" AND TRN_AUTH_POST = "A" and AUTH_DECISION_XCD = "A" and TRN_TYP IN ("C" "M" "P") and
TRN_POS_ENT_CD IN ("E" "K" "G") and TRN_AMT > 0),
     VAR_NAME            = CNP_30MIN);

/*DATA CHK;*/
/*SET FALT002_2;*/
/*WHERE MER_ID="020355198";*/
/*RUN;*/


PROC DELETE DATA=IMPACT_SUMMARY;RUN;

%MACRO ABC();

%DO CNT= 0 %TO 5;
%DO AMT= 0 %TO 1000 %BY 100;

PROC SQL;
CREATE TABLE XX AS 
SELECT DISTINCT 
           "CUM_COUNT_CNP_30MIN >= &CNT. AND CUM_AMOUNT_CNP_30MIN >= &AMT.                 " AS RULE, 
           COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
           COUNT(DISTINCT ORG_ACCT_NBR) AS ACCT_COUNT, 
           SUM(FRAUD) AS NO_OF_FRAUDS,
		   SUM(CASE WHEN FRAUD=1 THEN USD END) AS FRAUD_USD,
           COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ORG_ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
           CASE 
            WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
           ELSE CALCULATED TXN_COUNT
           END AS TFPR,
           CASE 
            WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
           ELSE CALCULATED ACCT_COUNT
           END AS AFPR,
           ROUND(CALCULATED ACCT_COUNT/120,1) AS IMPACT_PER_DAY
FROM FALT002_2
WHERE (TRN_AUTH_POST = "A" and (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") and
TRN_TYP IN ("C" "M" "P")  AND TRN_POS_ENT_CD IN ("E" "K" "G" "") AND 
COMPRESS(MER_ID)="020355198" AND 
CUM_COUNT_CNP_30MIN >= &CNT. AND CUM_AMOUNT_CNP_30MIN >= &AMT.) AND
CRD_CLNT_ID = "SC_TANDEMTW_DB" AND
ORG_ACCT_NBR in  
(
'4377226221769704'
'4377226223031988'
'4377226222899591'
'4377226221324567'
'4377226222864462'
'4377226223041698'
'4377226221667197'
);
QUIT;

PROC APPEND DATA=XX BASE=IMPACT_SUMMARY FORCE;RUN;

%END;
%END;

%MEND;

%ABC();