
/*local & international for credit and debit*/


/*debit international*/

	    (CRD_CLNT_ID = "SC_EURONETAE_DB" AND MER_CNTY_CD  NOT IN ("784") )  OR 
        (CRD_CLNT_ID = "SC_EURONETBH_DB" AND MER_CNTY_CD  NOT IN ("048") )  OR
        (CRD_CLNT_ID = "SC_EURONETBN_DB" AND MER_CNTY_CD  NOT IN ("096") )  OR
        (CRD_CLNT_ID = "SC_SPARROWBW_DB" AND MER_CNTY_CD  NOT IN ("072") )  OR
        (CRD_CLNT_ID = "SC_SPARROWGH_DB" AND MER_CNTY_CD  NOT IN ("288") )  OR
        (CRD_CLNT_ID = "SC_SPARROWCI_DB" AND MER_CNTY_CD  NOT IN ("384") )  OR
        (CRD_CLNT_ID = "SC_EURONETIN_DB" AND MER_CNTY_CD  NOT IN ("356") )  OR
        (CRD_CLNT_ID = "SC_SPARROWSL_DB" AND MER_CNTY_CD  NOT IN ("694") )  OR
        (CRD_CLNT_ID = "SC_SPARROWJO_DB" AND MER_CNTY_CD  NOT IN ("400") )  OR
        (CRD_CLNT_ID = "SC_SPARROWKE_DB" AND MER_CNTY_CD  NOT IN ("404") )  OR
        (CRD_CLNT_ID = "SC_SPARROWLK_DB" AND MER_CNTY_CD  NOT IN ("144") )  OR
        (CRD_CLNT_ID = "SC_SPARROWNG_DB" AND MER_CNTY_CD  NOT IN ("566") )  OR
        (CRD_CLNT_ID = "SC_EURONETMY_DB" AND MER_CNTY_CD  NOT IN ("458") )  OR
        (CRD_CLNT_ID = "SC_SPARROWZM_DB" AND MER_CNTY_CD  NOT IN ("894") )  OR
        (CRD_CLNT_ID = "SC_SPARROWNP_DB" AND MER_CNTY_CD  NOT IN ("524") )  OR
        (CRD_CLNT_ID = "SC_EURONETSG_DB" AND MER_CNTY_CD  NOT IN ("702") )  OR
        (CRD_CLNT_ID = "SC_EURONETVN_DB" AND MER_CNTY_CD  NOT IN ("704") )  OR
        (CRD_CLNT_ID = "SC_SPARROWCM_DB" AND MER_CNTY_CD  NOT IN ("120") )  OR
        (CRD_CLNT_ID = "SC_SPARROWTZ_DB" AND MER_CNTY_CD  NOT IN ("834") )  OR
        (CRD_CLNT_ID = "SC_SPARROWUG_DB" AND MER_CNTY_CD  NOT IN ("800") )  OR
        (CRD_CLNT_ID = "SC_EURONETQA_DB" AND MER_CNTY_CD  NOT IN ("634") )  OR
        (CRD_CLNT_ID = "SC_SPARROWZW_DB" AND MER_CNTY_CD  NOT IN ("716") )  OR
        (CRD_CLNT_ID = "SC_SPARROWGM_DB" AND MER_CNTY_CD  NOT IN ("270") )  OR
        (CRD_CLNT_ID = "SC_SPARROWBD_DB" AND MER_CNTY_CD  NOT IN ("050") )  OR
        (CRD_CLNT_ID = "SC_EURONETID_DB" AND MER_CNTY_CD  NOT IN ("360") )  OR
        (CRD_CLNT_ID = "SC_TANDEMTW_DB" AND MER_CNTY_CD  NOT IN ("158") )  OR
        (CRD_CLNT_ID = "SC_HOGANHK_DB" AND MER_CNTY_CD  NOT IN ("344") )



/*credit international*/

			((CRD_CLNT_ID = "SC_C400AE_CR" and MER_CNTY_CD NE "784" ) or
			(CRD_CLNT_ID = "SC_C400BH_CR" and MER_CNTY_CD NE "048" ) or 
			(CRD_CLNT_ID = "SC_C400BD_CR" and MER_CNTY_CD NE "050" ) or 
			(CRD_CLNT_ID = "SC_CCMSBN_CR" and MER_CNTY_CD NE "096" ) or
			(CRD_CLNT_ID = "SC_CCMSHK_CR" and MER_CNTY_CD NE "344" ) or
			(CRD_CLNT_ID = "SC_CCMSTW_CR" and MER_CNTY_CD NE "158" ) or
			(CRD_CLNT_ID = "SC_C400BW_CR" and MER_CNTY_CD NE "072" ) or
			(CRD_CLNT_ID = "SC_C400GH_CR" and MER_CNTY_CD NE "288" ) or
			(CRD_CLNT_ID = "SC_CCMSID_CR" and MER_CNTY_CD NE "360" ) or
			(CRD_CLNT_ID = "SC_CCMSIN_CR" and MER_CNTY_CD NE "356" ) or
			(CRD_CLNT_ID = "SC_C400JE_CR" and MER_CNTY_CD NE "832" ) or
			(CRD_CLNT_ID = "SC_C400JO_CR" and MER_CNTY_CD NE "400" ) or
			(CRD_CLNT_ID = "SC_C400KE_CR" and MER_CNTY_CD NE "404" ) or
			(CRD_CLNT_ID = "SC_C400LK_CR" and MER_CNTY_CD NE "144" ) or
			(CRD_CLNT_ID = "SC_CCMSMY_CR" and MER_CNTY_CD NE "458" ) or
			(CRD_CLNT_ID = "SC_C400NG_CR" and MER_CNTY_CD NE "566" ) or
			(CRD_CLNT_ID = "SC_C400NP_CR" and MER_CNTY_CD NE "524" ) or
			(CRD_CLNT_ID = "SC_CCMSSG_CR" and MER_CNTY_CD NE "702" ) or
			(CRD_CLNT_ID = "SC_C400VN_CR" and MER_CNTY_CD NE "704" ) or
			(CRD_CLNT_ID = "SC_C400ZM_CR" and MER_CNTY_CD NE "894" ))