
**************************************************************************************

                  Dispute MID Analysis

**************************************************************************************;

LIBNAME INC "C:\Users\1549580\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";
LIBNAME EXIST "C:\Users\1549580\Desktop\Jhilam\Falcon 6.4 Monthly Data";


OPTIONS COMPRESS=YES;

PROC DELETE DATA=FALT002; RUN;

%MACRO COP(CNTY);

DATA  XX;
SET INC.FALT002_&CNTY._CR_SEP2020
	INC.FALT002_&CNTY._CR_OCT2020
	INC.FALT002_&CNTY._CR_NOV2020
	INC.FALT002_&CNTY._CR_DEC2020;
     WHERE  TRN_AUTH_POST = "A" and  AUTH_DECISION_XCD = "A" and TRN_TYP in ("C"  "M"  "P") AND TRN_POS_ENT_CD IN ("E" "K" "G");
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
	 IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;
RUN;

PROC APPEND DATA=XX BASE=FALT002; RUN;

%MEND;

%COP(AE);
%COP(IN);
%COP(MY);
%COP(SG);
%COP(HK);

PROC SORT DATA=FALT002; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=FALT002 NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC SORT DATA=EXIST.FRD15 OUT=FRD_15 NODUPKEY; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_txn dbms=xlsx replace; sheet="txn_id"; run;


PROC SQL;
CREATE TABLE TXN_DETAILS AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" OR D.FI_TRANSACTION_ID NE "" THEN 1 
		  END AS FRAUD
FROM FALT002 AS A LEFT JOIN FRD_15 AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE)
LEFT JOIN Dispute_txn AS D ON
STRIP(A.FI_TRANSACTION_ID) = STRIP(D.FI_TRANSACTION_ID);
QUIT;

PROC SORT DATA=TXN_DETAILS NODUPKEY; BY FI_TRANSACTION_ID; RUN;
PROC SORT DATA=TXN_DETAILS OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;



%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ACCT_NBR AUTH_DTTM;

     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = USD;
           END;
     END;


RUN;
%MEND; 

/*%UDV(CUM_INTERVAL        = 300,                                          */
/*     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K" "G")),*/
/*     VAR_NAME            = 5MINS);*/
/**/
/*%UDV(CUM_INTERVAL        = 1800,                                          */
/*     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K" "G")),*/
/*     VAR_NAME            = 30MINS);*/

/*%UDV(CUM_INTERVAL        = 3600,                                          */
/*     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K" "G")),*/
/*     VAR_NAME            = 60MINS);*/

%UDV(CUM_INTERVAL        = 86400,                                          
     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K" "G")),
     VAR_NAME            = DAILY);





DATA CHK;
SET FALT002_2;
WHERE (INDEX(UPCASE(MER_NM),"MICROSOFT*") OR STRIP(MER_ID) IN ("N5SQYHPHTZA2ZKD" "000453160649993" "42MSP0000004388"))
AND FRAUD = 1;
RUN;


PROC DELETE DATA=Merchant_Analysis; RUN;

%MACRO CR();

%DO CNT = 6 %TO 10;
%DO AMT = 50 %TO 500 %BY 50;

PROC SQL;
CREATE TABLE XX AS 
SELECT DISTINCT CRD_CLNT_ID,
		"N5SQYHPHTZA2ZKD AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.       	                     		       " AS RULE, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/110,1) AS IMPACT_PER_DAY
FROM FALT002_2
WHERE STRIP(MER_ID) = "N5SQYHPHTZA2ZKD" AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.
GROUP BY CRD_CLNT_ID;
QUIT;

PROC APPEND DATA=XX BASE=Merchant_Analysis FORCE; RUN;

%END;
%END;

%MEND;

%CR();


%MACRO CR();

%DO CNT = 1 %TO 10;
%DO AMT = 50 %TO 500 %BY 50;

PROC SQL;
CREATE TABLE XX AS 
SELECT DISTINCT CRD_CLNT_ID,
		"MICROSOFT* AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.                       		       " AS RULE, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/110,1) AS IMPACT_PER_DAY
FROM FALT002_2
WHERE INDEX(UPCASE(MER_NM),"MICROSOFT*") AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.
GROUP BY CRD_CLNT_ID;
QUIT;

PROC APPEND DATA=XX BASE=Merchant_Analysis FORCE; RUN;

%END;
%END;

%MEND;

%CR();

%MACRO CR();

%DO CNT = 1 %TO 10;
%DO AMT = 50 %TO 500 %BY 50;

PROC SQL;
CREATE TABLE XX AS 
SELECT DISTINCT CRD_CLNT_ID,
		"000453160649993 AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.            		       " AS RULE, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/110,1) AS IMPACT_PER_DAY
FROM FALT002_2
WHERE STRIP(MER_ID) = "000453160649993" AND CUM_COUNT_DAILY > &CNT. AND CUM_AMOUNT_DAILY > &AMT.
GROUP BY CRD_CLNT_ID;
QUIT;

PROC APPEND DATA=XX BASE=Merchant_Analysis FORCE; RUN;

%END;
%END;

%MEND;

%CR();


%MACRO CR();

%DO AMT = 50 %TO 500 %BY 50;

PROC SQL;
CREATE TABLE XX AS 
SELECT DISTINCT CRD_CLNT_ID,
		"42MSP0000004388 AND CUM_AMOUNT_DAILY > &AMT.            		       " AS RULE, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/110,1) AS IMPACT_PER_DAY
FROM FALT002_2
WHERE STRIP(MER_ID) = "42MSP0000004388" AND CUM_AMOUNT_DAILY > &AMT.
GROUP BY CRD_CLNT_ID;
QUIT;

PROC APPEND DATA=XX BASE=Merchant_Analysis FORCE; RUN;

%END;
%END;

%MEND;

%CR();
