
**************************************************************************************

				Merchant Impact for Non Major

**************************************************************************************;
 
LIBNAME EXIST "\\inhadfil101.in.standardchartered.com\wkgrps5\RAC_IN_MIS\Falcon 6.4 data download\FRD15";

%LET TOD = %SYSFUNC(TODAY(),date9.);
%put &tod.;

*********************************************************;

PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\mernm_top5.xlsx" DBMS=XLSX OUT=mernm_top5 REPLACE; RUN;

PROC SORT DATA=EXIST.FRD15 OUT=FRD_15 NODUPKEY; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SORT DATA=mernm_top5 ; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=mernm_top5 NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_txn dbms=xlsx replace; sheet="txn_id"; run;
PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\Global_Dispute_Fraud_FI.xlsx" OUT=Global_Dispute_Fraud_FI dbms=xlsx replace; run;

PROC SQL;
CREATE TABLE TXN_DETAILS AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" OR C.FI_TRANSACTION_ID NE ""  OR D.FI_TRANSACTION_ID NE "" THEN 1 
		  END AS FRAUD
FROM mernm_top5 AS A LEFT JOIN FRD_15 AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE)
LEFT JOIN Global_Dispute_Fraud_FI AS C ON 
STRIP(A.FI_TRANSACTION_ID)=STRIP(C.FI_TRANSACTION_ID)
LEFT JOIN Dispute_txn AS D ON
STRIP(A.FI_TRANSACTION_ID) = STRIP(D.FI_TRANSACTION_ID);
QUIT;

PROC SORT DATA=TXN_DETAILS NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002;
     SET TXN_DETAILS;
   
     WHERE TRN_AUTH_POST="A" AND (AUTH_DECISION_XCD="A" OR DECI_CD_ORIG="A") AND TRN_TYP IN ("C" "M" "P") and upcase(substr(dbname,1,2)) = "DB";

     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
	 COUNTRY = CRD_CLNT_ID;

	 OUTPUT;
	 IF CRD_CLNT_ID NE "" THEN DO; COUNTRY = "All"; OUTPUT; END;
RUN;


PROC SQL;
CREATE TABLE db_Impact_Summary AS 
SELECT DISTINCT mer_id, COUNTRY, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM FALT002
group by mer_id, COUNTRY;
QUIT;





**************************************************************************************

				Credit Impact Summary

**************************************************************************************;


LIBNAME EXIST "\\inhadfil101.in.standardchartered.com\wkgrps5\RAC_IN_MIS\Falcon 6.4 data download\FRD15";

*********************************************************;

PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\mernm_top5.xlsx" DBMS=XLSX OUT=mernm_top5 REPLACE; RUN;

PROC SORT DATA=EXIST.FRD15 OUT=FRD_15 NODUPKEY; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SORT DATA=mernm_top5 ; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=mernm_top5 NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_txn dbms=xlsx replace; sheet="txn_id"; run;
PROC IMPORT DATAFILE="C:\Users\1549580\Desktop\Jhilam\Dispute Merchant Analysis\Global_Dispute_Fraud_FI.xlsx" OUT=Global_Dispute_Fraud_FI dbms=xlsx replace; run;

PROC SQL;
CREATE TABLE TXN_DETAILS AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" OR C.FI_TRANSACTION_ID NE "" OR D.FI_TRANSACTION_ID NE "" THEN 1 
		  END AS FRAUD
FROM mernm_top5 AS A LEFT JOIN FRD_15 AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE)
LEFT JOIN Global_Dispute_Fraud_FI AS C ON 
STRIP(A.FI_TRANSACTION_ID)=STRIP(C.FI_TRANSACTION_ID)
LEFT JOIN Dispute_txn AS D ON
STRIP(A.FI_TRANSACTION_ID) = STRIP(D.FI_TRANSACTION_ID);
QUIT;

PROC SORT DATA=TXN_DETAILS NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA FALT002;
     SET TXN_DETAILS;
   
     WHERE TRN_AUTH_POST="A" AND (AUTH_DECISION_XCD="A" OR DECI_CD_ORIG="A") AND TRN_TYP IN ("C" "M" "P") and upcase(substr(dbname,1,2)) = "CR";

     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
	 COUNTRY = CRD_CLNT_ID;

	 OUTPUT;
	 IF CRD_CLNT_ID NE "" THEN DO; COUNTRY = "All"; OUTPUT; END;
RUN;


PROC SQL;
CREATE TABLE CR_Impact_Summary AS 
SELECT DISTINCT mer_id, COUNTRY, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM FALT002
group by mer_id, COUNTRY;
QUIT;


data impact_summary_&TOD.;
set db_impact_summary
	cr_impact_summary;
run;