


***********************************************************************

		MR_Country_UBER_Taobao_TW_Test TW Debit 

***********************************************************************;

OPTIONS COMPRESS=YES;

LIBNAME INC1 "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";


************************************************************************;

DATA FALT002;
     SET 
INC1.falt002_DB_31MAY
INC1.falt002_DB_01JUN
INC1.falt002_DB_02JUN;
/* INC1.falt002_DB_02JUN; */
     WHERE TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M" "P") AND 
			TRN_POS_ENT_CD IN ("E" "K" "G") AND CRD_CLNT_ID IN ("SC_TANDEMTW_DB");
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);
	 COUNTRY1 = SUBSTR(CRD_CLNT_ID,LENGTH(CRD_CLNT_ID)-4,2);
RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;

%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ACCT_NBR AUTH_DTTM;

     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + TRN_AMT;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = TRN_AMT;
           END;
     END;


RUN;
%MEND; 

%UDV(CUM_INTERVAL        = 1800,                                          
     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND 
TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K" "G") and TRN_AMT > 0),
     VAR_NAME            = 30MIN);


%UDV(CUM_INTERVAL        = 86400,                                          
     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND 
TRN_TYP IN ("C" "M" "P") AND TRN_POS_ENT_CD IN ("E" "K") and TRN_AMT > 0),
     VAR_NAME            = DAILY);

DATA MR_Country_UBER_Taobao_TW_Test;

SET FALT002_2;

	**************** Decision Rule HR_Global_CNP_CPP  *****************; 
IF 

(
 CRD_CLNT_ID  ="SC_TANDEMTW_DB" AND
 TRN_AUTH_POST ="A" AND
( AUTH_DECISION_XCD ="A" OR AUTH_DECISION_XCD = "") AND
 TRN_TYP IN ("C" "M" "P")  AND
(TRN_POS_ENT_CD  IN ("E" "K" "G") OR TRN_POS_ENT_CD = "") AND
SUBSTR(USR_IND_4,1,2) NE "Y2" AND
(
(INDEX(UPCASE(MER_NM) ,"UBER") AND CUM_COUNT_DAILY >= 10) OR
(INDEX(UPCASE(MER_NM) ,"TAOBAO.COM") AND SIC_CD = "5311" AND COMPRESS(MER_ID) = "013043912" AND
CUM_COUNT_30MIN >= 2 AND CUM_AMOUNT_30MIN >= 4000 )
)
)

THEN FLAG = "Y";

RUN;


DATA TXN_DATA;
	SET MR_Country_UBER_Taobao_TW_Test;
	WHERE FLAG = "Y" AND DATE1 GE "01JUN2021"D;
RUN;

DATA RULE_DATA;
     SET 
	 INC1.falt003_DB_01JUN
INC1.falt003_DB_02JUN;
/* INC1.falt003_DB_02JUN; */
WHERE UPCASE(RULE_NAME_STRG) IN ('MR_COUNTRY_UBER_TAOBAO_TW_TEST') AND CLIENT_XID IN ("SC_TANDEMTW_DB") AND 
DATE1 GE "01JUN2021"D;
RUN;

PROC SORT DATA = RULE_DATA NODUPKEY ;BY FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA; TITLE "TXN_DATA SAS"; 
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

PROC FREQ DATA=RULE_DATA; TITLE "RULE_DATA FALCON HITS"; 
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

/**/
/*DATA CHECK;*/
/*SET TXN_DATA;*/
/*WHERE*/
/*ACCT_NBR IN*/
/*(*/
/*'4377213434702293',*/
/*'4377217135966224'*/
/*);*/
/*RUN;*/
