
							****************************************************
							        MR_CC_Country_CNP_TW_Test TW Credit
							****************************************************;

OPTIONS COMPRESS=YES;
LIBNAME CR "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Consolidated Last 3 Months Data\Oct21_Major\MAJOR_COUNTRIES_DATA";
LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";

DATA FALT002;
SET
INC.falt002_cr_30OCT
INC.falt002_cr_31OCT;

WHERE 

(
 CRD_CLNT_ID  = "SC_CCMSTW_CR" AND
 TRN_AUTH_POST  = "A"
);

FORMAT TRAN_DATE DATE9.;
TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));
MCC = INPUT(SIC_CD,BEST.);

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

RUN;


PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;

/**/
/*PROC IMPORT DATAFILE='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Hotlist\COMPROMISE_NCCC.xls'*/
/*DBMS = XLS*/
/*OUT = LOOKUP_DATA*/
/*REPLACE;*/
/*RUN;*/
/**/
/*PROC SQL;*/
/*CREATE TABLE FALT002_2 AS*/
/*SELECT * FROM FALT002_2 WHERE ACCT_NBR IN (SELECT NAME FROM LOOKUP_DATA);*/
/*RUN;*/

PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2 OUT=FALT003; BY ACCT_NBR AUTH_DTTM; RUN;

%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);
DATA FALT003;
SET FALT003;
     BY ACCT_NBR AUTH_DTTM;

    FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LT (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
               CUM_COUNT_&VAR_NAME. = 1;
               CUM_AMOUNT_&VAR_NAME. = USD;
           END;
     END;
RUN;
%MEND;

%UDV
(
CUM_INTERVAL = 2100,                                          
CUMULATIVE_CONDITION = %STR
(
     CRD_CLNT_ID  = "SC_CCMSTW_CR" AND
	TRN_AUTH_POST  ="A" AND
	 TRN_TYP  IN ("C" "M")AND
	 AUTH_DECISION_XCD  ="A" AND
	(
	( (SUBSTR(UPCASE(MER_NM),1,8) = "BLIZZARD" OR SUBSTR(UPCASE(MER_NM),1,8) = "FACEBOOK") ) OR
	( (SUBSTR(UPCASE(MER_NM),1,6) = "GOOGLE" OR SUBSTR(UPCASE(MER_NM),1,6) = "FACEBK"))
	)
),
VAR_NAME = CP_35MIN
);




DATA SAS_DATA;
   SET FALT003;
IF

( 
 CRD_CLNT_ID  = "SC_CCMSTW_CR" AND
 TRN_AUTH_POST  ="A" AND
 TRN_TYP  IN ("C" "M")AND
 FRD_SCOR  >= 550 AND
 AUTH_DECISION_XCD  ="A" AND
(
( (SUBSTR(UPCASE(MER_NM),1,8) = "BLIZZARD"
OR SUBSTR(UPCASE(MER_NM),1,6) = "GOOGLE")AND CUM_COUNT_CP_35MIN >=5 AND USD > 80) OR

( (SUBSTR(UPCASE(MER_NM),1,8) = "FACEBOOK"
OR SUBSTR(UPCASE(MER_NM),1,6) = "FACEBK")AND CUM_COUNT_CP_35MIN >=3 AND USD > 70 ) OR

( MER_ID = "188834000020254"
AND CUM_COUNT_CP_35MIN >=5 AND(SUBSTR(UPCASE(USR_DAT_1),5,2) NE "GO" AND USD > 80)))
)

THEN FLAG = "Y";
RUN;

DATA TXN_DATA;
SET SAS_DATA;
WHERE FLAG = "Y" AND DATE1 GE "30OCT2021"D;
RUN;

DATA RULE_DATA;
SET 

INC.FALT003_CR_30OCT
INC.FALT003_CR_31OCT;

WHERE UPCASE(RULE_NAME_STRG) IN ('MR_CC_COUNTRY_CNP_TW_TEST') AND
CLIENT_XID  = "SC_CCMSTW_CR" AND
DATE1 GE "30OCT2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "TXN_DATA SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

PROC FREQ DATA=RULE_DATA; TITLE "RULE_DATA FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;



/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_CC_Country_CNP_TW_Test TW Credit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
 PROC FREQ DATA = TXN_DATA;TITLE "MR_CC_Country_CNP_TW_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "MR_CC_Country_CNP_TW_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_CC_Country_CNP_TW_Test TW Credit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_CC_Country_CNP_TW_Test TW Credit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;
