



**************************************************************************************

							MR_CC_Global_CP_Test				 

**************************************************************************************;
/*PROC DELETE DATA=_ALL_;RUN;*/
OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

/*LIBNAME INC "C:\Users\1586087\Documents\Daily_datasets\Credit";*/


*********************************************************;

DATA FALT002;
SET INC.FALT002_CR_28AUG
	 INC.FALT002_CR_29AUG;

     WHERE TRN_AUTH_POST = "A" AND AUTH_DECISION_XCD = "A" AND TRN_TYP IN ("C" "M") AND
			TRN_POS_ENT_CD NOT IN ("E" "K" "G") AND 
			(
			(CRD_CLNT_ID="SC_CCMSSG_CR" AND MER_CNTY_CD NE "702" AND FRD_SCOR GE 950) OR
			(CRD_CLNT_ID="SC_CCMSIN_CR" AND MER_CNTY_CD NE "356" AND FRD_SCOR GE 850) OR
			(CRD_CLNT_ID="SC_CCMSMY_CR" AND MER_CNTY_CD NE "458" AND FRD_SCOR GE 860) OR
			(CRD_CLNT_ID="SC_CCMSBN_CR" AND MER_CNTY_CD NE "096" AND FRD_SCOR GE 950) 
			);
	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT/83.60;

	IF USD GE 150 AND DATE1 GE "28AUG2021"D;

RUN;

PROC SORT DATA=FALT002 OUT=MR_CC_GLOBAL_RN_DOM_CNP NODUPKEY; BY FI_TRANSACTION_ID; RUN;

DATA MR_CC_GLOBAL_RN_DOM_CNP_RL;
     SET INC.FALT003_CR_28AUG
		 INC.FALT003_CR_29AUG;
WHERE UPCASE(RULE_NAME_STRG) IN ('MR_CC_GLOBAL_CP_TEST') AND DATE1 GE "28AUG2021"D;
RUN;

PROC SORT DATA = MR_CC_GLOBAL_RN_DOM_CNP_RL NODUPKEY ;BY FI_TRANSACTION_ID; RUN;


PROC FREQ DATA=MR_CC_GLOBAL_RN_DOM_CNP; TITLE "MR_CC_Global_CP_Test SAS"; 
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;

PROC FREQ DATA=MR_CC_GLOBAL_RN_DOM_CNP_RL; TITLE "MR_CC_Global_CP_Test FALCON HITS"; 
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
