
**********************************************************
		 MR_Glovo_CNP_KE_Test Global Debit
				
**********************************************************;

LIBNAME INC "C:\Users\1510806\Documents\Monthly datasets\Debit\Non_Major_Market";
LIBNAME DB "C:\Users\1510806\Documents\Daily_datasets\Debit";

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Debit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";
LIBNAME CR1 "C:\Users\1510806\Desktop\Jhilam\Consolidated Last 3 Months Data\Jul21";

options compress=yes MPRINT MLOGIC SYMBOLGEN;

*********************************************************;

PROC DELETE DATA=FALT002_2; RUN;


%MACRO DEC(CNTY);

DATA FALT002_2;
SET  
/*CR.falt002_TW_db_mar2021 */
CR1.last_3_months_data_db
INC.falt002_db_01JUL
INC.falt002_db_02JUL
INC.falt002_db_03JUL
INC.falt002_db_04JUL
INC.falt002_db_05JUL
INC.falt002_db_06JUL
INC.falt002_db_07JUL
INC.falt002_db_08JUL
INC.falt002_db_09JUL
INC.falt002_db_10JUL
INC.falt002_db_11JUL
INC.falt002_db_12JUL
INC.falt002_db_13JUL
INC.falt002_db_14JUL;

     WHERE TRN_AUTH_POST = "A" ;
	ATMONUS=(COMPRESS(MER_ID)||COMPRESS(ACCT_NBR));
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2));

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/4.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/63.75;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;
RUN;

%MEND;


%DEC(KE);

PROC SORT DATA=FALT002_2 NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SORT DATA=FALT002_2; BY ATMONUS AUTH_DTTM; RUN;


DATA FALT002_2;
SET FALT002_2;
where ACCT_NBR = "4215359402070653";
RUN;

DATA FALT002_2;
     SET FALT002_2;
     BY ATMONUS AUTH_DTTM;

     FORMAT ATMONUS_FIRST_TXN_DATE DATETIME19. ATMONUS_FIRST_APPROVAL_DATE DATETIME19.;
	 RETAIN ATMONUS_FIRST_TXN_DATE ATMONUS_FIRST_APPROVAL_DATE;

     IF FIRST.ATMONUS THEN DO;
           ATMONUS_FIRST_TXN_DATE = 0;
		   ATMONUS_FIRST_APPROVAL_DATE = 0;
     END;

     IF TRN_AUTH_POST = "A" and MER_ID NE "" THEN DO;
           IF ATMONUS_FIRST_TXN_DATE = 0 THEN DO;
                ATMONUS_FIRST_TXN_DATE = AUTH_DTTM;
           END;
           IF ATMONUS_FIRST_APPROVAL_DATE = 0 AND TRN_TYP IN ("C" "M" "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") 
		   AND TRN_AMT GT 0 THEN DO;
                ATMONUS_FIRST_APPROVAL_DATE = AUTH_DTTM;
           END;
     END;


RUN;



%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ATMONUS AUTH_DTTM;

     FORMAT  TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME. 
			ATMONUS_DAILY_AA_SCORE ATMONUS_DAILY_BASE_SCORE ATMONUS_DAILY_DAYS ATMONUS_DAILY_PREV
			ATMONUS_DAILY_MAX_CNT ATMONUS_DAILY_MAX_AMT CUM_COUNT_APPROVED_&VAR_NAME. CUM_AMOUNT_APPROVED_&VAR_NAME.;

     IF FIRST.ATMONUS THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
		   CUM_COUNT_APPROVED_&VAR_NAME. = 0;
		   CUM_AMOUNT_APPROVED_&VAR_NAME. = 0;
		   ATMONUS_DAILY_BASE_SCORE=0;
		   ATMONUS_DAILY_AA_SCORE=0;
		   ATMONUS_DAILY_MAX_CNT=0;
		   ATMONUS_DAILY_MAX_AMT=0;
		   ATMONUS_DAILY_DAYS = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + TRN_AMT;
				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND TRN_AMT GT 0) THEN DO;
					CUM_COUNT_APPROVED_&VAR_NAME. + 1 ;
					CUM_AMOUNT_APPROVED_&VAR_NAME. + TRN_AMT;
				END;
				ATMONUS_DAILY_BASE_SCORE=MAX(ATMONUS_DAILY_BASE_SCORE,FRD_SCOR);
				ATMONUS_DAILY_AA_SCORE=MAX(ATMONUS_DAILY_AA_SCORE,AA_SCOR);
           END;
           ELSE DO;
		   		ATMONUS_DAILY_MAX_CNT = max(ATMONUS_DAILY_MAX_CNT, CUM_COUNT_APPROVED_&VAR_NAME.);
				ATMONUS_DAILY_MAX_AMT = max(ATMONUS_DAILY_MAX_AMT, CUM_AMOUNT_APPROVED_&VAR_NAME.);
				ATMONUS_DAILY_DAYS + 1;
				CUM_COUNT_&VAR_NAME. = 1;
           		CUM_AMOUNT_&VAR_NAME. = TRN_AMT;
                CUM_COUNT_APPROVED_&VAR_NAME. = 0;
		   		CUM_AMOUNT_APPROVED_&VAR_NAME. = 0;
				IF (TRN_TYP IN ("C"  "M"  "P") AND (AUTH_DECISION_XCD = "A" OR DECI_CD_ORIG="A") AND
					TRN_AMT GT 0) THEN DO;
					CUM_COUNT_APPROVED_&VAR_NAME. = 1 ;
					CUM_AMOUNT_APPROVED_&VAR_NAME. = TRN_AMT;
				END;
				ATMONUS_DAILY_PREV = TIME_RESET_&VAR_NAME.;
				TIME_RESET_&VAR_NAME. = AUTH_DTTM;
				ATMONUS_DAILY_BASE_SCORE = FRD_SCOR;
				ATMONUS_DAILY_AA_SCORE = AA_SCOR;
           END;
     END;

RUN;
%MEND; 

%UDV(CUM_INTERVAL        = 86400,                                          
     CUMULATIVE_CONDITION= %STR(TRN_AUTH_POST = "A" and MER_ID NE "") ,
     VAR_NAME            = DAILY);



DATA MR_Glovo_CNP_KE_TestSAS;
    SET FALT002_2;
	WHERE DATE1 GE "13JUL2021"D;
    IF (CRD_CLNT_ID = "SC_SPARROWKE_DB" and TRN_AUTH_POST = "A" and
AUTH_DECISION_XCD IN ("A" "") and TRN_TYP IN ("C" "M" "P") and
TRN_POS_ENT_CD IN ("E" "K" "G" "") and INDEX(UPCASE(MER_NM), "GLOVO") AND
(CUM_COUNT_APPROVED_DAILY > 4) AND
(CUM_AMOUNT_APPROVED_DAILY > 200))

      THEN MR_Glovo_CNP_KE_Test = "Y";
RUN;

DATA MR_Glovo_CNP_KE_Test;
SET MR_Glovo_CNP_KE_TestSAS;
WHERE MR_Glovo_CNP_KE_Test = "Y" and date1 GE "13JUL2021"D;
RUN;


DATA MR_Glovo_CNP_KE_Test_RL;
     SET INC.falt003_db_12JUL INC.falt003_db_13JUL;
       WHERE UPCASE(RULE_NAME_STRG) IN ('MR_GLOVO_CNP_KE_TEST') and date1 GE "13JUL2021"D
;
RUN;

PROC SORT DATA=MR_Glovo_CNP_KE_Test_RL NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=MR_Glovo_CNP_KE_Test;TITLE "MR_Glovo_CNP_KE_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA=MR_Glovo_CNP_KE_Test_RL; TITLE "MR_Glovo_CNP_KE_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 

