
			*******************************************************************
					 MR_MID_Amount_NonMajor_Test Global Credit

			*******************************************************************;

LIBNAME INC "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Daily Data\CR";

DATA  FALT002;
SET 
INC.falt002_cr_03nov
INC.falt002_cr_04nov;   

WHERE  CRD_CLNT_ID NOT IN ("SC_CCMSIN_CR" "SC_CCMSMY_CR" "SC_CCMSSG_CR" 
"SC_C400AE_CR" "SC_CCMSHK_CR" "SC_PMTHK_CR" "SC_CCMSTW_CR" "SC_C400BD_CR") and 
TRN_AUTH_POST = "A" and AUTH_DECISION_XCD = "A" and TRN_TYP IN  ("C" "M" "P");
FORMAT TRAN_DATE DATE9.;
 TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
 ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
 AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
 MCC = INPUT(SIC_CD,BEST.);

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

RUN;

PROC SORT DATA=FALT002 NODUPKEY; BY FI_TRANSACTION_ID; RUN;


DATA MR_MID_Amount_NonMajor_TestSAS;
SET FALT002;
IF
(
(
 TRN_AUTH_POST  = "A" AND
 AUTH_DECISION_XCD  = "A" AND
 TRN_TYP IN ("C" "M" "P")
)
and
(
(
 CRD_CLNT_ID  NOT IN ("SC_C400AE_CR"  "SC_CCMSMY_CR"  "SC_CCMSIN_CR"  "SC_CCMSSG_CR") AND
(
(
COMPRESS(MER_ID) = "498750000233875" AND
( USD  >= 5 AND  USD  <= 15)
) OR
(COMPRESS(MER_ID) = "04187197") OR
(COMPRESS(MER_ID) = "5139340")
)
)

OR
(
 CRD_CLNT_ID  = "SC_C400BH_CR" AND
COMPRESS(MER_ID) = "000000000013904" AND USD >=100
)
)
)
THEN MR_MID_Amount_NonMajor_Test = "Y";
RUN;

DATA TXN_DATA;
SET MR_MID_Amount_NonMajor_TestSAS;
WHERE MR_MID_Amount_NonMajor_Test = "Y" and date1 GE "03NOV2021"D;
RUN;


DATA RULE_DATA;
SET 
INC.falt003_cr_03nov
INC.falt003_cr_04nov;
       WHERE UPCASE(RULE_NAME_STRG) IN ('MR_MID_AMOUNT_NONMAJOR_TEST') and date1 GE "03NOV2021"D;
RUN;

PROC SORT DATA=RULE_DATA NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=TXN_DATA;TITLE "MR_MID_Amount_NonMajor_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA=RULE_DATA; TITLE "MR_MID_Amount_NonMajor_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



/* Writing Output to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_MID_Amount_NonMajor_Test Global Credit.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
 PROC FREQ DATA = TXN_DATA;TITLE "MR_MID_Amount_NonMajor_Test SAS";
TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA = RULE_DATA; TITLE "MR_MID_Amount_NonMajor_Test FALCON";
TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN;
ods excel close;
ods listing close;

PROC EXPORT DATA= TXN_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_MID_Amount_NonMajor_Test Global Credit.xlsx"
dbms=xlsx replace;
sheet="TXN_DATA";
run;

PROC EXPORT DATA= RULE_DATA
outfile= "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\SAS\Outputs\MR_MID_Amount_NonMajor_Test Global Credit.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA";
run;
