
*********************************************************************

		MR_NonMajor_3DS_Test Global Debit 

*********************************************************************;



LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";

DATA  FALT002;
SET 
/*INC.falt002_db_23may*/
/*INC.falt002_db_24may;*/
INC.falt002_db_28may
INC.falt002_db_29may
INC.falt002_db_30may; 
     WHERE 
CRD_CLNT_ID NOT IN ("SC_TANDEMTW_DB" "SC_SPARROWBD_DB" "SC_EURONETAE_DB" 
"SC_EURONETIN_DB" "SC_HOGANHK_DB" "SC_EURONETMY_DB" "SC_EURONETSG_DB") AND 
TRN_AUTH_POST = "A" and 
AUTH_DECISION_XCD IN ("A" "") AND 
TRN_TYP IN ("C" "M" "P") AND 
TRN_POS_ENT_CD IN ("E" "K" "G" "") AND  
TRN_AMT > 0 AND SUBSTR(USR_IND_4,1,2) IN ("Y2")
	 AND DATE1 GE "08SEP2020"D;
     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
     MCC = INPUT(SIC_CD,BEST.);

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_BD" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/4.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;

RUN;

PROC SORT DATA=FALT002 OUT=FALT002_1 NODUPKEY; BY FI_TRANSACTION_ID; RUN;


PROC SORT DATA=FALT002 OUT=FALT002_2; BY ACCT_NBR AUTH_DTTM; RUN;


%MACRO UDV(CUM_INTERVAL=, CUMULATIVE_CONDITION =, VAR_NAME=);

DATA FALT002_2;
     SET FALT002_2;
     BY ACCT_NBR AUTH_DTTM;

     FORMAT TIME_RESET_&VAR_NAME. DATETIME19.;

     RETAIN CUM_COUNT_&VAR_NAME. TIME_RESET_&VAR_NAME. CUM_AMOUNT_&VAR_NAME.;

     IF FIRST.ACCT_NBR THEN DO;
           TIME_RESET_&VAR_NAME. = 0;
           CUM_COUNT_&VAR_NAME. = 0;
           CUM_AMOUNT_&VAR_NAME. = 0;
     END;

     IF &CUMULATIVE_CONDITION. THEN DO;
           IF AUTH_DTTM LE (TIME_RESET_&VAR_NAME. + &CUM_INTERVAL.) THEN DO;
                CUM_COUNT_&VAR_NAME. + 1;
                CUM_AMOUNT_&VAR_NAME. + USD;
           END;
           ELSE DO;
                TIME_RESET_&VAR_NAME. = AUTH_DTTM;
                CUM_COUNT_&VAR_NAME. = 1;
                CUM_AMOUNT_&VAR_NAME. = USD;
           END;
     END;


RUN;
%MEND; 

%UDV(CUM_INTERVAL = 1800,                                          
CUMULATIVE_CONDITION= %STR(CRD_CLNT_ID NOT IN ("SC_TANDEMTW_DB" "SC_SPARROWBD_DB" "SC_EURONETAE_DB" 
"SC_EURONETIN_DB" "SC_HOGANHK_DB" "SC_EURONETMY_DB" "SC_EURONETSG_DB") AND 
TRN_AUTH_POST = "A" and AUTH_DECISION_XCD IN ("A" "") AND 
								TRN_TYP IN ("C" "M" "P") AND 
TRN_POS_ENT_CD IN ("E" "K" "G" "") AND  TRN_AMT > 0 AND 
SUBSTR(USR_IND_4,1,2) IN ("Y2")),
VAR_NAME = 3DS_30MINS);


DATA MR_NonMajor_3DS_TestSAS;
    SET FALT002_2;

	**************** Decision Rule MR_NonMajor_3DS_Test *****************; 

	IF TRN_AUTH_POST = "A" AND  AUTH_DECISION_XCD IN ("A" "") AND TRN_TYP IN ("C"  "M"  "P") AND	
	TRN_POS_ENT_CD IN ("E" "K" "G" "") AND TRN_AMT > 0 AND SUBSTR(USR_IND_4,1,2) EQ "Y2" AND 
	SIC_CD NOT IN ("8062" "5912") AND (0 LT (AUTH_DTTM - TIME_RESET_3DS_30MINS) LT 1800) AND 
	(
	(CRD_CLNT_ID IN  ("SC_EURONETBH_DB" "SC_EURONETBN_DB" "SC_EURONETVN_DB" 
"SC_SPARROWBW_DB" "SC_SPARROWCI_DB" "SC_SPARROWGH_DB" "SC_SPARROWGM_DB" 
"SC_SPARROWJO_DB" "SC_SPARROWKE_DB" "SC_SPARROWLK_DB" "SC_SPARROWNG_DB" 
"SC_SPARROWNP_DB" "SC_SPARROWTZ_DB" "SC_SPARROWUG_DB") AND 
	CUM_COUNT_3DS_30MINS GT 3 AND CUM_AMOUNT_3DS_30MINS GT 100) OR

	(CRD_CLNT_ID IN  ("SC_SPARROWZM_DB")  AND 
	CUM_COUNT_3DS_30MINS GT 3) OR

	(CRD_CLNT_ID IN  ("SC_SPARROWZW_DB")  AND 
	CUM_COUNT_3DS_30MINS GT 2) OR

	(CRD_CLNT_ID IN  ("SC_SPARROWCM_DB" "SC_SPARROWQA_DB" "SC_SPARROWSL_DB") AND 
	FRD_SCOR > 500) 
	)

	THEN MR_NonMajor_3DS_Test = "Y";


RUN;

DATA MR_NonMajor_3DS_Test;
SET MR_NonMajor_3DS_TestSAS;
WHERE MR_NonMajor_3DS_Test = "Y" AND DATE1 GE "29MAY2021"D;
RUN;


DATA MR_NonMajor_3DS_Test_RL;
SET
/*INC.falt003_db_23may*/
/*INC.falt003_db_24may;*/
INC.falt003_db_29MAY
INC.falt003_db_30MAY;
        WHERE UPCASE(RULE_NAME_STRG) IN ('MR_NONMAJOR_3DS_TEST')
		AND DATE1 GE "29MAY2021"D;
RUN;

PROC SORT DATA=MR_NonMajor_3DS_Test_RL NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA=MR_NonMajor_3DS_Test; TABLE CRD_CLNT_ID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 
PROC FREQ DATA=MR_NonMajor_3DS_Test_RL; TABLE CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



/*CROSS CHECK* - 5 STEPS */

/********************** cross check 4 STEPS ***********************/

/* 1 - Getting txns in SAS not in Falcon */
/* MER_ID is Name in VIP list Case manager */

PROC SQL;
CREATE TABLE txn_in_sas_not_in_rule AS 
SELECT ACCT_NBR, FI_TRANSACTION_ID, MER_ID, * FROM MR_NonMajor_3DS_Test where 
FI_TRANSACTION_ID not in (SELECT distinct(FI_TRANSACTION_ID) FROM 
MR_NonMajor_3DS_Test_RL);
QUIT;


/* 2 - High priority rule check */

DATA OTHER_RULE;
SET 
INC.falt003_db_29MAY
INC.falt003_db_30MAY;
WHERE FI_TRANSACTION_ID IN 
(
'2060b102eb02ed03'
/*'0060b103ba03d789'*/
/*'0060b103ba03d828'*/
/*'1e60b102eb03bbd3'*/
/*'2160b1031900a715'*/
) and
UPCASE(RULE_NAME_STRG) not IN ('MR_NONMAJOR_3DS_TEST');
RUN;


DATA ALL_ACCT_NBR_FROM_FALT002;
SET 
/*INC.falt002_db_23may*/
/*INC.falt002_db_24may;*/
INC.falt002_db_29may
INC.falt002_db_30may;
WHERE ACCT_NBR IN 
(
"4714151400073979"
);
RUN;


DATA ALL_ACCT_NBR_FROM_FALT003;
SET 
/*INC.falt002_db_23may*/
/*INC.falt002_db_24may;*/
INC.falt003_db_29may
INC.falt003_db_30may;
WHERE SCORE_CUSTOMER_ACCOUNT_XID IN 
(
"4714151400073979"
);
RUN;


/* 2 - High priority rule check */

DATA ACCT_NBR_INRULE_DATA;
SET 
INC.falt003_db_29MAY
INC.falt003_db_30MAY;
WHERE SCORE_CUSTOMER_ACCOUNT_XID IN
(
"4714151400073979"
/*'0060b103ba03d789'*/
/*'0060b103ba03d828'*/
/*'1e60b102eb03bbd3'*/
/*'2160b1031900a715'*/
);
/*and UPCASE(RULE_NAME_STRG) not IN ('MR_NONMAJOR_3DS_TEST');*/
RUN;

/* 3 - Genuine list check */

DATA CASACTN;
SET INC.casactn_db_29may
INC.casactn_db_30may;
WHERE ACCT_NBR IN 
(
"4714151400073979"
/*"4783932298520866"*/
/*"4935410000004450"*/
) and date1 ge "29may2021"d;
RUN;

/* 4 - If not solved in previous steps chec those ACCT_NBRs here*/
/* MER_ID or Name extraction for ACCT_NBS in SAS not in Falcon*/

PROC SQL;
CREATE TABLE VIP AS 
SELECT distinct(MER_ID), FI_TRANSACTION_ID FROM MR_NonMajor_3DS_Test where ACCT_NBR in
(
'4714151400073979'
/*'4783932298520866'*/
/*'4935410000004450'*/
);
RUN;

/* 5 - Check if the ACCT_NBR is present in VIP list (Case manager)*/

DATA VIP_LIST;
SET LOOKUP_DATA;
WHERE
NAME IN(
'484767000200403'
'EP86CJLWQYAQGJM'
);
RUN;

/********************** cross check 5 STEPS ***********************/



/**/
/*data chk;*/
/*set INC.falt003_db_11sep_bd;*/
/*where FI_TRANSACTION_ID in */
/*('005f577e2e02543e'*/
/*'1e5f577d6d024e68'*/
/*'1e5f577d6d02f8c9'*/
/*'035f577e5b0209c7');*/
/*run;*/
/**/
/*proc freq data=INC.falt003_cr_09sep; table filename; run;*/