

LIBNAME PVB "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\PvB_Dataset";


OPTIONS COMPRESS=YES;


 %LET TOD = %SYSFUNC(TODAY());
 %LET MNTH0 = %SYSFUNC(INTNX(MONTH,&TOD.,0),MONYY7.);
 %LET MNTH1 = %SYSFUNC(INTNX(MONTH,&TOD.,-1),MONYY7.);
 %PUT &MNTH1. &MNTH0. ;


DATA CLOSED_CASES;
 SET PVB.BRP005_HIST;
 FORMAT DATE FIRST_DATE_PREV_MNTH LAST_DATE_PREV_MNTH DATE9.;
 WHERE STRIP(UPCASE(CASE_STATUS_TYPE_CD)) = 'CLOSED';* AND STRIP(MANUAL_CASE_FLG) = "1";
 FIRST_DATE_PREV_MNTH = INTNX('MONTH',&TOD.,-1,'B');
 LAST_DATE_PREV_MNTH = INTNX('MONTH',&TOD.,-1,'E');
DATE = INPUT(SUBSTR(LAST_UPDATED_DTTM,1,2) || SUBSTR(LAST_UPDATED_DTTM,4,3) || '20' || SUBSTR(LAST_UPDATED_DTTM,8,2),DATE9.);
IF FIRST_DATE_PREV_MNTH LE DATE LE LAST_DATE_PREV_MNTH;
DROP FIRST_DATE_PREV_MNTH LAST_DATE_PREV_MNTH;
RUN;

PROC SORT DATA=CLOSED_CASES ; BY CASE_REFERENCE_NUM DESCENDING DATE; RUN;
PROC SORT DATA=CLOSED_CASES NODUPKEY DUPOUT=X; BY CASE_REFERENCE_NUM; RUN;

PROC SQL;
CREATE TABLE CLOSED_CASES_SUMMARY_&MNTH1. AS 
SELECT DISTINCT USER_NAME, DATE FORMAT = DATE9., COUNT(DISTINCT CASE_REFERENCE_NUM) AS  CASE_COUNT
FROM CLOSED_CASES
GROUP BY USER_NAME, DATE;
QUIT;

PROC SORT DATA=CLOSED_CASES_SUMMARY_&MNTH1.; BY DATE; RUN;

PROC TRANSPOSE DATA=CLOSED_CASES_SUMMARY_&MNTH1. OUT=&MNTH1._PVB_SUMMARY(DROP=_NAME_) PREFIX=ID_;
BY DATE;
ID USER_NAME;
VAR CASE_COUNT;
RUN;

/*COMMENTS: CHANGE PATH*/

PROC EXPORT DATA=CLOSED_CASES OUTFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\PVB\CLOSED_CASES_DETAILS_&MNTH1..xlsx" DBMS=XLSX REPLACE; RUN;
PROC EXPORT DATA=&MNTH1._PVB_SUMMARY OUTFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\PVB\CLOSED_CASES_SUMMARY_&MNTH1..xlsx" DBMS=XLSX REPLACE; RUN;

