

								/********* CREDIT *********/


OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

DATA RULE_DATA_CR;
SET 
INC.falt003_cr_21AUG
INC.falt003_cr_22AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'HR_GLOBAL_BLACKLISTINGN1_TW_TEST',
'HR_GLOBAL_COLLUSIVE_MERCHANT_TEST',
'HR_MERCHANT_ACQID_INT_CNP_TEST',
'MR_BIN_ATTACK_INT_CNP_TEST',
'MR_BIN_ATTACK_INT_CP_TEST',
'MR_BIN_ATTACK_LOC_CNP_TEST',
'HR_GLOBAL_BLACKLISTINGN1_TW',
'HR_GLOBAL_COLLUSIVE_MERCHANT',
'HR_MERCHANT_ACQID_INT_CNP',
'MR_BIN_ATTACK_INT_CNP',
'MR_BIN_ATTACK_INT_CP',
'MR_BIN_ATTACK_LOC_CNP'
) and 
/*CLIENT_XID NOT IN ("SC_C400BD_CR" "SC_PMTHK_CR" "SC_CCMSHK_CR" "SC_CCMSTW_CR")*/
CLIENT_XID = "SC_CCMSTW_CR"
and date1 GE "21AUG2021"D;
RUN;

PROC SORT DATA = RULE_DATA_CR NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = RULE_DATA_CR; TITLE "DATA FOR FALCON CREDIT";
TABLE RULE_NAME_STRG*CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



								/********* DEBIT *********/


OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Debit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";

DATA RULE_DATA_DB_1;
SET 
INC.falt003_db_21AUG
INC.falt003_db_22AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'MR_MERCHANT_ACQID_LOC_CNP_TEST',
'MR_MERCHANT_ACQID_LOC_CP_TEST',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP_TEST',
'MR_MERCHANT_ACQID_LOC_CNP',
'MR_MERCHANT_ACQID_LOC_CP',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP'
) and 
/*CLIENT_XID NOT IN ("SC_SPARROWBD_DB" "SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETID_DB")*/
CLIENT_XID = "SC_SPARROWBD_DB"
and date1 GE "21AUG2021"D;
RUN;


DATA RULE_DATA_DB_2;
SET 
INC.falt003_db_21AUG
INC.falt003_db_22AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'MR_BIN_ATTACK_LOC_CP_TEST',
'MR_GLOBAL_MID_WATCHLIST_TEST',
'MR_MERCHANT_ACQID_BRAZIL_CP_TEST',
'MR_MERCHANT_ACQID_INT_CNP_TEST',
'MR_MERCHANT_ACQID_INT_CP_TEST',
'MR_MERCHANT_ACQID_INT_JEE_MCC_CP_TEST',
'MR_MERCHANT_ACQID_LOC_CNP_TEST',
'MR_MERCHANT_ACQID_LOC_CP_TEST',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP_TEST',
'MR_BIN_ATTACK_LOC_CP',
'MR_GLOBAL_MID_WATCHLIST',
'MR_MERCHANT_ACQID_BRAZIL_CP',
'MR_MERCHANT_ACQID_INT_CNP',
'MR_MERCHANT_ACQID_INT_CP',
'MR_MERCHANT_ACQID_INT_JEE_MCC_CP',
'MR_MERCHANT_ACQID_LOC_CNP',
'MR_MERCHANT_ACQID_LOC_CP',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP'
) and 
/*CLIENT_XID NOT IN ("SC_SPARROWBD_DB" "SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETID_DB")*/
CLIENT_XID = "SC_EURONETID_DB"
and date1 GE "21AUG2021"D;
RUN;


DATA RULE_DATA_DB;
SET RULE_DATA_DB_1 RULE_DATA_DB_2;
RUN;

PROC SORT DATA = RULE_DATA_DB NODUPKEY; 
BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = RULE_DATA_DB; 
TITLE "DATA FOR FALCON DEBIT";
TABLE RULE_NAME_STRG*CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; 
RUN; 

/* Writing Outout to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_HK_CR_DR_23AUG.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
ods excel close;
ods listing close;

PROC EXPORT DATA= RULE_DATA_DB
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_HK_CR_DR_23AUG.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA_DB";
run;

PROC EXPORT DATA= RULE_DATA_CR
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_HK_CR_DR_23AUG.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA_CR";
run;


/***********************************************************/
