

								/********* CREDIT *********/


OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Credit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\CR";

DATA RULE_DATA_CR_1;
SET 
INC.falt003_cr_27AUG
INC.falt003_cr_28AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'HR_GLOBAL_MERCHANT_MID_TEST',
'HR_GLOBAL_MERCHANT_MID'
) and 
CLIENT_XID NOT IN ("SC_C400BD_CR" "SC_PMTHK_CR" "SC_CCMSHK_CR" "SC_CCMSTW_CR")
/*CLIENT_XID = "SC_PMTHK_CR"*/
and date1 GE "27AUG2021"D;
RUN;


DATA RULE_DATA_CR_2;
SET 
INC.falt003_cr_27AUG
INC.falt003_cr_28AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'MR_MERCHANT_ACQID_LOC_CNP_TEST',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP_TEST',
'MR_OTH_DEC_BIN_ATTACK_INT_CNP_TEST',
'MR_OTH_DEC_BIN_ATTACK_LOC_CNP_TEST',
'MR_MERCHANT_ACQID_LOC_CNP',
'MR_MERCHANT_ACQID_LOC_JEE_MCC_CP',
'MR_OTH_DEC_BIN_ATTACK_INT_CNP',
'MR_OTH_DEC_BIN_ATTACK_LOC_CNP'
) and 
/*CLIENT_XID NOT IN ("SC_C400BD_CR" "SC_PMTHK_CR" "SC_CCMSHK_CR" "SC_CCMSTW_CR")*/
CLIENT_XID = "SC_CCMSTW_CR"
and date1 GE "27AUG2021"D;
RUN;

DATA RULE_DATA_CR;
SET RULE_DATA_CR_1 RULE_DATA_CR_2;
RUN;

PROC SORT DATA = RULE_DATA_CR NODUPKEY; BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = RULE_DATA_CR; TITLE "DATA FOR FALCON CREDIT";
TABLE RULE_NAME_STRG*CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; RUN; 



								/********* DEBIT *********/


OPTIONS COMPRESS=YES;

LIBNAME CR "C:\Users\1510806\Desktop\Jhilam\Falcon 6.4 Monthly Data\Debit";
LIBNAME INC "C:\Users\1510806\Desktop\Jhilam\Daily Data\DB";

DATA RULE_DATA_DB_1;
SET 
INC.falt003_db_27AUG
INC.falt003_db_28AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'HR_GLOBAL_MERCHANT_MID_TEST',
'HR_GLOBAL_MERCHANT_MID'
) and 
CLIENT_XID NOT IN ("SC_SPARROWBD_DB" "SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETID_DB")
/*CLIENT_XID = "SC_TANDEMTW_DB"*/
and date1 GE "27AUG2021"D;
RUN;


DATA RULE_DATA_DB_2;
SET 
INC.falt003_db_27AUG
INC.falt003_db_28AUG;
WHERE UPCASE(RULE_NAME_STRG) IN 
(
'MR_MERCHANT_ACQID_BRAZIL_CP_TEST',
'MR_MERCHANT_ACQID_INT_ATM_TEST',
'MR_MERCHANT_ACQID_INT_CNP_TEST',
'MR_MERCHANT_ACQID_INT_CP_TEST',
'MR_MERCHANT_ACQID_LOC_CNP_TEST',
'MR_MERCHANT_ACQID_LOC_CP_TEST',
'MR_MERCHANT_ACQID_BRAZIL_CP',
'MR_MERCHANT_ACQID_INT_ATM',
'MR_MERCHANT_ACQID_INT_CNP',
'MR_MERCHANT_ACQID_INT_CP',
'MR_MERCHANT_ACQID_LOC_CNP',
'MR_MERCHANT_ACQID_LOC_CP'
) and 
/*CLIENT_XID NOT IN ("SC_SPARROWBD_DB" "SC_HOGANHK_DB" "SC_TANDEMTW_DB" "SC_EURONETID_DB")*/
CLIENT_XID = "SC_TANDEMTW_DB"
and date1 GE "27AUG2021"D;
RUN;


DATA RULE_DATA_DB;
SET RULE_DATA_DB_1 RULE_DATA_DB_2;
RUN;

PROC SORT DATA = RULE_DATA_DB NODUPKEY; 
BY RULE_NAME_STRG FI_TRANSACTION_ID; RUN;

PROC FREQ DATA = RULE_DATA_DB; 
TITLE "DATA FOR FALCON DEBIT";
TABLE RULE_NAME_STRG*CLIENT_XID*DATE1/NOCOL NOROW NOPERCENT NOCUM; 
RUN; 

/* Writing Outout to Excel - For Audit*/

ods listing;
ods excel file='C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_CR_DR_29AUG.xlsx'
 options(sheet_interval="NONE");
 ods excel options(sheet_name="OUTPUT");
ods excel close;
ods listing close;

PROC EXPORT DATA= RULE_DATA_DB
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_CR_DR_29AUG.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA_DB";
run;

PROC EXPORT DATA= RULE_DATA_CR
outfile= "C:\Users\1510806\Desktop\SAS\Outputs\Rule_Hits_CR_DR_29AUG.xlsx"
dbms=xlsx replace;
sheet="RULE_DATA_CR";
run;


/***********************************************************/
