
**************************************************************************************

				Merchant Impact for Non Major

**************************************************************************************;

/*PROC IMPORT DATAFILE="C:\USERS\1510806\DOCUMENTS\MONTHLY DATASETS\FRD15_FromAPR2020to21SEP2020.XLSX"*/
/*OUT=FRD_15_EXCEL DBMS=XLSX REPLACE;RUN;*/


LIBNAME EXIST "C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Falcon 6.4 Monthly Data";

options compress=yes MPRINT MLOGIC SYMBOLGEN;

*********************************************************;

DATA FRD15;
SET EXIST.FRD15;
/*FRD_15_EXCEL;*/
RUN;

 

/*LIBNAME EXIST "\\inhadfil101.in.standardchartered.com\wkgrps5\RAC_IN_MIS\Falcon 6.4 data download\FRD15";*/

%LET TOD = %SYSFUNC(TODAY(),date9.);

*********************************************************;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\mernm.xlsx" DBMS=XLSX OUT=mernm REPLACE; RUN;

PROC SORT DATA=FRD15 OUT=FRD_15 NODUPKEY; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SORT DATA=mernm ; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=mernm NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_txn dbms=xlsx replace; sheet="txn_id"; run;
PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Global_Dispute_Fraud_FI.xlsx" OUT=Global_Dispute_Fraud_FI dbms=xlsx replace; run;

PROC SQL;
CREATE TABLE TXN_DETAILS AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" OR C.FI_TRANSACTION_ID NE ""  OR D.FI_TRANSACTION_ID NE "" THEN 1 
		  END AS FRAUD
FROM mernm AS A LEFT JOIN FRD_15 AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE)
LEFT JOIN Global_Dispute_Fraud_FI AS C ON 
STRIP(A.FI_TRANSACTION_ID)=STRIP(C.FI_TRANSACTION_ID)
LEFT JOIN Dispute_txn AS D ON
STRIP(A.FI_TRANSACTION_ID) = STRIP(D.FI_TRANSACTION_ID);
QUIT;

PROC SORT DATA=TXN_DETAILS NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

DATA FALT002;
     SET TXN_DETAILS;
   
     WHERE TRN_AUTH_POST="A" AND (AUTH_DECISION_XCD="A" OR DECI_CD_ORIG="A") AND TRN_TYP NE "X" and upcase(substr(dbname,1,2)) = "DB";

     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
	 COUNTRY = CRD_CLNT_ID;

	 OUTPUT;
	 IF CRD_CLNT_ID NE "" THEN DO; COUNTRY = "All"; OUTPUT; END;
RUN;


PROC SQL;
CREATE TABLE db_Impact_Summary AS 
SELECT DISTINCT mer_id, COUNTRY, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM FALT002
group by mer_id, COUNTRY;
QUIT;


PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Merchants.xlsx" OUT=Merchants dbms=xlsx replace; run;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_MID dbms=xlsx replace; sheet="MID"; run;


proc sql;
create table db_Impact_Summary1 as 
select A.MID, A.MER_NM, B.*, "Debit	" as Product, CASE WHEN MER_ID IN (SELECT DISTINCT MER_ID FROM Dispute_MID) THEN "Y" END AS PREVIOUSLY_SHARED 
from Merchants(where=(mid ne "")) as a 
left join 
db_Impact_Summary b 
on strip(a.mid) = strip(b.mer_id);
quit;









/*crdit*/





**************************************************************************************

				Credit Impact Summary

**************************************************************************************;


/*LIBNAME EXIST "\\inhadfil101.in.standardchartered.com\wkgrps5\RAC_IN_MIS\Falcon 6.4 data download\FRD15";*/

*********************************************************;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\mernm.xlsx" DBMS=XLSX OUT=mernm REPLACE; RUN;

PROC SORT DATA=FRD15 OUT=FRD_15 NODUPKEY; 
	BY PAN FITRANSACTIONIDREFERENCE; 
RUN;

PROC SORT DATA=mernm ; BY ACCT_NBR FI_TRANSACTION_ID DESCENDING FRD_IND; RUN;
PROC SORT DATA=mernm NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_txn dbms=xlsx replace; sheet="txn_id"; run;
PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Global_Dispute_Fraud_FI.xlsx" OUT=Global_Dispute_Fraud_FI dbms=xlsx replace; run;

PROC SQL;
CREATE TABLE TXN_DETAILS AS
		SELECT A.*,
		  B.FRAUDFLAG,
		  CASE 
			WHEN STRIP(UPCASE(A.FRD_IND)) IN ("Y" "D") OR B.FRAUDFLAG="1" OR C.FI_TRANSACTION_ID NE "" OR D.FI_TRANSACTION_ID NE "" THEN 1 
		  END AS FRAUD
FROM mernm AS A LEFT JOIN FRD_15 AS B ON 
STRIP(A.CRD_CLNT_ID)=STRIP(B.CLIENTIDFROMHEADER) AND
STRIP(A.FI_TRANSACTION_ID)=STRIP(B.FITRANSACTIONIDREFERENCE)
LEFT JOIN Global_Dispute_Fraud_FI AS C ON 
STRIP(A.FI_TRANSACTION_ID)=STRIP(C.FI_TRANSACTION_ID)
LEFT JOIN Dispute_txn AS D ON
STRIP(A.FI_TRANSACTION_ID) = STRIP(D.FI_TRANSACTION_ID);
QUIT;

PROC SORT DATA=TXN_DETAILS NODUPKEY; BY ACCT_NBR FI_TRANSACTION_ID; RUN;

DATA FALT002;
     SET TXN_DETAILS;
   
     WHERE TRN_AUTH_POST="A" AND (AUTH_DECISION_XCD="A" OR DECI_CD_ORIG="A") AND TRN_TYP NE "X" and upcase(substr(dbname,1,2)) = "CR";

     FORMAT TRAN_DATE DATE9.;
     TRAN_DATE = INPUT(SUBSTR(TRN_DT,1,2) || SUBSTR(TRN_DT,4,3) || '20' || SUBSTR(TRN_DT,8,2),DATE9.);
     ATTRIB AUTH_DTTM FORMAT=DATETIME19.;
     AUTH_DTTM=DHMS(TRAN_DATE,SUBSTR(TRN_DT,11,2),SUBSTR(TRN_DT,14,2),SUBSTR(TRN_DT,17,2)); 
	 COUNTRY = CRD_CLNT_ID;

	 OUTPUT;
	 IF CRD_CLNT_ID NE "" THEN DO; COUNTRY = "All"; OUTPUT; END;
RUN;


PROC SQL;
CREATE TABLE CR_Impact_Summary AS 
SELECT DISTINCT mer_id, COUNTRY, 
		COUNT(DISTINCT FI_TRANSACTION_ID) AS TXN_COUNT, 
		COUNT(DISTINCT ACCT_NBR) AS ACCT_COUNT, 
		SUM(FRAUD) AS NO_OF_FRAUDS,
		COUNT(DISTINCT CASE WHEN FRAUD=1 THEN ACCT_NBR END) AS NO_OF_CARDS_FRAUD, 
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED TXN_COUNT/CALCULATED NO_OF_FRAUDS
		 ELSE CALCULATED TXN_COUNT
		END AS TFPR,
		CASE 
		 WHEN SUM(FRAUD) NE . THEN CALCULATED ACCT_COUNT/CALCULATED NO_OF_CARDS_FRAUD
		 ELSE CALCULATED ACCT_COUNT
		END AS AFPR,
		ROUND(CALCULATED ACCT_COUNT/90,1) AS IMPACT_PER_DAY
FROM FALT002
group by mer_id, COUNTRY;
QUIT;


PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Merchants.xlsx" OUT=Merchants dbms=xlsx replace; run;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Cases.xlsx" OUT=Dispute_MID dbms=xlsx replace; sheet="MID"; run;

proc sql;
create table cr_Impact_Summary1 as 
select  A.MID, A.MER_NM, B.*, "Credit" as Product, CASE WHEN MER_ID IN (SELECT DISTINCT MER_ID FROM Dispute_MID) THEN "Y" END AS PREVIOUSLY_SHARED
from Merchants(where=(mid ne "")) as a 
left join 
cr_Impact_Summary b 
on strip(a.mid) = strip(b.mer_id);
quit;

data impact_summary_&TOD.(drop=mer_id);
set db_impact_summary1
	cr_impact_summary1;
run;




/*data extraction*/

data MID_&tod.;
set TXN_DETAILS;
/*where mer_id = "000980200966995";*/
	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/4.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;
run;

PROC EXPORT DATA=impact_summary_&TOD. 
OUTFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\impact_summary_&TOD..xlsx"
DBMS=XLSX REPLACE;
RUN;


DATA MID_1; 
SET MID_&tod.(OBS=578829); 
RUN; 
DATA MID_2; 
SET MID_&tod.(FIRSTOBS=578830); 
RUN; 

proc export data=MID_1 
 outfile="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\MID_&tod.xlsx" 
dbms=xlsx replace;SHEET="MID_1";run; 
proc export data=MID_2 
 outfile="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\MID_&tod.xlsx" 
dbms=xlsx replace;SHEET="MID_2";run; 


*SUMMARY*;

PROC IMPORT DATAFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\Dispute Txns.xlsx" DBMS=XLSX OUT=Dispute_Txns REPLACE; RUN;


data chk;
set Dispute_Txns;
WHERE REPORTED_DATE = "&tod."D;
format date1 date9.;
IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_BD" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
		ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/4.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;
run;

PROC SORT DATA=chk NODUPKEY; BY FI_TRANSACTION_ID; RUN;

PROC SQL;
CREATE TABLE FRD_MIN(DROP=NO_OF_RULE_HITS) AS 
SELECT DISTINCT CRD_CLNT_ID AS CNTY,
				ACCT_NBR, 
				MIN(DATE1) AS MIN_TRAN_DATE FORMAT=DATE9.,
				SUM(USD) AS TRN_AMT_USD,
				COUNT(DISTINCT FI_TRANSACTION_ID) AS NUM_TXNS,
				COUNT(DISTINCT STRIP(MER_ID)) AS UNIQUE_MERCHANT,
				COUNT(DISTINCT CASE WHEN RULE_NAME_STRG NE "" THEN ACCT_NBR END) AS NO_OF_RULE_HITS,
				CASE WHEN CALCULATED NO_OF_RULE_HITS = 0 THEN "Dispute" ELSE "Detected" END AS DETECTED_DISPUTE_IND
FROM chk
GROUP BY ACCT_NBR;
QUIT;


PROC EXPORT DATA=FRD_MIN 
OUTFILE="C:\Users\1510806\OneDrive - Standard Chartered Bank\Desktop\Jhilam\Dispute Merchant Analysis\FRD_MIN_&tod..xlsx"
DBMS=XLSX REPLACE;
RUN;


