
**********************************************************************************************
									CONVERTING TO USD
**********************************************************************************************;


*********************FOR CREDIT COUNTRIES**************************;

DATA CR_DATA_WITH_USD;
    SET CR_INPUT_DATA;

	IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_C400BD_CR" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

	IF CRD_CLNT_ID IN ("SC_CCMSSG_CR" "SC_CCMSBN_CR") THEN USD = TRN_AMT/1.255698;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSMY_CR") THEN USD = TRN_AMT/3.221743;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSPH_CR") THEN USD = TRN_AMT/43.88082;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTH_CR") THEN USD = TRN_AMT/32.675467;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSID_CR") THEN USD = TRN_AMT/11627.906977;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSIN_CR") THEN USD = TRN_AMT/63.75;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSTW_CR") THEN USD = TRN_AMT/30.116853;
	ELSE IF CRD_CLNT_ID IN ("SC_C400AE_CR") THEN USD = TRN_AMT/3.67;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BH_CR") THEN USD = TRN_AMT/0.377132;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BW_CR") THEN USD = TRN_AMT/10.2587;
	ELSE IF CRD_CLNT_ID IN ("SC_C400GH_CR") THEN USD = TRN_AMT/4.42718;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JO_CR") THEN USD = TRN_AMT/0.708893;
	ELSE IF CRD_CLNT_ID IN ("SC_C400JE_CR") THEN USD = TRN_AMT/0.75;
	ELSE IF CRD_CLNT_ID IN ("SC_C400KE_CR") THEN USD = TRN_AMT/103.824;
	ELSE IF CRD_CLNT_ID IN ("SC_C400LK_CR") THEN USD = TRN_AMT/153.05;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NG_CR") THEN USD = TRN_AMT/365.467;
	ELSE IF CRD_CLNT_ID IN ("SC_C400NP_CR") THEN USD = TRN_AMT/102.69;
	ELSE IF CRD_CLNT_ID IN ("SC_C400VN_CR") THEN USD = TRN_AMT/22727.50;
	ELSE IF CRD_CLNT_ID IN ("SC_C400ZM_CR") THEN USD = TRN_AMT/8.98193;
	ELSE IF CRD_CLNT_ID IN ("SC_CCMSHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_PMTHK_CR") THEN USD = TRN_AMT/7.8;
	ELSE IF CRD_CLNT_ID IN ("SC_C400BD_CR") THEN USD = TRN_AMT_LOCAL/83.60;

RUN;



*********************FOR DEBIT COUNTRIES**************************;

DATA DB_DATA_WITH_USD;
    SET DB_INPUT_DATA;

		IF SUBSTR(ACCT_NBR,1,6) IN ('411144'
								'421451'
								'469626'
								'470691') AND CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN TRN_AMT_LOCAL = TRN_AMT * 83.60;
	ELSE TRN_AMT_LOCAL = TRN_AMT;

		IF CRD_CLNT_ID = "SC_EURONETAE_DB" THEN USD = TRN_AMT/3.67;
			ELSE IF CRD_CLNT_ID = "SC_EURONETMY_DB" THEN USD= TRN_AMT/3.221743;
		ELSE IF CRD_CLNT_ID = "SC_EURONETID_DB" THEN USD= TRN_AMT/13500;
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65;
		ELSE IF CRD_CLNT_ID = "SC_TANDEMTW_DB" THEN USD= TRN_AMT/30.116853; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETBH_DB" THEN USD= TRN_AMT/0.377132; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.2587; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGH_DB" THEN USD= TRN_AMT/4.42718; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWJO_DB" THEN USD= TRN_AMT/0.708893; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWKE_DB" THEN USD= TRN_AMT/103.824; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWLK_DB" THEN USD= TRN_AMT/153.05; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNG_DB" THEN USD= TRN_AMT/365.467; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWNP_DB" THEN USD= TRN_AMT/102.69; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETVN_DB" THEN USD= TRN_AMT/22700; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZM_DB" THEN USD= TRN_AMT/8.98193; 
		ELSE IF CRD_CLNT_ID IN ("SC_EURONETBN_DB"  "SC_EURONETSG_DB") THEN USD= TRN_AMT/1.36370; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBW_DB" THEN USD= TRN_AMT/10.3382; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWGM_DB" THEN USD= TRN_AMT/45.8258; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETIN_DB" THEN USD= TRN_AMT/65; 
		ELSE IF CRD_CLNT_ID = "SC_EURONETQA_DB" THEN USD= TRN_AMT/3.64146; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWTZ_DB" THEN USD= TRN_AMT/2240.11; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWUG_DB" THEN USD= TRN_AMT/3603.55; 
		ELSE IF CRD_CLNT_ID = "SC_SPARROWZW_DB" THEN USD= TRN_AMT/361.900; 
		ELSE IF CRD_CLNT_ID = "SC_HOGANHK_DB" THEN USD= TRN_AMT/7.8;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWBD_DB" THEN USD = TRN_AMT_LOCAL/83.60;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCI_DB" THEN USD = TRN_AMT/562.55;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWCM_DB" THEN USD = TRN_AMT/570;
		ELSE IF CRD_CLNT_ID = "SC_SPARROWSL_DB" THEN USD = TRN_AMT/8300;
RUN;


